package com.hoopawolf.mwaw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelFirePet3 extends ModelBase {
    //fields
    ModelRenderer Head_Flame_1_;
    ModelRenderer Head_Flame_2;
    ModelRenderer Neck_Flame;
    ModelRenderer Back_Flame_1;
    ModelRenderer Back_Flame_2;
    ModelRenderer Right_Eyebrow;
    ModelRenderer Left_Eyebrow;
    ModelRenderer Right_Frill_1;
    ModelRenderer Right_Frill_2;
    ModelRenderer Right_Frill_3;
    ModelRenderer Left_Frill_1;
    ModelRenderer Left_Frill_2;
    ModelRenderer Left_Frill_3;
    ModelRenderer Right_Horn_1;
    ModelRenderer Right_Horn_2;
    ModelRenderer Right_Horn_3;
    ModelRenderer Right_Horn_4;
    ModelRenderer Left_Horn_1;
    ModelRenderer Left_Horn_2;
    ModelRenderer Left_Horn_3;
    ModelRenderer Left_Horn_4;
    ModelRenderer Head;
    ModelRenderer Snout;
    ModelRenderer Mouth;
    ModelRenderer Right_Tooth_1;
    ModelRenderer Right_Tooth_2;
    ModelRenderer Right_Tooth_3;
    ModelRenderer Left_Tooth_1;
    ModelRenderer Left_Tooth_2;
    ModelRenderer Left_Tooth_3;
    ModelRenderer Neck;
    ModelRenderer Chest;
    ModelRenderer Front_Torso;
    ModelRenderer Back_Torso;
    ModelRenderer Right_Shoulder_Armor_1;
    ModelRenderer Right_Shoulder_Armor_2;
    ModelRenderer Right_Shoulder_Armor_3;
    ModelRenderer Right_Shoulder_Armor_4;
    ModelRenderer Right_Shoulder_Armor_5;
    ModelRenderer Right_Shoulder_Armor_6;
    ModelRenderer Front_Right_Shoulder;
    ModelRenderer Front_Right_Leg_1;
    ModelRenderer Front_Right_Leg_2;
    ModelRenderer Front_Right_Foot;
    ModelRenderer Front_Right_Claw_1;
    ModelRenderer Front_Right_Claw_2;
    ModelRenderer Front_Right_Claw_3;
    ModelRenderer Front_Right_Backclaw;
    ModelRenderer Left_Shoulder_Armor_1;
    ModelRenderer Left_Shoulder_Armor_2;
    ModelRenderer Left_Shoulder_Armor_3;
    ModelRenderer Left_Shoulder_Armor_4;
    ModelRenderer Left_Shoulder_Armor_5;
    ModelRenderer Left_Shoulder_Armor_6;
    ModelRenderer Front_Left_Shoulder;
    ModelRenderer Front_Left_Leg_1;
    ModelRenderer Front_Left_Leg_2;
    ModelRenderer Front_Left_Foot;
    ModelRenderer Front_Left_Claw_1;
    ModelRenderer Front_Left_Claw_2;
    ModelRenderer Front_Left_Claw_3;
    ModelRenderer Front_Left_Backclaw;
    ModelRenderer Back_Right_Shoulder;
    ModelRenderer Back_Right_Leg_1;
    ModelRenderer Back_Right_Leg_2;
    ModelRenderer Back_Right_Foot;
    ModelRenderer Back_Right_Claw_1;
    ModelRenderer Back_Right_Claw_2;
    ModelRenderer Back_Right_Claw_3;
    ModelRenderer Back_Left_Shoulder;
    ModelRenderer Back_Left_Leg_1;
    ModelRenderer Back_Left_Leg_2;
    ModelRenderer Back_Left_Foot;
    ModelRenderer Back_Left_Claw_1;
    ModelRenderer Back_Left_Claw_2;
    ModelRenderer Back_Left_Claw_3;
    ModelRenderer Rear_1;
    ModelRenderer Rear_2;
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer Tail_3;
    ModelRenderer Tail_4;
    ModelRenderer Tail_5;

    public ModelFirePet3() {
        textureWidth = 512;
        textureHeight = 256;

        Head = new ModelRenderer(this, 356, 112);
        Head.addBox(-7F, -16F, -3F, 14, 14, 14);
        Head.setRotationPoint(0F, -7F, 0F);
        Head.setTextureSize(512, 256);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Head_Flame_1_ = new ModelRenderer(this, 294, 99);
        Head_Flame_1_.addBox(-6.5F, -15F, 10F, 13, 13, 16);
        Head_Flame_1_.setRotationPoint(0F, -7F, 0F);
        Head_Flame_1_.setTextureSize(512, 256);
        Head_Flame_1_.mirror = true;
        this.convertToChild(Head, Head_Flame_1_);
        setRotation(Head_Flame_1_, 0.1745329F, 0F, 0F);
        Head_Flame_2 = new ModelRenderer(this, 266, 93);
        Head_Flame_2.addBox(-3F, -15F, 27F, 6, 6, 16);
        Head_Flame_2.setRotationPoint(0F, -7F, 0F);
        Head_Flame_2.setTextureSize(512, 256);
        Head_Flame_2.mirror = true;
        this.convertToChild(Head, Head_Flame_2);
        setRotation(Head_Flame_2, 0.3490659F, 0F, 0F);
        Neck_Flame = new ModelRenderer(this, 286, 128);
        Neck_Flame.addBox(-6F, -7F, 7F, 12, 14, 8);
        Neck_Flame.setRotationPoint(0F, -7F, 0F);
        Neck_Flame.setTextureSize(512, 256);
        Neck_Flame.mirror = true;
        setRotation(Neck_Flame, 0.3490659F, 0F, 0F);
        Back_Flame_1 = new ModelRenderer(this, 226, 128);
        Back_Flame_1.addBox(-7F, -5F, 12F, 14, 6, 16);
        Back_Flame_1.setRotationPoint(0F, -7F, 0F);
        Back_Flame_1.setTextureSize(512, 256);
        Back_Flame_1.mirror = true;
        setRotation(Back_Flame_1, -0.0872665F, 0F, 0F);
        Back_Flame_2 = new ModelRenderer(this, 168, 129);
        Back_Flame_2.addBox(0F, -4F, 27F, 12, 4, 17);
        Back_Flame_2.setRotationPoint(-6F, -7F, 0F);
        Back_Flame_2.setTextureSize(512, 256);
        Back_Flame_2.mirror = true;
        setRotation(Back_Flame_2, -0.1396263F, 0F, 0F);
        Right_Eyebrow = new ModelRenderer(this, 398, 119);
        Right_Eyebrow.addBox(-7.5F, -12F, 5F, 1, 1, 6);
        Right_Eyebrow.setRotationPoint(0F, -7F, 0F);
        Right_Eyebrow.setTextureSize(512, 256);
        Right_Eyebrow.mirror = true;
        this.convertToChild(Head, Right_Eyebrow);
        setRotation(Right_Eyebrow, 0.5235988F, 0F, 0F);
        Left_Eyebrow = new ModelRenderer(this, 356, 119);
        Left_Eyebrow.addBox(6.5F, -12F, 5F, 1, 1, 6);
        Left_Eyebrow.setRotationPoint(0F, -7F, 0F);
        Left_Eyebrow.setTextureSize(512, 256);
        Left_Eyebrow.mirror = true;
        this.convertToChild(Head, Left_Eyebrow);
        setRotation(Left_Eyebrow, 0.5235988F, 0F, 0F);
        Right_Frill_1 = new ModelRenderer(this, 408, 59);
        Right_Frill_1.addBox(-4F, -13F, 14F, 2, 8, 10);
        Right_Frill_1.setRotationPoint(0F, -7F, 0F);
        Right_Frill_1.setTextureSize(512, 256);
        Right_Frill_1.mirror = true;
        this.convertToChild(Head, Right_Frill_1);
        setRotation(Right_Frill_1, 0.4363323F, -0.3490659F, 0F);
        Right_Frill_2 = new ModelRenderer(this, 406, 77);
        Right_Frill_2.addBox(-4F, -8F, 11F, 2, 2, 11);
        Right_Frill_2.setRotationPoint(0F, -7F, 0F);
        Right_Frill_2.setTextureSize(512, 256);
        Right_Frill_2.mirror = true;
        this.convertToChild(Head, Right_Frill_2);
        setRotation(Right_Frill_2, 0.0872665F, -0.3490659F, 0F);
        Right_Frill_3 = new ModelRenderer(this, 412, 90);
        Right_Frill_3.addBox(-4F, -7F, 9F, 2, 3, 8);
        Right_Frill_3.setRotationPoint(0F, -7F, 0F);
        Right_Frill_3.setTextureSize(512, 256);
        Right_Frill_3.mirror = true;
        this.convertToChild(Head, Right_Frill_3);
        setRotation(Right_Frill_3, -0.2617994F, -0.3490659F, 0F);
        Left_Frill_1 = new ModelRenderer(this, 336, 59);
        Left_Frill_1.addBox(2F, -13F, 14F, 2, 8, 10);
        Left_Frill_1.setRotationPoint(0F, -7F, 0F);
        Left_Frill_1.setTextureSize(512, 256);
        Left_Frill_1.mirror = true;
        this.convertToChild(Head, Left_Frill_1);
        setRotation(Left_Frill_1, 0.4363323F, 0.3490659F, 0F);
        Left_Frill_2 = new ModelRenderer(this, 336, 77);
        Left_Frill_2.addBox(2F, -8F, 11F, 2, 2, 11);
        Left_Frill_2.setRotationPoint(0F, -7F, 0F);
        Left_Frill_2.setTextureSize(512, 256);
        Left_Frill_2.mirror = true;
        this.convertToChild(Head, Left_Frill_2);
        setRotation(Left_Frill_2, 0.0872665F, 0.3490659F, 0F);
        Left_Frill_3 = new ModelRenderer(this, 336, 90);
        Left_Frill_3.addBox(2F, -7F, 9F, 2, 3, 8);
        Left_Frill_3.setRotationPoint(0F, -7F, 0F);
        Left_Frill_3.setTextureSize(512, 256);
        Left_Frill_3.mirror = true;
        this.convertToChild(Head, Left_Frill_3);
        setRotation(Left_Frill_3, -0.2617994F, 0.3490659F, 0F);
        Right_Horn_1 = new ModelRenderer(this, 398, 109);
        Right_Horn_1.addBox(-16F, -11F, 4F, 4, 3, 3);
        Right_Horn_1.setRotationPoint(0F, -7F, 0F);
        Right_Horn_1.setTextureSize(512, 256);
        Right_Horn_1.mirror = true;
        this.convertToChild(Head, Right_Horn_1);
        setRotation(Right_Horn_1, 0F, 0F, 0.5235988F);
        Right_Horn_2 = new ModelRenderer(this, 400, 103);
        Right_Horn_2.addBox(-21F, -2F, 4F, 3, 3, 3);
        Right_Horn_2.setRotationPoint(0F, -7F, 0F);
        Right_Horn_2.setTextureSize(512, 256);
        Right_Horn_2.mirror = true;
        this.convertToChild(Head, Right_Horn_2);
        setRotation(Right_Horn_2, 0F, 0F, 1.047198F);
        Right_Horn_3 = new ModelRenderer(this, 400, 97);
        Right_Horn_3.addBox(-21F, 8.5F, 4F, 3, 3, 3);
        Right_Horn_3.setRotationPoint(0F, -7F, 0F);
        Right_Horn_3.setTextureSize(512, 256);
        Right_Horn_3.mirror = true;
        this.convertToChild(Head, Right_Horn_3);
        setRotation(Right_Horn_3, 0F, 0F, 1.570796F);
        Right_Horn_4 = new ModelRenderer(this, 396, 91);
        Right_Horn_4.addBox(-18F, 17.5F, 4F, 5, 3, 3);
        Right_Horn_4.setRotationPoint(0F, -7F, 0F);
        Right_Horn_4.setTextureSize(512, 256);
        Right_Horn_4.mirror = true;
        this.convertToChild(Head, Right_Horn_4);
        setRotation(Right_Horn_4, 0F, 0F, 2.094395F);
        Left_Horn_1 = new ModelRenderer(this, 356, 109);
        Left_Horn_1.addBox(12F, -11F, 4F, 4, 3, 3);
        Left_Horn_1.setRotationPoint(0F, -7F, 0F);
        Left_Horn_1.setTextureSize(512, 256);
        Left_Horn_1.mirror = true;
        this.convertToChild(Head, Left_Horn_1);
        setRotation(Left_Horn_1, 0F, 0F, -0.5235988F);
        Left_Horn_2 = new ModelRenderer(this, 356, 103);
        Left_Horn_2.addBox(18F, -2F, 4F, 3, 3, 3);
        Left_Horn_2.setRotationPoint(0F, -7F, 0F);
        Left_Horn_2.setTextureSize(512, 256);
        Left_Horn_2.mirror = true;
        this.convertToChild(Head, Left_Horn_2);
        setRotation(Left_Horn_2, 0F, 0F, -1.047198F);
        Left_Horn_3 = new ModelRenderer(this, 356, 97);
        Left_Horn_3.addBox(18F, 8.5F, 4F, 3, 3, 3);
        Left_Horn_3.setRotationPoint(0F, -7F, 0F);
        Left_Horn_3.setTextureSize(512, 256);
        Left_Horn_3.mirror = true;
        this.convertToChild(Head, Left_Horn_3);
        setRotation(Left_Horn_3, 0F, 0F, -1.570796F);
        Left_Horn_4 = new ModelRenderer(this, 356, 91);
        Left_Horn_4.addBox(13F, 17.5F, 4F, 5, 3, 3);
        Left_Horn_4.setRotationPoint(0F, -7F, 0F);
        Left_Horn_4.setTextureSize(512, 256);
        Left_Horn_4.mirror = true;
        this.convertToChild(Head, Left_Horn_4);
        setRotation(Left_Horn_4, 0F, 0F, -2.094395F);
        Snout = new ModelRenderer(this, 412, 115);
        Snout.addBox(-4F, -10F, -13F, 8, 5, 10);
        Snout.setRotationPoint(0F, -7F, 0F);
        Snout.setTextureSize(512, 256);
        Snout.mirror = true;
        this.convertToChild(Head, Snout);
        setRotation(Snout, 0F, 0F, 0F);
        Mouth = new ModelRenderer(this, 412, 142);
        Mouth.addBox(-3F, -5F, -12.5F, 6, 3, 10);
        Mouth.setRotationPoint(0F, -7F, 0F);
        Mouth.setTextureSize(512, 256);
        Mouth.mirror = true;
        this.convertToChild(Head, Mouth);
        setRotation(Mouth, 0F, 0F, 0F);
        Right_Tooth_1 = new ModelRenderer(this, 412, 130);
        Right_Tooth_1.addBox(-3.5F, -9F, -1F, 1, 3, 3);
        Right_Tooth_1.setRotationPoint(0F, -7F, 0F);
        Right_Tooth_1.setTextureSize(512, 256);
        Right_Tooth_1.mirror = true;
        this.convertToChild(Head, Right_Tooth_1);
        setRotation(Right_Tooth_1, 0.8726646F, 0F, 0F);
        Right_Tooth_2 = new ModelRenderer(this, 420, 130);
        Right_Tooth_2.addBox(-3.5F, -11F, -3F, 1, 2, 2);
        Right_Tooth_2.setRotationPoint(0F, -7F, 0F);
        Right_Tooth_2.setTextureSize(512, 256);
        Right_Tooth_2.mirror = true;
        this.convertToChild(Head, Right_Tooth_2);
        setRotation(Right_Tooth_2, 0.8726646F, 0F, 0F);
        Right_Tooth_3 = new ModelRenderer(this, 426, 130);
        Right_Tooth_3.addBox(-3.5F, -12F, -4F, 1, 1, 1);
        Right_Tooth_3.setRotationPoint(0F, -7F, 0F);
        Right_Tooth_3.setTextureSize(512, 256);
        Right_Tooth_3.mirror = true;
        this.convertToChild(Head, Right_Tooth_3);
        setRotation(Right_Tooth_3, 0.8726646F, 0F, 0F);
        Left_Tooth_1 = new ModelRenderer(this, 412, 136);
        Left_Tooth_1.addBox(2.5F, -9F, -1F, 1, 3, 3);
        Left_Tooth_1.setRotationPoint(0F, -7F, 0F);
        Left_Tooth_1.setTextureSize(512, 256);
        Left_Tooth_1.mirror = true;
        this.convertToChild(Head, Left_Tooth_1);
        setRotation(Left_Tooth_1, 0.8726646F, 0F, 0F);
        Left_Tooth_2 = new ModelRenderer(this, 420, 138);
        Left_Tooth_2.addBox(2.5F, -11F, -3F, 1, 2, 2);
        Left_Tooth_2.setRotationPoint(0F, -7F, 0F);
        Left_Tooth_2.setTextureSize(512, 256);
        Left_Tooth_2.mirror = true;
        this.convertToChild(Head, Left_Tooth_2);
        setRotation(Left_Tooth_2, 0.8726646F, 0F, 0F);
        Left_Tooth_3 = new ModelRenderer(this, 426, 140);
        Left_Tooth_3.addBox(2.5F, -12F, -4F, 1, 1, 1);
        Left_Tooth_3.setRotationPoint(0F, -7F, 0F);
        Left_Tooth_3.setTextureSize(512, 256);
        Left_Tooth_3.mirror = true;
        this.convertToChild(Head, Left_Tooth_3);
        setRotation(Left_Tooth_3, 0.8726646F, 0F, 0F);
        Neck = new ModelRenderer(this, 326, 130);
        Neck.addBox(-5F, -3F, 0F, 10, 10, 10);
        Neck.setRotationPoint(0F, -7F, 0F);
        Neck.setTextureSize(512, 256);
        Neck.mirror = true;
        setRotation(Neck, 0.2617994F, 0F, 0F);
        Chest = new ModelRenderer(this, 366, 172);
        Chest.addBox(-8F, 0F, -1F, 16, 18, 1);
        Chest.setRotationPoint(0F, -7F, 0F);
        Chest.setTextureSize(512, 256);
        Chest.mirror = true;
        setRotation(Chest, -0.0523599F, 0F, 0F);
        Front_Torso = new ModelRenderer(this, 282, 150);
        Front_Torso.addBox(-10F, 0F, 0F, 20, 20, 22);
        Front_Torso.setRotationPoint(0F, -7F, 0F);
        Front_Torso.setTextureSize(512, 256);
        Front_Torso.mirror = true;
        setRotation(Front_Torso, -0.0523599F, 0F, 0F);
        Back_Torso = new ModelRenderer(this, 210, 150);
        Back_Torso.addBox(-9F, 2F, 21F, 18, 18, 18);
        Back_Torso.setRotationPoint(0F, -7F, 0F);
        Back_Torso.setTextureSize(512, 256);
        Back_Torso.mirror = true;
        setRotation(Back_Torso, 0F, 0F, 0F);
        Front_Right_Shoulder = new ModelRenderer(this, 402, 192);
        Front_Right_Shoulder.addBox(-8F, -4F, -4F, 8, 8, 8);
        Front_Right_Shoulder.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Shoulder.setTextureSize(512, 256);
        Front_Right_Shoulder.mirror = true;
        setRotation(Front_Right_Shoulder, 0F, 0F, 0F);
        Right_Shoulder_Armor_1 = new ModelRenderer(this, 0, 201);
        Right_Shoulder_Armor_1.addBox(-9F, -6F, -6F, 6, 9, 12);
        Right_Shoulder_Armor_1.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_1.setTextureSize(512, 256);
        Right_Shoulder_Armor_1.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_1);
        setRotation(Right_Shoulder_Armor_1, 0.5235988F, -0.0872665F, 0F);
        Right_Shoulder_Armor_2 = new ModelRenderer(this, 36, 210);
        Right_Shoulder_Armor_2.addBox(-9F, -6F, 6F, 5, 8, 4);
        Right_Shoulder_Armor_2.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_2.setTextureSize(512, 256);
        Right_Shoulder_Armor_2.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_2);
        setRotation(Right_Shoulder_Armor_2, 0.5235988F, -0.0872665F, 0F);
        Right_Shoulder_Armor_3 = new ModelRenderer(this, 54, 211);
        Right_Shoulder_Armor_3.addBox(-9F, -6F, 10F, 4, 7, 4);
        Right_Shoulder_Armor_3.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_3.setTextureSize(512, 256);
        Right_Shoulder_Armor_3.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_3);
        setRotation(Right_Shoulder_Armor_3, 0.5235988F, -0.0872665F, 0F);
        Right_Shoulder_Armor_4 = new ModelRenderer(this, 70, 212);
        Right_Shoulder_Armor_4.addBox(-9F, -6F, 14F, 3, 6, 4);
        Right_Shoulder_Armor_4.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_4.setTextureSize(512, 256);
        Right_Shoulder_Armor_4.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_4);
        setRotation(Right_Shoulder_Armor_4, 0.5235988F, -0.0872665F, 0F);
        Right_Shoulder_Armor_5 = new ModelRenderer(this, 84, 213);
        Right_Shoulder_Armor_5.addBox(-9F, -6F, 18F, 2, 5, 4);
        Right_Shoulder_Armor_5.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_5.setTextureSize(512, 256);
        Right_Shoulder_Armor_5.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_5);
        setRotation(Right_Shoulder_Armor_5, 0.5235988F, -0.0872665F, 0F);
        Right_Shoulder_Armor_6 = new ModelRenderer(this, 96, 207);
        Right_Shoulder_Armor_6.addBox(-9F, -6F, 22F, 1, 3, 12);
        Right_Shoulder_Armor_6.setRotationPoint(-10F, 3F, 6F);
        Right_Shoulder_Armor_6.setTextureSize(512, 256);
        Right_Shoulder_Armor_6.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Right_Shoulder_Armor_6);
        setRotation(Right_Shoulder_Armor_6, 0.5235988F, -0.0872665F, 0F);
        Front_Right_Leg_1 = new ModelRenderer(this, 370, 192);
        Front_Right_Leg_1.addBox(-8F, 1F, -5F, 8, 11, 8);
        Front_Right_Leg_1.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Leg_1.setTextureSize(512, 256);
        Front_Right_Leg_1.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Leg_1);
        setRotation(Front_Right_Leg_1, 0.7330383F, 0F, 0F);
        Front_Right_Leg_2 = new ModelRenderer(this, 370, 211);
        Front_Right_Leg_2.addBox(-8F, 4F, 7F, 8, 13, 8);
        Front_Right_Leg_2.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Leg_2.setTextureSize(512, 256);
        Front_Right_Leg_2.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Leg_2);
        setRotation(Front_Right_Leg_2, -0.2617994F, 0F, 0F);
        Front_Right_Foot = new ModelRenderer(this, 370, 232);
        Front_Right_Foot.addBox(-8F, 17F, 1.5F, 8, 4, 9);
        Front_Right_Foot.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Foot.setTextureSize(512, 256);
        Front_Right_Foot.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Foot);
        setRotation(Front_Right_Foot, 0F, 0F, 0F);
        Front_Right_Claw_1 = new ModelRenderer(this, 404, 240);
        Front_Right_Claw_1.addBox(-9F, 18F, -3F, 1, 3, 10);
        Front_Right_Claw_1.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Claw_1.setTextureSize(512, 256);
        Front_Right_Claw_1.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Claw_1);
        setRotation(Front_Right_Claw_1, 0F, 0.1745329F, 0F);
        Front_Right_Claw_2 = new ModelRenderer(this, 404, 233);
        Front_Right_Claw_2.addBox(-5F, 18F, -2F, 2, 3, 4);
        Front_Right_Claw_2.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Claw_2.setTextureSize(512, 256);
        Front_Right_Claw_2.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Claw_2);
        setRotation(Front_Right_Claw_2, 0F, 0F, 0F);
        Front_Right_Claw_3 = new ModelRenderer(this, 404, 220);
        Front_Right_Claw_3.addBox(0F, 18F, -1.5F, 1, 3, 10);
        Front_Right_Claw_3.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Claw_3.setTextureSize(512, 256);
        Front_Right_Claw_3.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Claw_3);
        setRotation(Front_Right_Claw_3, 0F, -0.1745329F, 0F);
        Front_Right_Backclaw = new ModelRenderer(this, 360, 239);
        Front_Right_Backclaw.addBox(-4.5F, 19F, 10F, 1, 2, 4);
        Front_Right_Backclaw.setRotationPoint(-10F, 3F, 6F);
        Front_Right_Backclaw.setTextureSize(512, 256);
        Front_Right_Backclaw.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Backclaw);
        setRotation(Front_Right_Backclaw, 0F, 0F, 0F);
        Front_Left_Shoulder = new ModelRenderer(this, 338, 192);
        Front_Left_Shoulder.addBox(0F, -4F, -4F, 8, 8, 8);
        Front_Left_Shoulder.setRotationPoint(10F, 3F, 6F);
        Front_Left_Shoulder.setTextureSize(512, 256);
        Front_Left_Shoulder.mirror = true;
        setRotation(Front_Left_Shoulder, 0F, 0F, 0F);
        Left_Shoulder_Armor_1 = new ModelRenderer(this, 0, 180);
        Left_Shoulder_Armor_1.addBox(3F, -6F, -6F, 6, 9, 12);
        Left_Shoulder_Armor_1.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_1.setTextureSize(512, 256);
        Left_Shoulder_Armor_1.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_1);
        setRotation(Left_Shoulder_Armor_1, 0.5235988F, 0.0872665F, 0F);
        Left_Shoulder_Armor_2 = new ModelRenderer(this, 36, 189);
        Left_Shoulder_Armor_2.addBox(4F, -6F, 6F, 5, 8, 4);
        Left_Shoulder_Armor_2.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_2.setTextureSize(512, 256);
        Left_Shoulder_Armor_2.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_2);
        setRotation(Left_Shoulder_Armor_2, 0.5235988F, 0.0872665F, 0F);
        Left_Shoulder_Armor_3 = new ModelRenderer(this, 54, 190);
        Left_Shoulder_Armor_3.addBox(5F, -6F, 10F, 4, 7, 4);
        Left_Shoulder_Armor_3.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_3.setTextureSize(512, 256);
        Left_Shoulder_Armor_3.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_3);
        setRotation(Left_Shoulder_Armor_3, 0.5235988F, 0.0872665F, 0F);
        Left_Shoulder_Armor_4 = new ModelRenderer(this, 70, 191);
        Left_Shoulder_Armor_4.addBox(6F, -6F, 14F, 3, 6, 4);
        Left_Shoulder_Armor_4.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_4.setTextureSize(512, 256);
        Left_Shoulder_Armor_4.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_4);
        setRotation(Left_Shoulder_Armor_4, 0.5235988F, 0.0872665F, 0F);
        Left_Shoulder_Armor_5 = new ModelRenderer(this, 84, 192);
        Left_Shoulder_Armor_5.addBox(7F, -6F, 18F, 2, 5, 4);
        Left_Shoulder_Armor_5.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_5.setTextureSize(512, 256);
        Left_Shoulder_Armor_5.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_5);
        setRotation(Left_Shoulder_Armor_5, 0.5235988F, 0.0872665F, 0F);
        Left_Shoulder_Armor_6 = new ModelRenderer(this, 96, 186);
        Left_Shoulder_Armor_6.addBox(8F, -6F, 22F, 1, 3, 12);
        Left_Shoulder_Armor_6.setRotationPoint(10F, 3F, 6F);
        Left_Shoulder_Armor_6.setTextureSize(512, 256);
        Left_Shoulder_Armor_6.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Left_Shoulder_Armor_6);
        setRotation(Left_Shoulder_Armor_6, 0.5235988F, 0.0872665F, 0F);
        Front_Left_Leg_1 = new ModelRenderer(this, 306, 192);
        Front_Left_Leg_1.addBox(0F, 1F, -5F, 8, 11, 8);
        Front_Left_Leg_1.setRotationPoint(10F, 3F, 6F);
        Front_Left_Leg_1.setTextureSize(512, 256);
        Front_Left_Leg_1.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Leg_1);
        setRotation(Front_Left_Leg_1, 0.7330383F, 0F, 0F);
        Front_Left_Leg_2 = new ModelRenderer(this, 306, 211);
        Front_Left_Leg_2.addBox(0F, 4F, 7F, 8, 13, 8);
        Front_Left_Leg_2.setRotationPoint(10F, 3F, 6F);
        Front_Left_Leg_2.setTextureSize(512, 256);
        Front_Left_Leg_2.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Leg_2);
        setRotation(Front_Left_Leg_2, -0.2617994F, 0F, 0F);
        Front_Left_Foot = new ModelRenderer(this, 306, 232);
        Front_Left_Foot.addBox(0F, 17F, 1.5F, 8, 4, 9);
        Front_Left_Foot.setRotationPoint(10F, 3F, 6F);
        Front_Left_Foot.setTextureSize(512, 256);
        Front_Left_Foot.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Foot);
        setRotation(Front_Left_Foot, 0F, 0F, 0F);
        Front_Left_Claw_1 = new ModelRenderer(this, 340, 220);
        Front_Left_Claw_1.addBox(8F, 18F, -3F, 1, 3, 10);
        Front_Left_Claw_1.setRotationPoint(10F, 3F, 6F);
        Front_Left_Claw_1.setTextureSize(512, 256);
        Front_Left_Claw_1.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Claw_1);
        setRotation(Front_Left_Claw_1, 0F, -0.1745329F, 0F);
        Front_Left_Claw_2 = new ModelRenderer(this, 340, 233);
        Front_Left_Claw_2.addBox(3F, 18F, -2F, 2, 3, 4);
        Front_Left_Claw_2.setRotationPoint(10F, 3F, 6F);
        Front_Left_Claw_2.setTextureSize(512, 256);
        Front_Left_Claw_2.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Claw_2);
        setRotation(Front_Left_Claw_2, 0F, -0.0174533F, 0F);
        Front_Left_Claw_3 = new ModelRenderer(this, 340, 240);
        Front_Left_Claw_3.addBox(-1F, 18F, -1.5F, 1, 3, 10);
        Front_Left_Claw_3.setRotationPoint(10F, 3F, 6F);
        Front_Left_Claw_3.setTextureSize(512, 256);
        Front_Left_Claw_3.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Claw_3);
        setRotation(Front_Left_Claw_3, 0F, 0.1745329F, 0F);
        Front_Left_Backclaw = new ModelRenderer(this, 296, 239);
        Front_Left_Backclaw.addBox(3.5F, 19F, 10F, 1, 2, 4);
        Front_Left_Backclaw.setRotationPoint(10F, 3F, 6F);
        Front_Left_Backclaw.setTextureSize(512, 256);
        Front_Left_Backclaw.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Backclaw);
        setRotation(Front_Left_Backclaw, 0F, 0F, 0F);
        Back_Right_Shoulder = new ModelRenderer(this, 274, 192);
        Back_Right_Shoulder.addBox(-8F, -4F, -4F, 8, 8, 8);
        Back_Right_Shoulder.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Shoulder.setTextureSize(512, 256);
        Back_Right_Shoulder.mirror = true;
        setRotation(Back_Right_Shoulder, 0F, 0F, 0F);
        Back_Right_Leg_1 = new ModelRenderer(this, 242, 192);
        Back_Right_Leg_1.addBox(-8F, 0F, -5F, 8, 11, 8);
        Back_Right_Leg_1.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Leg_1.setTextureSize(512, 256);
        Back_Right_Leg_1.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Leg_1);
        setRotation(Back_Right_Leg_1, 0.7330383F, 0F, 0F);
        Back_Right_Leg_2 = new ModelRenderer(this, 242, 211);
        Back_Right_Leg_2.addBox(-8F, 3F, 4F, 8, 11, 8);
        Back_Right_Leg_2.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Leg_2.setTextureSize(512, 256);
        Back_Right_Leg_2.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Leg_2);
        setRotation(Back_Right_Leg_2, -0.2617994F, 0F, 0F);
        Back_Right_Foot = new ModelRenderer(this, 242, 230);
        Back_Right_Foot.addBox(-8F, 14F, -1F, 8, 3, 9);
        Back_Right_Foot.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Foot.setTextureSize(512, 256);
        Back_Right_Foot.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Foot);
        setRotation(Back_Right_Foot, 0F, 0F, 0F);
        Back_Right_Claw_1 = new ModelRenderer(this, 266, 242);
        Back_Right_Claw_1.addBox(-8F, 15F, -5.5F, 1, 2, 5);
        Back_Right_Claw_1.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Claw_1.setTextureSize(512, 256);
        Back_Right_Claw_1.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Claw_1);
        setRotation(Back_Right_Claw_1, 0F, 0.1745329F, 0F);
        Back_Right_Claw_2 = new ModelRenderer(this, 254, 242);
        Back_Right_Claw_2.addBox(-5F, 15F, -5F, 2, 2, 4);
        Back_Right_Claw_2.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Claw_2.setTextureSize(512, 256);
        Back_Right_Claw_2.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Claw_2);
        setRotation(Back_Right_Claw_2, 0F, 0F, 0F);
        Back_Right_Claw_3 = new ModelRenderer(this, 242, 242);
        Back_Right_Claw_3.addBox(-1F, 15F, -4F, 1, 2, 5);
        Back_Right_Claw_3.setRotationPoint(-9F, 7F, 32F);
        Back_Right_Claw_3.setTextureSize(512, 256);
        Back_Right_Claw_3.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Claw_3);
        setRotation(Back_Right_Claw_3, 0F, -0.1745329F, 0F);
        Back_Left_Shoulder = new ModelRenderer(this, 210, 192);
        Back_Left_Shoulder.addBox(0F, -4F, -4F, 8, 8, 8);
        Back_Left_Shoulder.setRotationPoint(9F, 7F, 32F);
        Back_Left_Shoulder.setTextureSize(512, 256);
        Back_Left_Shoulder.mirror = true;
        setRotation(Back_Left_Shoulder, 0F, 0F, 0F);
        Back_Left_Leg_1 = new ModelRenderer(this, 178, 192);
        Back_Left_Leg_1.addBox(0F, 0F, -5F, 8, 11, 8);
        Back_Left_Leg_1.setRotationPoint(9F, 7F, 32F);
        Back_Left_Leg_1.setTextureSize(512, 256);
        Back_Left_Leg_1.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Leg_1);
        setRotation(Back_Left_Leg_1, 0.7330383F, 0F, 0F);
        Back_Left_Leg_2 = new ModelRenderer(this, 178, 211);
        Back_Left_Leg_2.addBox(0F, 3F, 4F, 8, 11, 8);
        Back_Left_Leg_2.setRotationPoint(9F, 7F, 32F);
        Back_Left_Leg_2.setTextureSize(512, 256);
        Back_Left_Leg_2.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Leg_2);
        setRotation(Back_Left_Leg_2, -0.2617994F, 0F, 0F);
        Back_Left_Foot = new ModelRenderer(this, 178, 230);
        Back_Left_Foot.addBox(0F, 14F, -1F, 8, 3, 9);
        Back_Left_Foot.setRotationPoint(9F, 7F, 32F);
        Back_Left_Foot.setTextureSize(512, 256);
        Back_Left_Foot.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Foot);
        setRotation(Back_Left_Foot, 0F, 0F, 0F);
        Back_Left_Claw_1 = new ModelRenderer(this, 178, 242);
        Back_Left_Claw_1.addBox(7F, 15F, -5.5F, 1, 2, 5);
        Back_Left_Claw_1.setRotationPoint(9F, 7F, 32F);
        Back_Left_Claw_1.setTextureSize(512, 256);
        Back_Left_Claw_1.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Claw_1);
        setRotation(Back_Left_Claw_1, 0F, -0.1745329F, 0F);
        Back_Left_Claw_2 = new ModelRenderer(this, 190, 242);
        Back_Left_Claw_2.addBox(3F, 15F, -5F, 2, 2, 4);
        Back_Left_Claw_2.setRotationPoint(9F, 7F, 32F);
        Back_Left_Claw_2.setTextureSize(512, 256);
        Back_Left_Claw_2.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Claw_2);
        setRotation(Back_Left_Claw_2, 0F, 0F, 0F);
        Back_Left_Claw_3 = new ModelRenderer(this, 202, 242);
        Back_Left_Claw_3.addBox(0F, 15F, -4F, 1, 2, 5);
        Back_Left_Claw_3.setRotationPoint(9F, 7F, 32F);
        Back_Left_Claw_3.setTextureSize(512, 256);
        Back_Left_Claw_3.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Claw_3);
        setRotation(Back_Left_Claw_3, 0F, 0.1745329F, 0F);
        Rear_1 = new ModelRenderer(this, 192, 150);
        Rear_1.addBox(-8F, 3F, 39F, 16, 16, 2);
        Rear_1.setRotationPoint(0F, -7F, 0F);
        Rear_1.setTextureSize(512, 256);
        Rear_1.mirror = true;
        setRotation(Rear_1, 0F, 0F, 0F);
        Rear_2 = new ModelRenderer(this, 160, 150);
        Rear_2.addBox(-7F, 4F, 41F, 14, 14, 2);
        Rear_2.setRotationPoint(0F, -7F, 0F);
        Rear_2.setTextureSize(512, 256);
        Rear_2.mirror = true;
        setRotation(Rear_2, 0F, 0F, 0F);
        Tail_1 = new ModelRenderer(this, 112, 150);
        Tail_1.addBox(-6F, -10.5F, 41F, 12, 12, 12);
        Tail_1.setRotationPoint(0F, -7F, 0F);
        Tail_1.setTextureSize(512, 256);
        Tail_1.mirror = true;
        setRotation(Tail_1, -0.3490659F, 0F, 0F);
        Tail_2 = new ModelRenderer(this, 72, 150);
        Tail_2.addBox(-5F, -5F, 52F, 10, 10, 10);
        Tail_2.setRotationPoint(0F, -7F, 0F);
        Tail_2.setTextureSize(512, 256);
        Tail_2.mirror = true;
        setRotation(Tail_2, -0.2617994F, 0F, 0F);
        Tail_3 = new ModelRenderer(this, 40, 150);
        Tail_3.addBox(-4F, 1F, 61F, 8, 8, 8);
        Tail_3.setRotationPoint(0F, -7F, 0F);
        Tail_3.setTextureSize(512, 256);
        Tail_3.mirror = true;
        setRotation(Tail_3, -0.1745329F, 0F, 0F);
        Tail_4 = new ModelRenderer(this, 16, 150);
        Tail_4.addBox(-3F, 8F, 68F, 6, 6, 6);
        Tail_4.setRotationPoint(0F, -7F, 0F);
        Tail_4.setTextureSize(512, 256);
        Tail_4.mirror = true;
        setRotation(Tail_4, -0.0872665F, 0F, 0F);
        Tail_5 = new ModelRenderer(this, 0, 150);
        Tail_5.addBox(-2F, 15F, 72F, 4, 4, 4);
        Tail_5.setRotationPoint(0F, -7F, 0F);
        Tail_5.setTextureSize(512, 256);
        Tail_5.mirror = true;
        setRotation(Tail_5, 0F, 0F, 0F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        GL11.glTranslatef(0.0F, 0.0F, -0.5F);

        Head.render(f5);
        Neck.render(f5);
        Chest.render(f5);
        Neck_Flame.render(f5);
        Back_Flame_1.render(f5);
        Back_Flame_2.render(f5);
        Front_Torso.render(f5);
        Back_Torso.render(f5);
        Front_Right_Shoulder.render(f5);
        Front_Left_Shoulder.render(f5);
        Back_Right_Shoulder.render(f5);
        Back_Left_Shoulder.render(f5);
        Rear_1.render(f5);
        Rear_2.render(f5);
        Tail_1.render(f5);
        Tail_2.render(f5);
        Tail_3.render(f5);
        Tail_4.render(f5);
        Tail_5.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);

///////////////////////////////LEGS///////////////////////////////////////
        this.Front_Left_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Front_Right_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        this.Back_Right_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Back_Left_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;
    }


}