package com.hoopawolf.mwaw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelLightningPet3 extends ModelBase {
    //fields
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer Tail_3;
    ModelRenderer Tail_Tip_1;
    ModelRenderer Tail_Tip_2;
    ModelRenderer Tail_Tip_3;
    ModelRenderer Tail_Tip_4;
    ModelRenderer Rear;
    ModelRenderer Lower_Torso;
    ModelRenderer Upper_Torso;
    ModelRenderer Chest;
    ModelRenderer Head;
    ModelRenderer Horn_Base_1;
    ModelRenderer Horn_Base_2;
    ModelRenderer Horn_1;
    ModelRenderer Horn_2;
    ModelRenderer Horn_3;
    ModelRenderer Horn_4;
    ModelRenderer Snout;
    ModelRenderer Undermouth_1;
    ModelRenderer Undermouth_2;
    ModelRenderer Neck;
    ModelRenderer Right_Frill_1;
    ModelRenderer Right_Frill_2;
    ModelRenderer Right_Frill_3;
    ModelRenderer Right_Frill_4;
    ModelRenderer Right_Frill_5;
    ModelRenderer Right_Frill_6;
    ModelRenderer Right_Sideburn;
    ModelRenderer Left_Frill_1;
    ModelRenderer Left_Frill_2;
    ModelRenderer Left_Frill_3;
    ModelRenderer Left_Frill_4;
    ModelRenderer Left_Frill_5;
    ModelRenderer Left_Frill_6;
    ModelRenderer Left_Sideburn;
    ModelRenderer Hair_1;
    ModelRenderer Hair_2;
    ModelRenderer Hair_3;
    ModelRenderer Hair_4;
    ModelRenderer Hair_5;
    ModelRenderer Hair_6;
    ModelRenderer Hair_7;
    ModelRenderer Front_Right_Leg_1;
    ModelRenderer Front_Right_Leg_2;
    ModelRenderer Front_Right_Foot;
    ModelRenderer Front_Right_Claw_1;
    ModelRenderer Front_Right_Claw_2;
    ModelRenderer Front_Right_Claw_3;
    ModelRenderer Front_Left_Leg_1;
    ModelRenderer Front_Left_Leg_2;
    ModelRenderer Front_Left_Foot;
    ModelRenderer Front_Left_Claw_1;
    ModelRenderer Front_Left_Claw_2;
    ModelRenderer Front_Left_Claw_3;
    ModelRenderer Back_Right_Leg_1;
    ModelRenderer Back_Right_Leg_2;
    ModelRenderer Back_Right_Foot;
    ModelRenderer Back_Right_Claw_1;
    ModelRenderer Back_Right_Claw_2;
    ModelRenderer Back_Right_Claw_3;
    ModelRenderer Back_Left_Leg_1;
    ModelRenderer Back_Left_Leg_2;
    ModelRenderer Back_Left_Foot;
    ModelRenderer Back_Left_Claw_1;
    ModelRenderer Back_Left_Claw_2;
    ModelRenderer Back_Left_Claw_3;
    ModelRenderer Right_Wing_Membrane_1;
    ModelRenderer Right_Wing_Membrane_2;
    ModelRenderer Right_Wing_Membrane_3;
    ModelRenderer Right_Wing_1;
    ModelRenderer Right_Wing_2;
    ModelRenderer Right_Wing_3;
    ModelRenderer Right_Wing_4;
    ModelRenderer Right_Wing_5;
    ModelRenderer Left_Wing_Membrane_1;
    ModelRenderer Left_Wing_Membrane_2;
    ModelRenderer Left_Wing_Membrane_3;
    ModelRenderer Left_Wing_1;
    ModelRenderer Left_Wing_2;
    ModelRenderer Left_Wing_3;
    ModelRenderer Left_Wing_4;
    ModelRenderer Left_Wing_5;

    public ModelLightningPet3() {
        textureWidth = 512;
        textureHeight = 256;

        Tail_1 = new ModelRenderer(this, 24, 183);
        Tail_1.addBox(-3F, -1F, 1F, 6, 6, 10);
        Tail_1.setRotationPoint(0F, 5F, 34F);
        Tail_1.setTextureSize(512, 256);
        Tail_1.mirror = true;
        setRotation(Tail_1, 1.047198F, 0F, 0F);
        Tail_2 = new ModelRenderer(this, 0, 177);
        Tail_2.addBox(-3F, 5F, 5F, 6, 6, 10);
        Tail_2.setRotationPoint(0F, 5F, 34F);
        Tail_2.setTextureSize(512, 256);
        Tail_2.mirror = true;
        setRotation(Tail_2, 1.745329F, 0F, 0F);
        Tail_3 = new ModelRenderer(this, 22, 167);
        Tail_3.addBox(-3F, 12.5F, 4F, 6, 6, 10);
        Tail_3.setRotationPoint(0F, 5F, 34F);
        Tail_3.setTextureSize(512, 256);
        Tail_3.mirror = true;
        setRotation(Tail_3, 2.443461F, 0F, 0F);
        Tail_Tip_1 = new ModelRenderer(this, 44, 157);
        Tail_Tip_1.addBox(-5F, 9F, 12F, 10, 10, 10);
        Tail_Tip_1.setRotationPoint(0F, 5F, 34F);
        Tail_Tip_1.setTextureSize(512, 256);
        Tail_Tip_1.mirror = true;
        setRotation(Tail_Tip_1, 2.356194F, 0F, 0F);
        Tail_Tip_2 = new ModelRenderer(this, 64, 145);
        Tail_Tip_2.addBox(-3F, -25F, -11F, 6, 6, 6);
        Tail_Tip_2.setRotationPoint(0F, 5F, 34F);
        Tail_Tip_2.setTextureSize(512, 256);
        Tail_Tip_2.mirror = true;
        setRotation(Tail_Tip_2, 0F, 0F, 0F);
        Tail_Tip_3 = new ModelRenderer(this, 88, 146);
        Tail_Tip_3.addBox(-2F, -24F, -17F, 4, 4, 6);
        Tail_Tip_3.setRotationPoint(0F, 5F, 34F);
        Tail_Tip_3.setTextureSize(512, 256);
        Tail_Tip_3.mirror = true;
        setRotation(Tail_Tip_3, 0F, 0F, 0F);
        Tail_Tip_4 = new ModelRenderer(this, 108, 150);
        Tail_Tip_4.addBox(-1F, -23F, -19F, 2, 2, 2);
        Tail_Tip_4.setRotationPoint(0F, 5F, 34F);
        Tail_Tip_4.setTextureSize(512, 256);
        Tail_Tip_4.mirror = true;
        setRotation(Tail_Tip_4, 0F, 0F, 0F);
        Rear = new ModelRenderer(this, 49, 192);
        Rear.addBox(-5F, -6F, -3F, 10, 10, 7);
        Rear.setRotationPoint(0F, 5F, 34F);
        Rear.setTextureSize(512, 256);
        Rear.mirror = true;
        setRotation(Rear, 0.3490659F, 0F, 0F);
        Lower_Torso = new ModelRenderer(this, 83, 173);
        Lower_Torso.addBox(-8F, 2.5F, 18F, 16, 16, 16);
        Lower_Torso.setRotationPoint(0F, -6F, 0F);
        Lower_Torso.setTextureSize(512, 256);
        Lower_Torso.mirror = true;
        setRotation(Lower_Torso, 0F, 0F, 0F);
        Upper_Torso = new ModelRenderer(this, 147, 170);
        Upper_Torso.addBox(-9F, 0F, 0F, 18, 18, 20);
        Upper_Torso.setRotationPoint(0F, -6F, 0F);
        Upper_Torso.setTextureSize(512, 256);
        Upper_Torso.mirror = true;
        setRotation(Upper_Torso, -0.0698132F, 0F, 0F);
        Chest = new ModelRenderer(this, 223, 190);
        Chest.addBox(-8F, 2F, -5F, 16, 14, 6);
        Chest.setRotationPoint(0F, -6F, 0F);
        Chest.setTextureSize(512, 256);
        Chest.mirror = true;
        setRotation(Chest, 0F, 0F, 0F);
        Head = new ModelRenderer(this, 229, 156);
        Head.addBox(-6F, -12F, -9F, 12, 12, 10);
        Head.setRotationPoint(0F, -6F, 0F);
        Head.setTextureSize(512, 256);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Horn_Base_1 = new ModelRenderer(this, 247, 148);
        Horn_Base_1.addBox(-3F, -15F, 0F, 6, 4, 4);
        Horn_Base_1.setRotationPoint(0F, -6F, 0F);
        Horn_Base_1.setTextureSize(512, 256);
        Horn_Base_1.mirror = true;
        this.convertToChild(Head, Horn_Base_1);
        setRotation(Horn_Base_1, 0.3665191F, 0F, 0F);
        Horn_Base_2 = new ModelRenderer(this, 229, 149);
        Horn_Base_2.addBox(-3F, -14F, 5F, 6, 4, 3);
        Horn_Base_2.setRotationPoint(0F, -6F, 0F);
        Horn_Base_2.setTextureSize(512, 256);
        Horn_Base_2.mirror = true;
        this.convertToChild(Head, Horn_Base_2);
        setRotation(Horn_Base_2, 0.5061455F, 0F, 0F);
        Horn_1 = new ModelRenderer(this, 239, 143);
        Horn_1.addBox(-1F, -17F, -8F, 2, 4, 2);
        Horn_1.setRotationPoint(0F, -6F, 0F);
        Horn_1.setTextureSize(512, 256);
        Horn_1.mirror = true;
        this.convertToChild(Head, Horn_1);
        setRotation(Horn_1, -0.4712389F, 0F, 0F);
        Horn_2 = new ModelRenderer(this, 249, 140);
        Horn_2.addBox(-1F, -20F, 3F, 2, 6, 2);
        Horn_2.setRotationPoint(0F, -6F, 0F);
        Horn_2.setTextureSize(512, 256);
        Horn_2.mirror = true;
        this.convertToChild(Head, Horn_2);
        setRotation(Horn_2, 0.3316126F, 0F, 0F);
        Horn_3 = new ModelRenderer(this, 263, 137);
        Horn_3.addBox(-1.5F, -24F, 6F, 3, 12, 3);
        Horn_3.setRotationPoint(0F, -6F, 0F);
        Horn_3.setTextureSize(512, 256);
        Horn_3.mirror = true;
        this.convertToChild(Head, Horn_3);
        setRotation(Horn_3, 0.7853982F, 0F, 0F);
        Horn_4 = new ModelRenderer(this, 265, 131);
        Horn_4.addBox(-1F, -28F, 6.5F, 2, 4, 2);
        Horn_4.setRotationPoint(0F, -6F, 0F);
        Horn_4.setTextureSize(512, 256);
        Horn_4.mirror = true;
        this.convertToChild(Head, Horn_4);
        setRotation(Horn_4, 0.7853982F, 0F, 0F);
        Snout = new ModelRenderer(this, 273, 160);
        Snout.addBox(-4F, -13F, -15F, 8, 8, 12);
        Snout.setRotationPoint(0F, -6F, 0F);
        Snout.setTextureSize(512, 256);
        Snout.mirror = true;
        this.convertToChild(Head, Snout);
        setRotation(Snout, 0.4363323F, 0F, 0F);
        Undermouth_1 = new ModelRenderer(this, 273, 180);
        Undermouth_1.addBox(-2F, -9F, -8F, 4, 3, 3);
        Undermouth_1.setRotationPoint(0F, -6F, 0F);
        Undermouth_1.setTextureSize(512, 256);
        Undermouth_1.mirror = true;
        this.convertToChild(Head, Undermouth_1);
        setRotation(Undermouth_1, 0.7853982F, 0F, 0F);
        Undermouth_2 = new ModelRenderer(this, 296, 180);
        Undermouth_2.addBox(-2F, -11F, -11.5F, 4, 3, 4);
        Undermouth_2.setRotationPoint(0F, -6F, 0F);
        Undermouth_2.setTextureSize(512, 256);
        Undermouth_2.mirror = true;
        this.convertToChild(Head, Undermouth_2);
        setRotation(Undermouth_2, 0.7853982F, 0F, 0F);
        Neck = new ModelRenderer(this, 203, 168);
        Neck.addBox(-4F, -6F, -5F, 8, 12, 10);
        Neck.setRotationPoint(0F, -6F, 0F);
        Neck.setTextureSize(512, 256);
        Neck.mirror = true;
        setRotation(Neck, 0.7330383F, 0F, 0F);
        Right_Frill_1 = new ModelRenderer(this, 205, 97);
        Right_Frill_1.addBox(-6F, -8F, 8F, 3, 3, 9);
        Right_Frill_1.setRotationPoint(0F, -6F, 0F);
        Right_Frill_1.setTextureSize(512, 256);
        Right_Frill_1.mirror = true;
        this.convertToChild(Head, Right_Frill_1);
        setRotation(Right_Frill_1, 0.6981317F, -0.7853982F, 0F);
        Right_Frill_2 = new ModelRenderer(this, 205, 109);
        Right_Frill_2.addBox(-6F, -8F, 5F, 3, 3, 9);
        Right_Frill_2.setRotationPoint(0F, -6F, 0F);
        Right_Frill_2.setTextureSize(512, 256);
        Right_Frill_2.mirror = true;
        this.convertToChild(Head, Right_Frill_2);
        setRotation(Right_Frill_2, 0.4537856F, -0.7853982F, 0F);
        Right_Frill_3 = new ModelRenderer(this, 205, 121);
        Right_Frill_3.addBox(-6F, -8F, 2F, 3, 3, 9);
        Right_Frill_3.setRotationPoint(0F, -6F, 0F);
        Right_Frill_3.setTextureSize(512, 256);
        Right_Frill_3.mirror = true;
        this.convertToChild(Head, Right_Frill_3);
        setRotation(Right_Frill_3, 0.1396263F, -0.7853982F, 0F);
        Right_Frill_4 = new ModelRenderer(this, 205, 133);
        Right_Frill_4.addBox(-6F, -8F, -1F, 3, 3, 9);
        Right_Frill_4.setRotationPoint(0F, -6F, 0F);
        Right_Frill_4.setTextureSize(512, 256);
        Right_Frill_4.mirror = true;
        this.convertToChild(Head, Right_Frill_4);
        setRotation(Right_Frill_4, -0.2617994F, -0.7853982F, 0F);
        Right_Frill_5 = new ModelRenderer(this, 205, 145);
        Right_Frill_5.addBox(-6F, -7F, -4F, 3, 3, 9);
        Right_Frill_5.setRotationPoint(0F, -6F, 0F);
        Right_Frill_5.setTextureSize(512, 256);
        Right_Frill_5.mirror = true;
        this.convertToChild(Head, Right_Frill_5);
        setRotation(Right_Frill_5, -0.6981317F, -0.7853982F, 0F);
        Right_Frill_6 = new ModelRenderer(this, 207, 157);
        Right_Frill_6.addBox(-6F, -4F, -6F, 3, 3, 8);
        Right_Frill_6.setRotationPoint(0F, -6F, 0F);
        Right_Frill_6.setTextureSize(512, 256);
        Right_Frill_6.mirror = true;
        this.convertToChild(Head, Right_Frill_6);
        setRotation(Right_Frill_6, -1.22173F, -0.7853982F, 0F);
        Right_Sideburn = new ModelRenderer(this, 256, 178);
        Right_Sideburn.addBox(-9F, -1F, -3F, 3, 3, 4);
        Right_Sideburn.setRotationPoint(0F, -6F, 0F);
        Right_Sideburn.setTextureSize(512, 256);
        Right_Sideburn.mirror = true;
        this.convertToChild(Head, Right_Sideburn);
        setRotation(Right_Sideburn, -1.22173F, -0.7853982F, 0F);
        Left_Frill_1 = new ModelRenderer(this, 181, 97);
        Left_Frill_1.addBox(3F, -8F, 8F, 3, 3, 9);
        Left_Frill_1.setRotationPoint(0F, -6F, 0F);
        Left_Frill_1.setTextureSize(512, 256);
        Left_Frill_1.mirror = true;
        this.convertToChild(Head, Left_Frill_1);
        setRotation(Left_Frill_1, 0.6981317F, 0.7853982F, 0F);
        Left_Frill_2 = new ModelRenderer(this, 181, 109);
        Left_Frill_2.addBox(3F, -8F, 5F, 3, 3, 9);
        Left_Frill_2.setRotationPoint(0F, -6F, 0F);
        Left_Frill_2.setTextureSize(512, 256);
        Left_Frill_2.mirror = true;
        this.convertToChild(Head, Left_Frill_2);
        setRotation(Left_Frill_2, 0.4537856F, 0.7853982F, 0F);
        Left_Frill_3 = new ModelRenderer(this, 181, 121);
        Left_Frill_3.addBox(3F, -8F, 2F, 3, 3, 9);
        Left_Frill_3.setRotationPoint(0F, -6F, 0F);
        Left_Frill_3.setTextureSize(512, 256);
        Left_Frill_3.mirror = true;
        this.convertToChild(Head, Left_Frill_3);
        setRotation(Left_Frill_3, 0.1396263F, 0.7853982F, 0F);
        Left_Frill_4 = new ModelRenderer(this, 181, 133);
        Left_Frill_4.addBox(3F, -8F, -1F, 3, 3, 9);
        Left_Frill_4.setRotationPoint(0F, -6F, 0F);
        Left_Frill_4.setTextureSize(512, 256);
        Left_Frill_4.mirror = true;
        this.convertToChild(Head, Left_Frill_4);
        setRotation(Left_Frill_4, -0.2617994F, 0.7853982F, 0F);
        Left_Frill_5 = new ModelRenderer(this, 181, 145);
        Left_Frill_5.addBox(3F, -7F, -4F, 3, 3, 9);
        Left_Frill_5.setRotationPoint(0F, -6F, 0F);
        Left_Frill_5.setTextureSize(512, 256);
        Left_Frill_5.mirror = true;
        this.convertToChild(Head, Left_Frill_5);
        setRotation(Left_Frill_5, -0.6981317F, 0.7853982F, 0F);
        Left_Frill_6 = new ModelRenderer(this, 183, 157);
        Left_Frill_6.addBox(3F, -4F, -6F, 3, 3, 8);
        Left_Frill_6.setRotationPoint(0F, -6F, 0F);
        Left_Frill_6.setTextureSize(512, 256);
        Left_Frill_6.mirror = true;
        this.convertToChild(Head, Left_Frill_6);
        setRotation(Left_Frill_6, -1.22173F, 0.7853982F, 0F);
        Left_Sideburn = new ModelRenderer(this, 240, 178);
        Left_Sideburn.addBox(6F, -1F, -3F, 3, 3, 4);
        Left_Sideburn.setRotationPoint(0F, -6F, 0F);
        Left_Sideburn.setTextureSize(512, 256);
        Left_Sideburn.mirror = true;
        this.convertToChild(Head, Left_Sideburn);
        setRotation(Left_Sideburn, -1.22173F, 0.7853982F, 0F);
        Hair_1 = new ModelRenderer(this, 132, 150);
        Hair_1.addBox(-6.5F, -11F, -2.5F, 13, 9, 11);
        Hair_1.setRotationPoint(0F, -9F, 0F);
        Hair_1.setTextureSize(512, 256);
        Hair_1.mirror = true;
        this.convertToChild(Head, Hair_1);
        setRotation(Hair_1, -0.3839724F, 0F, 0F);
        Hair_2 = new ModelRenderer(this, 147, 142);
        Hair_2.addBox(-6F, -10F, -9F, 12, 4, 4);
        Hair_2.setRotationPoint(0F, -9F, 0F);
        Hair_2.setTextureSize(512, 256);
        Hair_2.mirror = true;
        this.convertToChild(Head, Hair_2);
        setRotation(Hair_2, -1.186824F, 0F, 0F);
        Hair_3 = new ModelRenderer(this, 123, 142);
        Hair_3.addBox(-4F, -13F, -6F, 8, 4, 4);
        Hair_3.setRotationPoint(0F, -9F, 0F);
        Hair_3.setTextureSize(512, 256);
        Hair_3.mirror = true;
        this.convertToChild(Head, Hair_3);
        setRotation(Hair_3, -1.186824F, 0F, 0F);
        Hair_4 = new ModelRenderer(this, 119, 153);
        Hair_4.addBox(-4F, -12F, 2F, 8, 4, 4);
        Hair_4.setRotationPoint(0F, -9F, 0F);
        Hair_4.setTextureSize(512, 256);
        Hair_4.mirror = true;
        this.convertToChild(Head, Hair_4);
        setRotation(Hair_4, -0.9250245F, 0F, 0F);
        Hair_5 = new ModelRenderer(this, 100, 161);
        Hair_5.addBox(-4F, -6F, 8F, 8, 4, 8);
        Hair_5.setRotationPoint(0F, -9F, 0F);
        Hair_5.setTextureSize(512, 256);
        Hair_5.mirror = true;
        this.convertToChild(Head, Hair_5);
        setRotation(Hair_5, -0.3839724F, 0F, 0F);
        Hair_6 = new ModelRenderer(this, 99, 156);
        Hair_6.addBox(-4F, -11F, 8F, 8, 3, 2);
        Hair_6.setRotationPoint(0F, -9F, 0F);
        Hair_6.setTextureSize(512, 256);
        Hair_6.mirror = true;
        this.convertToChild(Head, Hair_6);
        setRotation(Hair_6, -0.715585F, 0F, 0F);
        Hair_7 = new ModelRenderer(this, 78, 158);
        Hair_7.addBox(-4F, -9F, 11F, 8, 4, 5);
        Hair_7.setRotationPoint(0F, -9F, 0F);
        Hair_7.setTextureSize(512, 256);
        Hair_7.mirror = true;
        this.convertToChild(Head, Hair_7);
        setRotation(Hair_7, -0.5410521F, 0F, 0F);
        Front_Right_Leg_1 = new ModelRenderer(this, 114, 205);
        Front_Right_Leg_1.addBox(-7F, -1F, -3F, 7, 10, 7);
        Front_Right_Leg_1.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Leg_1.setTextureSize(512, 256);
        Front_Right_Leg_1.mirror = true;
        setRotation(Front_Right_Leg_1, 0F, 0F, 0F);
        Front_Right_Leg_2 = new ModelRenderer(this, 114, 222);
        Front_Right_Leg_2.addBox(-7F, 2F, 4F, 7, 16, 7);
        Front_Right_Leg_2.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Leg_2.setTextureSize(512, 256);
        Front_Right_Leg_2.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Leg_2);
        setRotation(Front_Right_Leg_2, -0.5235988F, 0F, 0F);
        Front_Right_Foot = new ModelRenderer(this, 114, 245);
        Front_Right_Foot.addBox(-7F, 17F, -6F, 7, 4, 7);
        Front_Right_Foot.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Foot.setTextureSize(512, 256);
        Front_Right_Foot.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Foot);
        setRotation(Front_Right_Foot, 0F, 0F, 0F);
        Front_Right_Claw_1 = new ModelRenderer(this, 142, 250);
        Front_Right_Claw_1.addBox(-7F, 19F, -10F, 1, 2, 4);
        Front_Right_Claw_1.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Claw_1.setTextureSize(512, 256);
        Front_Right_Claw_1.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_1);
        setRotation(Front_Right_Claw_1, 0F, 0F, 0F);
        Front_Right_Claw_2 = new ModelRenderer(this, 142, 244);
        Front_Right_Claw_2.addBox(-4F, 19F, -10F, 1, 2, 4);
        Front_Right_Claw_2.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Claw_2.setTextureSize(512, 256);
        Front_Right_Claw_2.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_2);
        setRotation(Front_Right_Claw_2, 0F, 0F, 0F);
        Front_Right_Claw_3 = new ModelRenderer(this, 142, 238);
        Front_Right_Claw_3.addBox(-1F, 19F, -10F, 1, 2, 4);
        Front_Right_Claw_3.setRotationPoint(-9F, 3F, 4F);
        Front_Right_Claw_3.setTextureSize(512, 256);
        Front_Right_Claw_3.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_3);
        setRotation(Front_Right_Claw_3, 0F, 0F, 0F);
        Front_Left_Leg_1 = new ModelRenderer(this, 76, 205);
        Front_Left_Leg_1.addBox(0F, -1F, -3F, 7, 10, 7);
        Front_Left_Leg_1.setRotationPoint(9F, 3F, 4F);
        Front_Left_Leg_1.setTextureSize(512, 256);
        Front_Left_Leg_1.mirror = true;
        setRotation(Front_Left_Leg_1, 0F, 0F, 0F);
        Front_Left_Leg_2 = new ModelRenderer(this, 76, 222);
        Front_Left_Leg_2.addBox(0F, 2F, 4F, 7, 16, 7);
        Front_Left_Leg_2.setRotationPoint(9F, 3F, 4F);
        Front_Left_Leg_2.setTextureSize(512, 256);
        Front_Left_Leg_2.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Leg_2);
        setRotation(Front_Left_Leg_2, -0.5235988F, 0F, 0F);
        Front_Left_Foot = new ModelRenderer(this, 76, 245);
        Front_Left_Foot.addBox(0F, 17F, -6F, 7, 4, 7);
        Front_Left_Foot.setRotationPoint(9F, 3F, 4F);
        Front_Left_Foot.setTextureSize(512, 256);
        Front_Left_Foot.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Foot);
        setRotation(Front_Left_Foot, 0F, 0F, 0F);
        Front_Left_Claw_1 = new ModelRenderer(this, 104, 238);
        Front_Left_Claw_1.addBox(6F, 19F, -10F, 1, 2, 4);
        Front_Left_Claw_1.setRotationPoint(9F, 3F, 4F);
        Front_Left_Claw_1.setTextureSize(512, 256);
        Front_Left_Claw_1.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_1);
        setRotation(Front_Left_Claw_1, 0F, 0F, 0F);
        Front_Left_Claw_2 = new ModelRenderer(this, 104, 244);
        Front_Left_Claw_2.addBox(3F, 19F, -10F, 1, 2, 4);
        Front_Left_Claw_2.setRotationPoint(9F, 3F, 4F);
        Front_Left_Claw_2.setTextureSize(512, 256);
        Front_Left_Claw_2.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_2);
        setRotation(Front_Left_Claw_2, 0F, 0F, 0F);
        Front_Left_Claw_3 = new ModelRenderer(this, 104, 250);
        Front_Left_Claw_3.addBox(0F, 19F, -10F, 1, 2, 4);
        Front_Left_Claw_3.setRotationPoint(9F, 3F, 4F);
        Front_Left_Claw_3.setTextureSize(512, 256);
        Front_Left_Claw_3.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_3);
        setRotation(Front_Left_Claw_3, 0F, 0F, 0F);
        Back_Right_Leg_1 = new ModelRenderer(this, 38, 209);
        Back_Right_Leg_1.addBox(-7F, -2F, -3F, 7, 8, 7);
        Back_Right_Leg_1.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Leg_1.setTextureSize(512, 256);
        Back_Right_Leg_1.mirror = true;
        setRotation(Back_Right_Leg_1, 0F, 0F, 0F);
        Back_Right_Leg_2 = new ModelRenderer(this, 38, 224);
        Back_Right_Leg_2.addBox(-7F, 1F, 1F, 7, 14, 7);
        Back_Right_Leg_2.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Leg_2.setTextureSize(512, 256);
        Back_Right_Leg_2.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Leg_2);
        setRotation(Back_Right_Leg_2, -0.3490659F, 0F, 0F);
        Back_Right_Foot = new ModelRenderer(this, 38, 245);
        Back_Right_Foot.addBox(-7F, 13F, -4.5F, 7, 4, 7);
        Back_Right_Foot.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Foot.setTextureSize(512, 256);
        Back_Right_Foot.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Foot);
        setRotation(Back_Right_Foot, 0F, 0F, 0F);
        Back_Right_Claw_1 = new ModelRenderer(this, 66, 250);
        Back_Right_Claw_1.addBox(-7F, 15F, -8.5F, 1, 2, 4);
        Back_Right_Claw_1.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Claw_1.setTextureSize(512, 256);
        Back_Right_Claw_1.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_1);
        setRotation(Back_Right_Claw_1, 0F, 0F, 0F);
        Back_Right_Claw_2 = new ModelRenderer(this, 66, 244);
        Back_Right_Claw_2.addBox(-4F, 15F, -8.5F, 1, 2, 4);
        Back_Right_Claw_2.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Claw_2.setTextureSize(512, 256);
        Back_Right_Claw_2.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_2);
        setRotation(Back_Right_Claw_2, 0F, 0F, 0F);
        Back_Right_Claw_3 = new ModelRenderer(this, 66, 238);
        Back_Right_Claw_3.addBox(-1F, 15F, -8.5F, 1, 2, 4);
        Back_Right_Claw_3.setRotationPoint(-8F, 7F, 25F);
        Back_Right_Claw_3.setTextureSize(512, 256);
        Back_Right_Claw_3.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_3);
        setRotation(Back_Right_Claw_3, 0F, 0F, 0F);
        Back_Left_Leg_1 = new ModelRenderer(this, 0, 209);
        Back_Left_Leg_1.addBox(0F, -2F, -3F, 7, 8, 7);
        Back_Left_Leg_1.setRotationPoint(8F, 7F, 25F);
        Back_Left_Leg_1.setTextureSize(512, 256);
        Back_Left_Leg_1.mirror = true;
        setRotation(Back_Left_Leg_1, 0F, 0F, 0F);
        Back_Left_Leg_2 = new ModelRenderer(this, 0, 224);
        Back_Left_Leg_2.addBox(0F, 1F, 1F, 7, 14, 7);
        Back_Left_Leg_2.setRotationPoint(8F, 7F, 25F);
        Back_Left_Leg_2.setTextureSize(512, 256);
        Back_Left_Leg_2.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Leg_2);
        setRotation(Back_Left_Leg_2, -0.3490659F, 0F, 0F);
        Back_Left_Foot = new ModelRenderer(this, 0, 245);
        Back_Left_Foot.addBox(0F, 13F, -4.5F, 7, 4, 7);
        Back_Left_Foot.setRotationPoint(8F, 7F, 25F);
        Back_Left_Foot.setTextureSize(512, 256);
        Back_Left_Foot.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Foot);
        setRotation(Back_Left_Foot, 0F, 0F, 0F);
        Back_Left_Claw_1 = new ModelRenderer(this, 28, 238);
        Back_Left_Claw_1.addBox(6F, 15F, -8.5F, 1, 2, 4);
        Back_Left_Claw_1.setRotationPoint(8F, 7F, 25F);
        Back_Left_Claw_1.setTextureSize(512, 256);
        Back_Left_Claw_1.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_1);
        setRotation(Back_Left_Claw_1, 0F, 0F, 0F);
        Back_Left_Claw_2 = new ModelRenderer(this, 28, 244);
        Back_Left_Claw_2.addBox(3F, 15F, -8.5F, 1, 2, 4);
        Back_Left_Claw_2.setRotationPoint(8F, 7F, 25F);
        Back_Left_Claw_2.setTextureSize(512, 256);
        Back_Left_Claw_2.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_2);
        setRotation(Back_Left_Claw_2, 0F, 0F, 0F);
        Back_Left_Claw_3 = new ModelRenderer(this, 28, 250);
        Back_Left_Claw_3.addBox(0F, 15F, -8.5F, 1, 2, 4);
        Back_Left_Claw_3.setRotationPoint(8F, 7F, 25F);
        Back_Left_Claw_3.setTextureSize(512, 256);
        Back_Left_Claw_3.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_3);
        setRotation(Back_Left_Claw_3, 0F, 0F, 0F);
        Right_Wing_Membrane_2 = new ModelRenderer(this, 365, 216);
        Right_Wing_Membrane_2.addBox(0F, 0F, 0F, 1, 1, 25);
        Right_Wing_Membrane_2.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_Membrane_2.setTextureSize(512, 256);
        Right_Wing_Membrane_2.mirror = true;
        setRotation(Right_Wing_Membrane_2, 0F, -0.5235988F, 0F);
        Right_Wing_Membrane_1 = new ModelRenderer(this, 324, 208);
        Right_Wing_Membrane_1.addBox(0F, 0F, 0F, 1, 1, 32);
        Right_Wing_Membrane_1.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_Membrane_1.setTextureSize(512, 256);
        Right_Wing_Membrane_1.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_Membrane_1);
        setRotation(Right_Wing_Membrane_1, 0.6632251F, -0.5235988F, 0F);
        Right_Wing_Membrane_3 = new ModelRenderer(this, 400, 225);
        Right_Wing_Membrane_3.addBox(0F, 0F, 0F, 1, 1, 17);
        Right_Wing_Membrane_3.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_Membrane_3.setTextureSize(512, 256);
        Right_Wing_Membrane_3.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_Membrane_3);
        setRotation(Right_Wing_Membrane_3, -0.8901179F, -0.5235988F, 0F);
        Right_Wing_1 = new ModelRenderer(this, 324, 211);
        Right_Wing_1.addBox(0.5F, 1F, 0F, 0, 6, 31);
        Right_Wing_1.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_1.setTextureSize(512, 256);
        Right_Wing_1.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_1);
        setRotation(Right_Wing_1, 0.6632251F, -0.5235988F, 0F);
        Right_Wing_2 = new ModelRenderer(this, 386, 226);
        Right_Wing_2.addBox(0.5F, -10F, 2F, 0, 10, 17);
        Right_Wing_2.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_2.setTextureSize(512, 256);
        Right_Wing_2.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_2);
        setRotation(Right_Wing_2, -0.8901179F, -0.5235988F, 0F);
        Right_Wing_3 = new ModelRenderer(this, 420, 229);
        Right_Wing_3.addBox(0.5F, 10F, 2F, 0, 13, 14);
        Right_Wing_3.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_3.setTextureSize(512, 256);
        Right_Wing_3.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_3);
        setRotation(Right_Wing_3, 1.082104F, -0.5235988F, 0F);
        Right_Wing_4 = new ModelRenderer(this, 448, 234);
        Right_Wing_4.addBox(0.5F, -29F, 6F, 0, 12, 10);
        Right_Wing_4.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_4.setTextureSize(512, 256);
        Right_Wing_4.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_4);
        setRotation(Right_Wing_4, -0.8901179F, -0.5235988F, 0F);
        Right_Wing_5 = new ModelRenderer(this, 468, 232);
        Right_Wing_5.addBox(0.5F, -36F, -15F, 0, 10, 14);
        Right_Wing_5.setRotationPoint(-9F, -4F, 7F);
        Right_Wing_5.setTextureSize(512, 256);
        Right_Wing_5.mirror = true;
        this.convertToChild(Right_Wing_Membrane_2, Right_Wing_5);
        setRotation(Right_Wing_5, -1.448623F, -0.5235988F, 0F);
        Left_Wing_Membrane_2 = new ModelRenderer(this, 193, 216);
        Left_Wing_Membrane_2.addBox(-1F, 0F, 0F, 1, 1, 25);
        Left_Wing_Membrane_2.setRotationPoint(9F, -4F, 7F);
        Left_Wing_Membrane_2.setTextureSize(512, 256);
        Left_Wing_Membrane_2.mirror = true;
        setRotation(Left_Wing_Membrane_2, 0F, 0.5235988F, 0F);
        Left_Wing_2 = new ModelRenderer(this, 214, 226);
        Left_Wing_2.addBox(-0.5F, -10F, 2F, 0, 10, 17);
        Left_Wing_2.setRotationPoint(9F, -4F, 7F);
        Left_Wing_2.setTextureSize(512, 256);
        Left_Wing_2.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_2);
        setRotation(Left_Wing_2, -0.8901179F, 0.5235988F, 0F);
        Left_Wing_Membrane_1 = new ModelRenderer(this, 152, 208);
        Left_Wing_Membrane_1.addBox(-1F, 0F, 0F, 1, 1, 32);
        Left_Wing_Membrane_1.setRotationPoint(9F, -4F, 7F);
        Left_Wing_Membrane_1.setTextureSize(512, 256);
        Left_Wing_Membrane_1.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_Membrane_1);
        setRotation(Left_Wing_Membrane_1, 0.6632251F, 0.5235988F, 0F);
        Left_Wing_Membrane_3 = new ModelRenderer(this, 228, 225);
        Left_Wing_Membrane_3.addBox(-1F, 0F, 0F, 1, 1, 17);
        Left_Wing_Membrane_3.setRotationPoint(9F, -4F, 7F);
        Left_Wing_Membrane_3.setTextureSize(512, 256);
        Left_Wing_Membrane_3.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_Membrane_3);
        setRotation(Left_Wing_Membrane_3, -0.8901179F, 0.5235988F, 0F);
        Left_Wing_1 = new ModelRenderer(this, 152, 211);
        Left_Wing_1.addBox(-0.5F, 1F, 0F, 0, 6, 31);
        Left_Wing_1.setRotationPoint(9F, -4F, 7F);
        Left_Wing_1.setTextureSize(512, 256);
        Left_Wing_1.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_1);
        setRotation(Left_Wing_1, 0.6632251F, 0.5235988F, 0F);
        Left_Wing_3 = new ModelRenderer(this, 248, 229);
        Left_Wing_3.addBox(-0.5F, 10F, 2F, 0, 13, 14);
        Left_Wing_3.setRotationPoint(9F, -4F, 7F);
        Left_Wing_3.setTextureSize(512, 256);
        Left_Wing_3.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_3);
        setRotation(Left_Wing_3, 1.082104F, 0.5235988F, 0F);
        Left_Wing_4 = new ModelRenderer(this, 276, 234);
        Left_Wing_4.addBox(-0.5F, -29F, 6F, 0, 12, 10);
        Left_Wing_4.setRotationPoint(9F, -4F, 7F);
        Left_Wing_4.setTextureSize(512, 256);
        Left_Wing_4.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_4);
        setRotation(Left_Wing_4, -0.8901179F, 0.5235988F, 0F);
        Left_Wing_5 = new ModelRenderer(this, 296, 232);
        Left_Wing_5.addBox(-0.5F, -36F, -15F, 0, 10, 14);
        Left_Wing_5.setRotationPoint(9F, -4F, 7F);
        Left_Wing_5.setTextureSize(512, 256);
        Left_Wing_5.mirror = true;
        this.convertToChild(Left_Wing_Membrane_2, Left_Wing_5);
        setRotation(Left_Wing_5, -1.448623F, 0.5235988F, 0F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Tail_1.render(f5);
        Tail_2.render(f5);
        Tail_3.render(f5);
        Tail_Tip_1.render(f5);
        Tail_Tip_2.render(f5);
        Tail_Tip_3.render(f5);
        Tail_Tip_4.render(f5);
        Rear.render(f5);
        Lower_Torso.render(f5);
        Upper_Torso.render(f5);
        Chest.render(f5);
        Head.render(f5);
        Neck.render(f5);
        Front_Right_Leg_1.render(f5);
        Front_Left_Leg_1.render(f5);
        Back_Right_Leg_1.render(f5);
        Back_Left_Leg_1.render(f5);
        Right_Wing_Membrane_2.render(f5);
        Left_Wing_Membrane_2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);

///////////////////////////////LEGS///////////////////////////////////////
        this.Front_Left_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Front_Right_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        this.Back_Right_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Back_Left_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        //////////////////////////////WINGS////////////////////////////////////////
        if (!entity.onGround) {
            this.Left_Wing_Membrane_2.rotateAngleZ = f2;
            this.Right_Wing_Membrane_2.rotateAngleZ = -f2;
        } else {
            this.Left_Wing_Membrane_2.rotateAngleZ = 0;
            this.Right_Wing_Membrane_2.rotateAngleZ = 0;
        }
    }

}

