package com.hoopawolf.mwaw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelEarthPet3 extends ModelBase {
    //fields
    ModelRenderer Head;
    ModelRenderer Head_Gem;
    ModelRenderer Right_Head_Sides;
    ModelRenderer Left_Head_Sides;
    ModelRenderer Top_Right_Headgear_Piece;
    ModelRenderer Top_Left_Headgear_Piece;
    ModelRenderer Head_Rock_1;
    ModelRenderer Head_Rock_2;
    ModelRenderer Head_Rock_3;
    ModelRenderer Right_Backhead_Rock_1;
    ModelRenderer Right_Backhead_Rock_2;
    ModelRenderer Left_Backhead_Rock_1;
    ModelRenderer Left_Backhead_Rock_2;
    ModelRenderer Hair_Tie;
    ModelRenderer Hair_1;
    ModelRenderer Hair_2;
    ModelRenderer Hair_3;
    ModelRenderer Hair_4;
    ModelRenderer Hair_5;
    ModelRenderer Hair_6;
    ModelRenderer Scarf_1;
    ModelRenderer Scarf_2;
    ModelRenderer Scarf_3;
    ModelRenderer Scarf_4;
    ModelRenderer Scarf_Button;
    ModelRenderer Upper_Torso;
    ModelRenderer Lower_Torso;
    ModelRenderer Left_Shoulder;
    ModelRenderer Left_Arm_1;
    ModelRenderer Left_Arm_2;
    ModelRenderer Left_Arm_Rock_1;
    ModelRenderer Left_Arm_Rock_2;
    ModelRenderer Left_Arm_Rock_3;
    ModelRenderer Left_Arm_Rock_4;
    ModelRenderer Left_Arm_Rock_5;
    ModelRenderer Right_Arm_1;
    ModelRenderer Right_Arm_2;
    ModelRenderer Right_Palm;
    ModelRenderer Right_Thumb;
    ModelRenderer Right_Index_Finger;
    ModelRenderer Right_Middle_Finger;
    ModelRenderer Right_Ring_Finger;
    ModelRenderer Right_Pinky;
    ModelRenderer Dirt;

    public ModelEarthPet3() {
        textureWidth = 512;
        textureHeight = 256;

        Head = new ModelRenderer(this, 221, 121);
        Head.addBox(-7F, -14F, -7F, 14, 13, 14);
        Head.setRotationPoint(0F, -8F, 0F);
        Head.setTextureSize(512, 256);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Head_Gem = new ModelRenderer(this, 244, 103);
        Head_Gem.addBox(-10F, -10F, -8F, 4, 4, 1);
        Head_Gem.setRotationPoint(0F, -8F, 0F);
        Head_Gem.setTextureSize(512, 256);
        Head_Gem.mirror = true;
        this.convertToChild(Head, Head_Gem);
        setRotation(Head_Gem, 0F, 0F, 0.7853982F);
        Right_Head_Sides = new ModelRenderer(this, 208, 103);
        Right_Head_Sides.addBox(-14F, -4F, -5F, 8, 8, 10);
        Right_Head_Sides.setRotationPoint(0F, -8F, 0F);
        Right_Head_Sides.setTextureSize(512, 256);
        Right_Head_Sides.mirror = true;
        this.convertToChild(Head, Right_Head_Sides);
        setRotation(Right_Head_Sides, 0F, 0F, 0.7853982F);
        Left_Head_Sides = new ModelRenderer(this, 254, 103);
        Left_Head_Sides.addBox(6F, -4F, -5F, 8, 8, 10);
        Left_Head_Sides.setRotationPoint(0F, -8F, 0F);
        Left_Head_Sides.setTextureSize(512, 256);
        Left_Head_Sides.mirror = true;
        this.convertToChild(Head, Left_Head_Sides);
        setRotation(Left_Head_Sides, 0F, 0F, -0.7853982F);
        Top_Right_Headgear_Piece = new ModelRenderer(this, 193, 83);
        Top_Right_Headgear_Piece.addBox(-13F, -15F, -3F, 10, 2, 18);
        Top_Right_Headgear_Piece.setRotationPoint(0F, -8F, 0F);
        Top_Right_Headgear_Piece.setTextureSize(512, 256);
        Top_Right_Headgear_Piece.mirror = true;
        this.convertToChild(Head, Top_Right_Headgear_Piece);
        setRotation(Top_Right_Headgear_Piece, 0.1745329F, -0.7853982F, 0F);
        Top_Left_Headgear_Piece = new ModelRenderer(this, 249, 83);
        Top_Left_Headgear_Piece.addBox(3F, -15F, -3F, 10, 2, 18);
        Top_Left_Headgear_Piece.setRotationPoint(0F, -8F, 0F);
        Top_Left_Headgear_Piece.setTextureSize(512, 256);
        Top_Left_Headgear_Piece.mirror = true;
        this.convertToChild(Head, Top_Left_Headgear_Piece);
        setRotation(Top_Left_Headgear_Piece, 0.1745329F, 0.7853982F, 0F);
        Head_Rock_1 = new ModelRenderer(this, 233, 86);
        Head_Rock_1.addBox(-8F, -17F, 0F, 8, 7, 8);
        Head_Rock_1.setRotationPoint(0F, -8F, 0F);
        Head_Rock_1.setTextureSize(512, 256);
        Head_Rock_1.mirror = true;
        this.convertToChild(Head, Head_Rock_1);
        setRotation(Head_Rock_1, 0.2617994F, 0.7853982F, 0.2617994F);
        Head_Rock_2 = new ModelRenderer(this, 237, 75);
        Head_Rock_2.addBox(-7F, -22F, 1F, 6, 5, 6);
        Head_Rock_2.setRotationPoint(0F, -8F, 0F);
        Head_Rock_2.setTextureSize(512, 256);
        Head_Rock_2.mirror = true;
        this.convertToChild(Head, Head_Rock_2);
        setRotation(Head_Rock_2, 0.2617994F, 0.7853982F, 0.2617994F);
        Head_Rock_3 = new ModelRenderer(this, 241, 69);
        Head_Rock_3.addBox(-6F, -24F, 2F, 4, 2, 4);
        Head_Rock_3.setRotationPoint(0F, -8F, 0F);
        Head_Rock_3.setTextureSize(512, 256);
        Head_Rock_3.mirror = true;
        this.convertToChild(Head, Head_Rock_3);
        setRotation(Head_Rock_3, 0.2617994F, 0.7853982F, 0.2617994F);
        Right_Backhead_Rock_1 = new ModelRenderer(this, 201, 73);
        Right_Backhead_Rock_1.addBox(-3F, -9F, 11F, 5, 5, 5);
        Right_Backhead_Rock_1.setRotationPoint(0F, -8F, 0F);
        Right_Backhead_Rock_1.setTextureSize(512, 256);
        Right_Backhead_Rock_1.mirror = true;
        this.convertToChild(Head, Right_Backhead_Rock_1);
        setRotation(Right_Backhead_Rock_1, 0.5235988F, -0.7853982F, 0F);
        Right_Backhead_Rock_2 = new ModelRenderer(this, 221, 75);
        Right_Backhead_Rock_2.addBox(-3F, -9F, 11F, 4, 4, 4);
        Right_Backhead_Rock_2.setRotationPoint(0F, -8F, 0F);
        Right_Backhead_Rock_2.setTextureSize(512, 256);
        Right_Backhead_Rock_2.mirror = true;
        this.convertToChild(Head, Right_Backhead_Rock_2);
        setRotation(Right_Backhead_Rock_2, 0.5235988F, -0.1745329F, 0F);
        Left_Backhead_Rock_1 = new ModelRenderer(this, 277, 73);
        Left_Backhead_Rock_1.addBox(-2F, -9F, 11F, 5, 5, 5);
        Left_Backhead_Rock_1.setRotationPoint(0F, -8F, 0F);
        Left_Backhead_Rock_1.setTextureSize(512, 256);
        Left_Backhead_Rock_1.mirror = true;
        this.convertToChild(Head, Left_Backhead_Rock_1);
        setRotation(Left_Backhead_Rock_1, 0.5235988F, 0.7853982F, 0F);
        Left_Backhead_Rock_2 = new ModelRenderer(this, 261, 75);
        Left_Backhead_Rock_2.addBox(-1F, -9F, 11F, 4, 4, 4);
        Left_Backhead_Rock_2.setRotationPoint(0F, -8F, 0F);
        Left_Backhead_Rock_2.setTextureSize(512, 256);
        Left_Backhead_Rock_2.mirror = true;
        this.convertToChild(Head, Left_Backhead_Rock_2);
        setRotation(Left_Backhead_Rock_2, 0.5235988F, 0.1745329F, 0F);
        Hair_Tie = new ModelRenderer(this, 239, 59);
        Hair_Tie.addBox(-1F, -7F, 12F, 2, 2, 8);
        Hair_Tie.setRotationPoint(0F, -8F, 0F);
        Hair_Tie.setTextureSize(512, 256);
        Hair_Tie.mirror = true;
        this.convertToChild(Head, Hair_Tie);
        setRotation(Hair_Tie, 0.6981317F, 0F, 0F);
        Hair_1 = new ModelRenderer(this, 235, 44);
        Hair_1.addBox(-6F, -11F, 16F, 12, 13, 2);
        Hair_1.setRotationPoint(0F, -8F, 0F);
        Hair_1.setTextureSize(512, 256);
        Hair_1.mirror = true;
        this.convertToChild(Head, Hair_1);
        setRotation(Hair_1, 0.5235988F, 0F, 0F);
        Hair_2 = new ModelRenderer(this, 265, 21);
        Hair_2.addBox(-5F, -16F, 19F, 10, 3, 10);
        Hair_2.setRotationPoint(0F, -8F, 0F);
        Hair_2.setTextureSize(512, 256);
        Hair_2.mirror = true;
        this.convertToChild(Head, Hair_2);
        setRotation(Hair_2, 0.4363323F, 0F, 0F);
        Hair_3 = new ModelRenderer(this, 209, 13);
        Hair_3.addBox(-7F, -12F, 18F, 14, 17, 14);
        Hair_3.setRotationPoint(0F, -8F, 0F);
        Hair_3.setTextureSize(512, 256);
        Hair_3.mirror = true;
        this.convertToChild(Head, Hair_3);
        setRotation(Hair_3, 0.5235988F, 0F, 0F);
        Hair_4 = new ModelRenderer(this, 161, 13);
        Hair_4.addBox(-6F, -4F, 19.5F, 12, 17, 12);
        Hair_4.setRotationPoint(0F, -8F, 0F);
        Hair_4.setTextureSize(512, 256);
        Hair_4.mirror = true;
        this.convertToChild(Head, Hair_4);
        setRotation(Hair_4, 0.2617994F, 0F, 0F);
        Hair_5 = new ModelRenderer(this, 121, 13);
        Hair_5.addBox(-5F, 4F, 23F, 10, 15, 10);
        Hair_5.setRotationPoint(0F, -8F, 0F);
        Hair_5.setTextureSize(512, 256);
        Hair_5.mirror = true;
        this.convertToChild(Head, Hair_5);
        setRotation(Hair_5, 0F, 0F, 0F);
        Hair_6 = new ModelRenderer(this, 89, 13);
        Hair_6.addBox(-4F, 19F, 24F, 8, 5, 8);
        Hair_6.setRotationPoint(0F, -8F, 0F);
        Hair_6.setTextureSize(512, 256);
        Hair_6.mirror = true;
        this.convertToChild(Head, Hair_6);
        setRotation(Hair_6, 0F, 0F, 0F);
        Scarf_1 = new ModelRenderer(this, 113, 124);
        Scarf_1.addBox(-23F, -1F, -9F, 34, 4, 20);
        Scarf_1.setRotationPoint(0F, -8F, 0F);
        Scarf_1.setTextureSize(512, 256);
        Scarf_1.mirror = true;
        setRotation(Scarf_1, 0F, 0F, -0.2617994F);
        Scarf_2 = new ModelRenderer(this, 113, 102);
        Scarf_2.addBox(-23F, -3F, -9F, 24, 2, 20);
        Scarf_2.setRotationPoint(0F, -8F, 0F);
        Scarf_2.setTextureSize(512, 256);
        Scarf_2.mirror = true;
        setRotation(Scarf_2, 0F, 0F, -0.2617994F);
        Scarf_3 = new ModelRenderer(this, 113, 80);
        Scarf_3.addBox(-23F, -5F, -9F, 18, 2, 20);
        Scarf_3.setRotationPoint(0F, -8F, 0F);
        Scarf_3.setTextureSize(512, 256);
        Scarf_3.mirror = true;
        setRotation(Scarf_3, 0F, 0F, -0.2617994F);
        Scarf_4 = new ModelRenderer(this, 286, 160);
        Scarf_4.addBox(9F, -6F, -9F, 17, 3, 20);
        Scarf_4.setRotationPoint(0F, -8F, 0F);
        Scarf_4.setTextureSize(512, 256);
        Scarf_4.mirror = true;
        setRotation(Scarf_4, 0F, 0F, 0.3316126F);
        Scarf_Button = new ModelRenderer(this, 278, 142);
        Scarf_Button.addBox(8F, -3F, -10F, 4, 4, 2);
        Scarf_Button.setRotationPoint(0F, -8F, 0F);
        Scarf_Button.setTextureSize(512, 256);
        Scarf_Button.mirror = true;
        setRotation(Scarf_Button, 0F, 0F, 0F);
        Upper_Torso = new ModelRenderer(this, 210, 148);
        Upper_Torso.addBox(-11F, 0F, -8F, 22, 26, 16);
        Upper_Torso.setRotationPoint(0F, -8F, 0F);
        Upper_Torso.setTextureSize(512, 256);
        Upper_Torso.mirror = true;
        setRotation(Upper_Torso, 0F, 0F, 0F);
        Lower_Torso = new ModelRenderer(this, 220, 190);
        Lower_Torso.addBox(-8F, 18F, -6F, 16, 4, 12);
        Lower_Torso.setRotationPoint(0F, 0F, 0F);
        Lower_Torso.setTextureSize(512, 256);
        Lower_Torso.mirror = true;
        setRotation(Lower_Torso, 0F, 0F, 0F);
        Left_Shoulder = new ModelRenderer(this, 278, 136);
        Left_Shoulder.addBox(0F, -6F, -6F, 12, 12, 12);
        Left_Shoulder.setRotationPoint(11F, -7F, 0F);
        Left_Shoulder.setTextureSize(512, 256);
        Left_Shoulder.mirror = true;
        setRotation(Left_Shoulder, 0F, 0F, 0F);
        Left_Arm_1 = new ModelRenderer(this, 296, 183);
        Left_Arm_1.addBox(-1F, 2F, -5F, 10, 6, 10);
        Left_Arm_1.setRotationPoint(11F, -4F, 0F);
        Left_Arm_1.setTextureSize(512, 256);
        Left_Arm_1.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_1);
        setRotation(Left_Arm_1, 0F, 0F, -0.3665191F);
        Left_Arm_2 = new ModelRenderer(this, 290, 199);
        Left_Arm_2.addBox(-3F, 8F, -6F, 14, 20, 12);
        Left_Arm_2.setRotationPoint(11F, -4F, 0F);
        Left_Arm_2.setTextureSize(512, 256);
        Left_Arm_2.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_2);
        setRotation(Left_Arm_2, 0F, 0F, -0.3665191F);
        Left_Arm_Rock_1 = new ModelRenderer(this, 274, 222);
        Left_Arm_Rock_1.addBox(3F, 18F, -15F, 5, 7, 3);
        Left_Arm_Rock_1.setRotationPoint(11F, -4F, 0F);
        Left_Arm_Rock_1.setTextureSize(512, 256);
        Left_Arm_Rock_1.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_Rock_1);
        setRotation(Left_Arm_Rock_1, 0F, -0.5759587F, -0.3665191F);
        Left_Arm_Rock_2 = new ModelRenderer(this, 282, 231);
        Left_Arm_Rock_2.addBox(10F, 13F, 10F, 7, 9, 8);
        Left_Arm_Rock_2.setRotationPoint(11F, -4F, 0F);
        Left_Arm_Rock_2.setTextureSize(512, 256);
        Left_Arm_Rock_2.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_Rock_2);
        setRotation(Left_Arm_Rock_2, -0.3665191F, 0.3490659F, 0F);
        Left_Arm_Rock_3 = new ModelRenderer(this, 342, 217);
        Left_Arm_Rock_3.addBox(3F, 9F, -8F, 8, 8, 6);
        Left_Arm_Rock_3.setRotationPoint(11F, -4F, 0F);
        Left_Arm_Rock_3.setTextureSize(512, 256);
        Left_Arm_Rock_3.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_Rock_3);
        setRotation(Left_Arm_Rock_3, 0.5061455F, -0.418879F, 0F);
        Left_Arm_Rock_4 = new ModelRenderer(this, 262, 207);
        Left_Arm_Rock_4.addBox(5F, 9F, 4F, 6, 7, 8);
        Left_Arm_Rock_4.setRotationPoint(11F, -4F, 0F);
        Left_Arm_Rock_4.setTextureSize(512, 256);
        Left_Arm_Rock_4.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_Rock_4);
        setRotation(Left_Arm_Rock_4, -0.6283185F, 0.4886922F, 0F);
        Left_Arm_Rock_5 = new ModelRenderer(this, 312, 231);
        Left_Arm_Rock_5.addBox(5F, 9F, -6F, 10, 9, 9);
        Left_Arm_Rock_5.setRotationPoint(11F, -4F, 0F);
        Left_Arm_Rock_5.setTextureSize(512, 256);
        Left_Arm_Rock_5.mirror = true;
        this.convertToChild(Left_Shoulder, Left_Arm_Rock_5);
        setRotation(Left_Arm_Rock_5, 0.8726646F, 0.5585054F, 0F);
        Right_Arm_1 = new ModelRenderer(this, 170, 148);
        Right_Arm_1.addBox(-9F, 2F, -5F, 10, 15, 10);
        Right_Arm_1.setRotationPoint(-11F, -4F, 0F);
        Right_Arm_1.setTextureSize(512, 256);
        Right_Arm_1.mirror = true;
        setRotation(Right_Arm_1, 0F, 0F, 0.1919862F);
        Right_Arm_2 = new ModelRenderer(this, 170, 173);
        Right_Arm_2.addBox(-9F, -1F, 8F, 10, 24, 10);
        Right_Arm_2.setRotationPoint(-11F, -4F, 0F);
        Right_Arm_2.setTextureSize(512, 256);
        Right_Arm_2.mirror = true;
        setRotation(Right_Arm_2, -1.308997F, 0F, 0.1919862F);
        Right_Palm = new ModelRenderer(this, 169, 207);
        Right_Palm.addBox(-10F, 23F, 10F, 12, 11, 9);
        Right_Palm.setRotationPoint(-11F, -4F, 0F);
        Right_Palm.setTextureSize(512, 256);
        Right_Palm.mirror = true;
        setRotation(Right_Palm, -1.308997F, 0F, 0.1919862F);
        Right_Thumb = new ModelRenderer(this, 143, 207);
        Right_Thumb.addBox(-14F, 24F, 4F, 4, 4, 9);
        Right_Thumb.setRotationPoint(-11F, -4F, 0F);
        Right_Thumb.setTextureSize(512, 256);
        Right_Thumb.mirror = true;
        setRotation(Right_Thumb, -1.308997F, 0F, 0.1919862F);
        Right_Index_Finger = new ModelRenderer(this, 154, 227);
        Right_Index_Finger.addBox(-11F, 34F, 4F, 3, 3, 9);
        Right_Index_Finger.setRotationPoint(-11F, -4F, 0F);
        Right_Index_Finger.setTextureSize(512, 256);
        Right_Index_Finger.mirror = true;
        setRotation(Right_Index_Finger, -1.308997F, 0F, 0.1919862F);
        Right_Middle_Finger = new ModelRenderer(this, 178, 227);
        Right_Middle_Finger.addBox(-6F, 34F, 4F, 3, 3, 9);
        Right_Middle_Finger.setRotationPoint(-11F, -4F, 0F);
        Right_Middle_Finger.setTextureSize(512, 256);
        Right_Middle_Finger.mirror = true;
        setRotation(Right_Middle_Finger, -1.308997F, 0F, 0.1919862F);
        Right_Ring_Finger = new ModelRenderer(this, 202, 227);
        Right_Ring_Finger.addBox(-1F, 34F, 4F, 3, 3, 9);
        Right_Ring_Finger.setRotationPoint(-11F, -4F, 0F);
        Right_Ring_Finger.setTextureSize(512, 256);
        Right_Ring_Finger.mirror = true;
        setRotation(Right_Ring_Finger, -1.308997F, 0F, 0.1919862F);
        Right_Pinky = new ModelRenderer(this, 211, 213);
        Right_Pinky.addBox(2F, 28F, 4F, 3, 3, 9);
        Right_Pinky.setRotationPoint(-11F, -4F, 0F);
        Right_Pinky.setTextureSize(512, 256);
        Right_Pinky.mirror = true;
        setRotation(Right_Pinky, -1.308997F, 0F, 0.1919862F);
        Dirt = new ModelRenderer(this, 175, 239);
        Dirt.addBox(-9F, 24F, 5F, 10, 9, 5);
        Dirt.setRotationPoint(-11F, -4F, 0F);
        Dirt.setTextureSize(512, 256);
        Dirt.mirror = true;
        setRotation(Dirt, -1.308997F, 0F, 0.1919862F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Head.render(f5);
        Scarf_1.render(f5);
        Scarf_2.render(f5);
        Scarf_3.render(f5);
        Scarf_4.render(f5);
        Scarf_Button.render(f5);
        Upper_Torso.render(f5);
        Lower_Torso.render(f5);
        Left_Shoulder.render(f5);
        Right_Arm_1.render(f5);
        Right_Arm_2.render(f5);
        Right_Palm.render(f5);
        Right_Thumb.render(f5);
        Right_Index_Finger.render(f5);
        Right_Middle_Finger.render(f5);
        Right_Ring_Finger.render(f5);
        Right_Pinky.render(f5);
        Dirt.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);

        ///////////////////////////////////ARMS//////////////////////////////////////////
        Left_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;

    }

}