package com.hoopawolf.mwaw.models;

import com.hoopawolf.mwaw.entity.EntityDarkPet;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDarkPet extends ModelBase {
    //fields
    ModelRenderer Right_Tip_1_1;
    ModelRenderer Right_Tip_1_2;
    ModelRenderer Right_Tip_1_3;
    ModelRenderer Right_Tip_2_1;
    ModelRenderer Right_Tip_2_2;
    ModelRenderer Right_Tip_2_3;
    ModelRenderer Left_Tip_1_1;
    ModelRenderer Left_Tip_1_2;
    ModelRenderer Left_Tip_1_3;
    ModelRenderer Left_Tip_2_1;
    ModelRenderer Left_Tip_2_2;
    ModelRenderer Left_Tip_2_3;
    ModelRenderer Forehead;
    ModelRenderer Headgear_Gem;
    ModelRenderer Head_Gear_Right_Piece;
    ModelRenderer Head_Gear_Left_Piece;
    ModelRenderer Body;
    ModelRenderer Back_1;
    ModelRenderer Back_2;
    ModelRenderer Right_Sides_1;
    ModelRenderer Right_Sides_2;
    ModelRenderer Right_Sides_3;
    ModelRenderer Left_Sides_1;
    ModelRenderer Left_Sides_2;
    ModelRenderer Left_Sides_3;
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer Tail_3;
    ModelRenderer Right_Armor_1;
    ModelRenderer Right_Armor_2;
    ModelRenderer Right_Armor_3;
    ModelRenderer Right_Armor_4;
    ModelRenderer Right_Armor_Spike_1;
    ModelRenderer Right_Armor_Spike_2;
    ModelRenderer Left_Armor_1;
    ModelRenderer Left_Armor_2;
    ModelRenderer Left_Armor_3;
    ModelRenderer Left_Armor_4;
    ModelRenderer Left_Armor_Spike_1;
    ModelRenderer Left_Armor_Spike_2;

    public ModelDarkPet() {
        textureWidth = 64;
        textureHeight = 32;

        Body = new ModelRenderer(this, 26, 7);
        Body.addBox(-2.5F, -2.5F, -1F, 5, 5, 2);
        Body.setRotationPoint(0F, 15F, 0F);
        Body.setTextureSize(64, 32);
        Body.mirror = true;
        setRotation(Body, 0.0523599F, 0F, 0F);
        Right_Tip_1_1 = new ModelRenderer(this, 12, 5);
        Right_Tip_1_1.addBox(-1.5F, -4F, -2F, 1, 2, 1);
        Right_Tip_1_1.setRotationPoint(0F, 15F, 0F);
        Right_Tip_1_1.setTextureSize(64, 32);
        Right_Tip_1_1.mirror = true;
        this.convertToChild(Body, Right_Tip_1_1);
        setRotation(Right_Tip_1_1, -0.9599311F, -0.6981317F, 0F);
        Right_Tip_1_2 = new ModelRenderer(this, 7, 3);
        Right_Tip_1_2.addBox(-1.5F, -5F, -2.6F, 1, 1, 2);
        Right_Tip_1_2.setRotationPoint(0F, 15F, 0F);
        Right_Tip_1_2.setTextureSize(64, 32);
        Right_Tip_1_2.mirror = true;
        this.convertToChild(Body, Right_Tip_1_2);
        setRotation(Right_Tip_1_2, -0.9599311F, -0.6981317F, 0F);
        Right_Tip_1_3 = new ModelRenderer(this, 5, 3);
        Right_Tip_1_3.addBox(-1.5F, -6F, -3F, 1, 1, 1);
        Right_Tip_1_3.setRotationPoint(0F, 15F, 0F);
        Right_Tip_1_3.setTextureSize(64, 32);
        Right_Tip_1_3.mirror = true;
        this.convertToChild(Body, Right_Tip_1_3);
        setRotation(Right_Tip_1_3, -0.9599311F, -0.6981317F, 0F);
        Right_Tip_2_1 = new ModelRenderer(this, 20, 3);
        Right_Tip_2_1.addBox(-1F, -4F, -1.5F, 1, 2, 1);
        Right_Tip_2_1.setRotationPoint(0F, 15F, 0F);
        Right_Tip_2_1.setTextureSize(64, 32);
        Right_Tip_2_1.mirror = true;
        this.convertToChild(Body, Right_Tip_2_1);
        setRotation(Right_Tip_2_1, -0.6108652F, -0.2268928F, 0F);
        Right_Tip_2_2 = new ModelRenderer(this, 15, 1);
        Right_Tip_2_2.addBox(-1F, -5F, -2.1F, 1, 1, 2);
        Right_Tip_2_2.setRotationPoint(0F, 15F, 0F);
        Right_Tip_2_2.setTextureSize(64, 32);
        Right_Tip_2_2.mirror = true;
        this.convertToChild(Body, Right_Tip_2_2);
        setRotation(Right_Tip_2_2, -0.6108652F, -0.2268928F, 0F);
        Right_Tip_2_3 = new ModelRenderer(this, 13, 1);
        Right_Tip_2_3.addBox(-1F, -6F, -3F, 1, 1, 1);
        Right_Tip_2_3.setRotationPoint(0F, 15F, 0F);
        Right_Tip_2_3.setTextureSize(64, 32);
        Right_Tip_2_3.mirror = true;
        this.convertToChild(Body, Right_Tip_2_3);
        setRotation(Right_Tip_2_3, -0.6108652F, -0.2268928F, 0F);
        Left_Tip_1_1 = new ModelRenderer(this, 50, 5);
        Left_Tip_1_1.addBox(0.5F, -4F, -2F, 1, 2, 1);
        Left_Tip_1_1.setRotationPoint(0F, 15F, 0F);
        Left_Tip_1_1.setTextureSize(64, 32);
        Left_Tip_1_1.mirror = true;
        this.convertToChild(Body, Left_Tip_1_1);
        setRotation(Left_Tip_1_1, -0.9599311F, 0.6981317F, 0F);
        Left_Tip_1_2 = new ModelRenderer(this, 53, 3);
        Left_Tip_1_2.addBox(0.5F, -5F, -2.6F, 1, 1, 2);
        Left_Tip_1_2.setRotationPoint(0F, 15F, 0F);
        Left_Tip_1_2.setTextureSize(64, 32);
        Left_Tip_1_2.mirror = true;
        this.convertToChild(Body, Left_Tip_1_2);
        setRotation(Left_Tip_1_2, -0.9599311F, 0.6981317F, 0F);
        Left_Tip_1_3 = new ModelRenderer(this, 57, 3);
        Left_Tip_1_3.addBox(0.5F, -6F, -3F, 1, 1, 1);
        Left_Tip_1_3.setRotationPoint(0F, 15F, 0F);
        Left_Tip_1_3.setTextureSize(64, 32);
        Left_Tip_1_3.mirror = true;
        this.convertToChild(Body, Left_Tip_1_3);
        setRotation(Left_Tip_1_3, -0.9599311F, 0.6981317F, 0F);
        Left_Tip_2_1 = new ModelRenderer(this, 42, 3);
        Left_Tip_2_1.addBox(0F, -4F, -1.5F, 1, 2, 1);
        Left_Tip_2_1.setRotationPoint(0F, 15F, 0F);
        Left_Tip_2_1.setTextureSize(64, 32);
        Left_Tip_2_1.mirror = true;
        this.convertToChild(Body, Left_Tip_2_1);
        setRotation(Left_Tip_2_1, -0.6108652F, 0.2268928F, 0F);
        Left_Tip_2_2 = new ModelRenderer(this, 45, 1);
        Left_Tip_2_2.addBox(0F, -5F, -2.1F, 1, 1, 2);
        Left_Tip_2_2.setRotationPoint(0F, 15F, 0F);
        Left_Tip_2_2.setTextureSize(64, 32);
        Left_Tip_2_2.mirror = true;
        this.convertToChild(Body, Left_Tip_2_2);
        setRotation(Left_Tip_2_2, -0.6108652F, 0.2268928F, 0F);
        Left_Tip_2_3 = new ModelRenderer(this, 49, 1);
        Left_Tip_2_3.addBox(0F, -6F, -3F, 1, 1, 1);
        Left_Tip_2_3.setRotationPoint(0F, 15F, 0F);
        Left_Tip_2_3.setTextureSize(64, 32);
        Left_Tip_2_3.mirror = true;
        this.convertToChild(Body, Left_Tip_2_3);
        setRotation(Left_Tip_2_3, -0.6108652F, 0.2268928F, 0F);
        Forehead = new ModelRenderer(this, 27, 0);
        Forehead.addBox(-2F, -3F, -1F, 4, 1, 2);
        Forehead.setRotationPoint(0F, 15F, 0F);
        Forehead.setTextureSize(64, 32);
        Forehead.mirror = true;
        this.convertToChild(Body, Forehead);
        setRotation(Forehead, 0F, 0F, 0F);
        Headgear_Gem = new ModelRenderer(this, 31, 5);
        Headgear_Gem.addBox(-2F, -2F, -2F, 1, 1, 1);
        Headgear_Gem.setRotationPoint(0F, 15F, 0F);
        Headgear_Gem.setTextureSize(64, 32);
        Headgear_Gem.mirror = true;
        this.convertToChild(Body, Headgear_Gem);
        setRotation(Headgear_Gem, 0F, 0F, 0.7853982F);
        Head_Gear_Right_Piece = new ModelRenderer(this, 24, 2);
        Head_Gear_Right_Piece.addBox(0F, -4F, -2F, 1, 4, 1);
        Head_Gear_Right_Piece.setRotationPoint(0F, 15F, 0F);
        Head_Gear_Right_Piece.setTextureSize(64, 32);
        Head_Gear_Right_Piece.mirror = true;
        this.convertToChild(Body, Head_Gear_Right_Piece);
        setRotation(Head_Gear_Right_Piece, 0F, 0F, -0.7853982F);
        Head_Gear_Left_Piece = new ModelRenderer(this, 38, 2);
        Head_Gear_Left_Piece.addBox(-1F, -4F, -2F, 1, 4, 1);
        Head_Gear_Left_Piece.setRotationPoint(0F, 15F, 0F);
        Head_Gear_Left_Piece.setTextureSize(64, 32);
        Head_Gear_Left_Piece.mirror = true;
        this.convertToChild(Body, Head_Gear_Left_Piece);
        setRotation(Head_Gear_Left_Piece, 0F, 0F, 0.7853982F);
        Back_1 = new ModelRenderer(this, 27, 14);
        Back_1.addBox(-2F, -1.5F, -0.5F, 4, 4, 2);
        Back_1.setRotationPoint(0F, 15F, 1F);
        Back_1.setTextureSize(64, 32);
        Back_1.mirror = true;
        this.convertToChild(Body, Back_1);
        setRotation(Back_1, 0F, 0F, 0F);
        Back_2 = new ModelRenderer(this, 29, 20);
        Back_2.addBox(-1.5F, -0.5F, 1.2F, 3, 3, 1);
        Back_2.setRotationPoint(0F, 15F, 1F);
        Back_2.setTextureSize(64, 32);
        Back_2.mirror = true;
        this.convertToChild(Body, Back_2);
        setRotation(Back_2, -0.1745329F, 0F, 0F);
        Right_Sides_1 = new ModelRenderer(this, 20, 6);
        Right_Sides_1.addBox(-2.5F, -1.5F, 1F, 1, 2, 2);
        Right_Sides_1.setRotationPoint(0F, 15F, 0F);
        Right_Sides_1.setTextureSize(64, 32);
        Right_Sides_1.mirror = true;
        this.convertToChild(Body, Right_Sides_1);
        setRotation(Right_Sides_1, 0.0174533F, -0.7853982F, 0F);
        Right_Sides_2 = new ModelRenderer(this, 16, 5);
        Right_Sides_2.addBox(-2.5F, -2F, 2F, 1, 1, 2);
        Right_Sides_2.setRotationPoint(0F, 15F, 0F);
        Right_Sides_2.setTextureSize(64, 32);
        Right_Sides_2.mirror = true;
        this.convertToChild(Body, Right_Sides_2);
        setRotation(Right_Sides_2, 0.0174533F, -0.7853982F, 0F);
        Right_Sides_3 = new ModelRenderer(this, 20, 10);
        Right_Sides_3.addBox(-3F, -0.1F, -0.9F, 1, 2, 2);
        Right_Sides_3.setRotationPoint(0F, 15F, 0F);
        Right_Sides_3.setTextureSize(64, 32);
        Right_Sides_3.mirror = true;
        this.convertToChild(Body, Right_Sides_3);
        setRotation(Right_Sides_3, 0.0523599F, 0F, -0.2094395F);
        Left_Sides_1 = new ModelRenderer(this, 40, 6);
        Left_Sides_1.addBox(1.5F, -1.5F, 1F, 1, 2, 2);
        Left_Sides_1.setRotationPoint(0F, 15F, 0F);
        Left_Sides_1.setTextureSize(64, 32);
        Left_Sides_1.mirror = true;
        this.convertToChild(Body, Left_Sides_1);
        setRotation(Left_Sides_1, 0.0174533F, 0.7853982F, 0F);
        Left_Sides_2 = new ModelRenderer(this, 44, 5);
        Left_Sides_2.addBox(1.5F, -2F, 2F, 1, 1, 2);
        Left_Sides_2.setRotationPoint(0F, 15F, 0F);
        Left_Sides_2.setTextureSize(64, 32);
        Left_Sides_2.mirror = true;
        this.convertToChild(Body, Left_Sides_2);
        setRotation(Left_Sides_2, 0.0174533F, 0.7853982F, 0F);
        Left_Sides_3 = new ModelRenderer(this, 40, 10);
        Left_Sides_3.addBox(2F, -0.1F, -0.9F, 1, 2, 2);
        Left_Sides_3.setRotationPoint(0F, 15F, 0F);
        Left_Sides_3.setTextureSize(64, 32);
        Left_Sides_3.mirror = true;
        this.convertToChild(Body, Left_Sides_3);
        setRotation(Left_Sides_3, 0.0523599F, 0F, 0.2094395F);
        Tail_1 = new ModelRenderer(this, 32, 24);
        Tail_1.addBox(0F, 2F, 0.5F, 0, 2, 1);
        Tail_1.setRotationPoint(0F, 15F, 1F);
        Tail_1.setTextureSize(64, 32);
        Tail_1.mirror = true;
        setRotation(Tail_1, 0.1570796F, 0F, 0F);
        Tail_2 = new ModelRenderer(this, 32, 26);
        Tail_2.addBox(0F, -0.5F, 4F, 0, 4, 1);
        Tail_2.setRotationPoint(0F, 15F, 1F);
        Tail_2.setTextureSize(64, 32);
        Tail_2.mirror = true;
        setRotation(Tail_2, -0.8726646F, 0F, 0F);
        Tail_3 = new ModelRenderer(this, 32, 30);
        Tail_3.addBox(0F, 3F, 3.5F, 0, 1, 1);
        Tail_3.setRotationPoint(0F, 15F, 1F);
        Tail_3.setTextureSize(64, 32);
        Tail_3.mirror = true;
        setRotation(Tail_3, -0.8726646F, 0F, 0F);
        Right_Armor_1 = new ModelRenderer(this, 0, 25);
        Right_Armor_1.addBox(-6F, -2F, -2F, 1, 4, 3);
        Right_Armor_1.setRotationPoint(0F, 15F, 0F);
        Right_Armor_1.setTextureSize(64, 32);
        Right_Armor_1.mirror = true;
        setRotation(Right_Armor_1, 0F, -0.3490659F, 0F);
        Right_Armor_2 = new ModelRenderer(this, 0, 20);
        Right_Armor_2.addBox(-5.5F, -2F, 0.5F, 1, 4, 1);
        Right_Armor_2.setRotationPoint(0F, 15F, 0F);
        Right_Armor_2.setTextureSize(64, 32);
        Right_Armor_2.mirror = true;
        setRotation(Right_Armor_2, 0F, -0.3490659F, 0F);
        Right_Armor_3 = new ModelRenderer(this, 4, 20);
        Right_Armor_3.addBox(-5.5F, -2F, -2.5F, 1, 4, 1);
        Right_Armor_3.setRotationPoint(0F, 15F, 0F);
        Right_Armor_3.setTextureSize(64, 32);
        Right_Armor_3.mirror = true;
        setRotation(Right_Armor_3, 0F, -0.3490659F, 0F);
        Right_Armor_4 = new ModelRenderer(this, 6, 15);
        Right_Armor_4.addBox(-6.5F, -2.5F, -1.5F, 1, 3, 2);
        Right_Armor_4.setRotationPoint(0F, 15F, 0F);
        Right_Armor_4.setTextureSize(64, 32);
        Right_Armor_4.mirror = true;
        setRotation(Right_Armor_4, 0F, -0.3490659F, 0F);
        Right_Armor_Spike_1 = new ModelRenderer(this, 0, 15);
        Right_Armor_Spike_1.addBox(-8F, -2.4F, -1F, 2, 1, 1);
        Right_Armor_Spike_1.setRotationPoint(0F, 15F, 0F);
        Right_Armor_Spike_1.setTextureSize(64, 32);
        Right_Armor_Spike_1.mirror = true;
        setRotation(Right_Armor_Spike_1, 0F, -0.3490659F, 0F);
        Right_Armor_Spike_2 = new ModelRenderer(this, 0, 18);
        Right_Armor_Spike_2.addBox(-8F, -0.6F, -1F, 2, 1, 1);
        Right_Armor_Spike_2.setRotationPoint(0F, 15F, 0F);
        Right_Armor_Spike_2.setTextureSize(64, 32);
        Right_Armor_Spike_2.mirror = true;
        setRotation(Right_Armor_Spike_2, 0F, -0.3490659F, 0F);
        Left_Armor_1 = new ModelRenderer(this, 56, 25);
        Left_Armor_1.addBox(5F, -2F, -2F, 1, 4, 3);
        Left_Armor_1.setRotationPoint(0F, 15F, 0F);
        Left_Armor_1.setTextureSize(64, 32);
        Left_Armor_1.mirror = true;
        setRotation(Left_Armor_1, 0F, 0.3490659F, 0F);
        Left_Armor_2 = new ModelRenderer(this, 60, 20);
        Left_Armor_2.addBox(4.5F, -2F, 0.5F, 1, 4, 1);
        Left_Armor_2.setRotationPoint(0F, 15F, 0F);
        Left_Armor_2.setTextureSize(64, 32);
        Left_Armor_2.mirror = true;
        setRotation(Left_Armor_2, 0F, 0.3490659F, 0F);
        Left_Armor_3 = new ModelRenderer(this, 56, 20);
        Left_Armor_3.addBox(4.5F, -2F, -2.5F, 1, 4, 1);
        Left_Armor_3.setRotationPoint(0F, 15F, 0F);
        Left_Armor_3.setTextureSize(64, 32);
        Left_Armor_3.mirror = true;
        setRotation(Left_Armor_3, 0F, 0.3490659F, 0F);
        Left_Armor_4 = new ModelRenderer(this, 52, 15);
        Left_Armor_4.addBox(5.5F, -2.5F, -1.5F, 1, 3, 2);
        Left_Armor_4.setRotationPoint(0F, 15F, 0F);
        Left_Armor_4.setTextureSize(64, 32);
        Left_Armor_4.mirror = true;
        setRotation(Left_Armor_4, 0F, 0.3490659F, 0F);
        Left_Armor_Spike_1 = new ModelRenderer(this, 58, 15);
        Left_Armor_Spike_1.addBox(6F, -2.4F, -1F, 2, 1, 1);
        Left_Armor_Spike_1.setRotationPoint(0F, 15F, 0F);
        Left_Armor_Spike_1.setTextureSize(64, 32);
        Left_Armor_Spike_1.mirror = true;
        setRotation(Left_Armor_Spike_1, 0F, 0.3490659F, 0F);
        Left_Armor_Spike_2 = new ModelRenderer(this, 58, 18);
        Left_Armor_Spike_2.addBox(6F, -0.6F, -1F, 2, 1, 1);
        Left_Armor_Spike_2.setRotationPoint(0F, 15F, 0F);
        Left_Armor_Spike_2.setTextureSize(64, 32);
        Left_Armor_Spike_2.mirror = true;
        setRotation(Left_Armor_Spike_2, 0F, 0.3490659F, 0F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        EntityDarkPet darkPet = (EntityDarkPet) entity;

        Body.rotationPointY = darkPet.getFloatingRotation();
        Tail_1.rotationPointY = darkPet.getFloatingRotation();
        Tail_2.rotationPointY = darkPet.getFloatingRotation();
        Tail_3.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_1.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_2.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_3.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_4.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_Spike_1.rotationPointY = darkPet.getFloatingRotation();
        Right_Armor_Spike_2.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_1.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_2.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_3.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_4.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_Spike_1.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_Spike_2.rotationPointY = darkPet.getFloatingRotation();
        Left_Armor_1.rotationPointY = darkPet.getFloatingRotation();

        Body.render(f5);
        Tail_1.render(f5);
        Tail_2.render(f5);
        Tail_3.render(f5);
        Right_Armor_1.render(f5);
        Right_Armor_2.render(f5);
        Right_Armor_3.render(f5);
        Right_Armor_4.render(f5);
        Right_Armor_Spike_1.render(f5);
        Right_Armor_Spike_2.render(f5);
        Left_Armor_1.render(f5);
        Left_Armor_2.render(f5);
        Left_Armor_3.render(f5);
        Left_Armor_4.render(f5);
        Left_Armor_Spike_1.render(f5);
        Left_Armor_Spike_2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Body.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Body.rotateAngleY = f3 / (180F / (float) Math.PI);
    }

}
