package com.hoopawolf.mwaw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelFirePet2 extends ModelBase {
    //fields
    ModelRenderer Front_Torso;
    ModelRenderer Back_Torso;
    ModelRenderer Fire_Mane_1;
    ModelRenderer Fire_Mane_2;
    ModelRenderer Fire_Mane_3;
    ModelRenderer Fire_Mane_4;
    ModelRenderer Neck;
    ModelRenderer Head;
    ModelRenderer Snout;
    ModelRenderer Mouth;
    ModelRenderer Right_Horn_1;
    ModelRenderer Right_Horn_2;
    ModelRenderer Right_Horn_3;
    ModelRenderer Left_Horn_1;
    ModelRenderer Left_Horn_2;
    ModelRenderer Left_Horn_3;
    ModelRenderer Fire_Hair_1;
    ModelRenderer Fire_Hair_2;
    ModelRenderer Front_Right_Shoulder;
    ModelRenderer Front_Right_Leg;
    ModelRenderer Front_Right_Foot;
    ModelRenderer Front_Left_Shoulder;
    ModelRenderer Front_Left_Leg;
    ModelRenderer Front_Left_Foot;
    ModelRenderer Back_Left_Shoulder;
    ModelRenderer Back_Left_Leg;
    ModelRenderer Back_Left_Foot;
    ModelRenderer Back_Right_Shoulder;
    ModelRenderer Back_Right_Leg;
    ModelRenderer Back_Right_Foot;
    ModelRenderer Fire_Tail_1;
    ModelRenderer Fire_Tail_2;
    ModelRenderer Fire_Tail_3;
    ModelRenderer Fire_Tail_4;
    ModelRenderer Fire_Tail_5;
    ModelRenderer Fire_Tail_6;

    public ModelFirePet2() {
        textureWidth = 128;
        textureHeight = 64;

        Front_Torso = new ModelRenderer(this, 70, 21);
        Front_Torso.addBox(-4.5F, 0F, 0F, 9, 9, 10);
        Front_Torso.setRotationPoint(0F, 9F, 0F);
        Front_Torso.setTextureSize(128, 64);
        Front_Torso.mirror = true;
        setRotation(Front_Torso, -0.0523599F, 0F, 0F);
        Back_Torso = new ModelRenderer(this, 38, 24);
        Back_Torso.addBox(-4F, 1F, 9F, 8, 8, 8);
        Back_Torso.setRotationPoint(0F, 9F, 0F);
        Back_Torso.setTextureSize(128, 64);
        Back_Torso.mirror = true;
        setRotation(Back_Torso, 0F, 0F, 0F);
        Fire_Mane_2 = new ModelRenderer(this, 38, 12);
        Fire_Mane_2.addBox(-3F, -13F, -2F, 6, 9, 3);
        Fire_Mane_2.setRotationPoint(0F, 9F, 0F);
        Fire_Mane_2.setTextureSize(128, 64);
        Fire_Mane_2.mirror = true;
        setRotation(Fire_Mane_2, -1.710423F, 0F, 0F);
        Fire_Mane_3 = new ModelRenderer(this, 38, 5);
        Fire_Mane_3.addBox(-1F, -7F, 7F, 2, 3, 2);
        Fire_Mane_3.setRotationPoint(0F, 9F, 0F);
        Fire_Mane_3.setTextureSize(128, 64);
        Fire_Mane_3.mirror = true;
        setRotation(Fire_Mane_3, -0.4363323F, 0F, 0F);
        Fire_Mane_4 = new ModelRenderer(this, 25, 7);
        Fire_Mane_4.addBox(-2.5F, -16F, -7F, 5, 5, 3);
        Fire_Mane_4.setRotationPoint(0F, 9F, 0F);
        Fire_Mane_4.setTextureSize(128, 64);
        Fire_Mane_4.mirror = true;
        setRotation(Fire_Mane_4, -2.059489F, 0F, 0F);
        Neck = new ModelRenderer(this, 72, 13);
        Neck.addBox(-2F, -2.3F, 0F, 4, 4, 4);
        Neck.setRotationPoint(0F, 9F, 0F);
        Neck.setTextureSize(128, 64);
        Neck.mirror = true;
        setRotation(Neck, 0.2617994F, 0F, 0F);
        Head = new ModelRenderer(this, 84, 5);
        Head.addBox(-4F, -8F, -2F, 8, 6, 6);
        Head.setRotationPoint(0F, 9F, 0F);
        Head.setTextureSize(128, 64);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Fire_Mane_1 = new ModelRenderer(this, 56, 15);
        Fire_Mane_1.addBox(-2.5F, -5F, 4F, 5, 6, 3);
        Fire_Mane_1.setRotationPoint(0F, 9F, 0F);
        Fire_Mane_1.setTextureSize(128, 64);
        Fire_Mane_1.mirror = true;
        this.convertToChild(Head, Fire_Mane_1);
        setRotation(Fire_Mane_1, 0.2617994F, 0F, 0F);
        Snout = new ModelRenderer(this, 108, 17);
        Snout.addBox(-1.1F, -7.5F, -3.9F, 5, 4, 5);
        Snout.setRotationPoint(0F, 9F, 0F);
        Snout.setTextureSize(128, 64);
        Snout.mirror = true;
        this.convertToChild(Head, Snout);
        setRotation(Snout, 0F, 0.7853982F, 0F);
        Mouth = new ModelRenderer(this, 108, 26);
        Mouth.addBox(-1.2F, -3.5F, -3.8F, 5, 1, 5);
        Mouth.setRotationPoint(0F, 9F, 0F);
        Mouth.setTextureSize(128, 64);
        Mouth.mirror = true;
        this.convertToChild(Head, Mouth);
        setRotation(Mouth, 0F, 0.7853982F, 0F);
        Right_Horn_1 = new ModelRenderer(this, 120, 0);
        Right_Horn_1.addBox(-3.5F, -13F, 0.5F, 1, 6, 1);
        Right_Horn_1.setRotationPoint(0F, 9F, 0F);
        Right_Horn_1.setTextureSize(128, 64);
        Right_Horn_1.mirror = true;
        this.convertToChild(Head, Right_Horn_1);
        setRotation(Right_Horn_1, -0.2617994F, 0F, 0F);
        Right_Horn_2 = new ModelRenderer(this, 106, 0);
        Right_Horn_2.addBox(-2.5F, -5F, 4F, 2, 2, 4);
        Right_Horn_2.setRotationPoint(0F, 9F, 0F);
        Right_Horn_2.setTextureSize(128, 64);
        Right_Horn_2.mirror = true;
        this.convertToChild(Head, Right_Horn_2);
        setRotation(Right_Horn_2, 0.2617994F, -0.5235988F, 0F);
        Right_Horn_3 = new ModelRenderer(this, 114, 0);
        Right_Horn_3.addBox(-2F, -4.5F, 8F, 1, 1, 2);
        Right_Horn_3.setRotationPoint(0F, 9F, 0F);
        Right_Horn_3.setTextureSize(128, 64);
        Right_Horn_3.mirror = true;
        this.convertToChild(Head, Right_Horn_3);
        setRotation(Right_Horn_3, 0.2617994F, -0.5235988F, 0F);
        Left_Horn_1 = new ModelRenderer(this, 72, 0);
        Left_Horn_1.addBox(2.5F, -13F, 0.5F, 1, 6, 1);
        Left_Horn_1.setRotationPoint(0F, 9F, 0F);
        Left_Horn_1.setTextureSize(128, 64);
        Left_Horn_1.mirror = true;
        this.convertToChild(Head, Left_Horn_1);
        setRotation(Left_Horn_1, -0.2617994F, 0F, 0F);
        Left_Horn_2 = new ModelRenderer(this, 78, 0);
        Left_Horn_2.addBox(0.5F, -5F, 4F, 2, 2, 4);
        Left_Horn_2.setRotationPoint(0F, 9F, 0F);
        Left_Horn_2.setTextureSize(128, 64);
        Left_Horn_2.mirror = true;
        this.convertToChild(Head, Left_Horn_2);
        setRotation(Left_Horn_2, 0.2617994F, 0.5235988F, 0F);
        Left_Horn_3 = new ModelRenderer(this, 76, 0);
        Left_Horn_3.addBox(1F, -4.5F, 8F, 1, 1, 2);
        Left_Horn_3.setRotationPoint(0F, 9F, 0F);
        Left_Horn_3.setTextureSize(128, 64);
        Left_Horn_3.mirror = true;
        this.convertToChild(Head, Left_Horn_3);
        setRotation(Left_Horn_3, 0.2617994F, 0.5235988F, 0F);
        Fire_Hair_1 = new ModelRenderer(this, 61, 6);
        Fire_Hair_1.addBox(-2F, -10F, -7.5F, 4, 6, 3);
        Fire_Hair_1.setRotationPoint(0F, 9F, 0F);
        Fire_Hair_1.setTextureSize(128, 64);
        Fire_Hair_1.mirror = true;
        this.convertToChild(Head, Fire_Hair_1);
        setRotation(Fire_Hair_1, -1.396263F, 0F, 0F);
        Fire_Hair_2 = new ModelRenderer(this, 52, 1);
        Fire_Hair_2.addBox(-1.5F, -15F, -8F, 3, 5, 3);
        Fire_Hair_2.setRotationPoint(0F, 9F, 0F);
        Fire_Hair_2.setTextureSize(128, 64);
        Fire_Hair_2.mirror = true;
        this.convertToChild(Head, Fire_Hair_2);
        setRotation(Fire_Hair_2, -1.22173F, 0F, 0F);
        Front_Right_Shoulder = new ModelRenderer(this, 82, 41);
        Front_Right_Shoulder.addBox(-3F, -1.5F, -1.5F, 3, 3, 3);
        Front_Right_Shoulder.setRotationPoint(-4.5F, 14F, 3F);
        Front_Right_Shoulder.setTextureSize(128, 64);
        Front_Right_Shoulder.mirror = true;
        setRotation(Front_Right_Shoulder, 0F, 0F, 0F);
        Front_Right_Leg = new ModelRenderer(this, 82, 47);
        Front_Right_Leg.addBox(-3F, 0.5F, 1F, 3, 8, 3);
        Front_Right_Leg.setRotationPoint(-4.5F, 14F, 3F);
        Front_Right_Leg.setTextureSize(128, 64);
        Front_Right_Leg.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Leg);
        setRotation(Front_Right_Leg, -0.2617994F, 0F, 0F);
        Front_Right_Foot = new ModelRenderer(this, 81, 58);
        Front_Right_Foot.addBox(-3F, 8F, -2.3F, 3, 2, 4);
        Front_Right_Foot.setRotationPoint(-4.5F, 14F, 3F);
        Front_Right_Foot.setTextureSize(128, 64);
        Front_Right_Foot.mirror = true;
        this.convertToChild(Front_Right_Shoulder, Front_Right_Foot);
        setRotation(Front_Right_Foot, 0F, 0F, 0F);
        Front_Left_Shoulder = new ModelRenderer(this, 68, 41);
        Front_Left_Shoulder.addBox(0F, -1.5F, -1.533333F, 3, 3, 3);
        Front_Left_Shoulder.setRotationPoint(4.5F, 14F, 3F);
        Front_Left_Shoulder.setTextureSize(128, 64);
        Front_Left_Shoulder.mirror = true;
        setRotation(Front_Left_Shoulder, 0F, 0F, 0F);
        Front_Left_Leg = new ModelRenderer(this, 68, 47);
        Front_Left_Leg.addBox(0F, 0.5F, 1F, 3, 8, 3);
        Front_Left_Leg.setRotationPoint(4.5F, 14F, 3F);
        Front_Left_Leg.setTextureSize(128, 64);
        Front_Left_Leg.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Leg);
        setRotation(Front_Left_Leg, -0.2617994F, 0F, 0F);
        Front_Left_Foot = new ModelRenderer(this, 67, 58);
        Front_Left_Foot.addBox(0F, 8F, -2.3F, 3, 2, 4);
        Front_Left_Foot.setRotationPoint(4.5F, 14F, 3F);
        Front_Left_Foot.setTextureSize(128, 64);
        Front_Left_Foot.mirror = true;
        this.convertToChild(Front_Left_Shoulder, Front_Left_Foot);
        setRotation(Front_Left_Foot, 0F, 0F, 0F);
        Back_Left_Shoulder = new ModelRenderer(this, 40, 43);
        Back_Left_Shoulder.addBox(0F, -1.5F, -2F, 3, 3, 3);
        Back_Left_Shoulder.setRotationPoint(4F, 17F, 15F);
        Back_Left_Shoulder.setTextureSize(128, 64);
        Back_Left_Shoulder.mirror = true;
        setRotation(Back_Left_Shoulder, 0F, 0F, 0F);
        Back_Left_Leg = new ModelRenderer(this, 40, 49);
        Back_Left_Leg.addBox(0F, 0F, -1F, 3, 6, 3);
        Back_Left_Leg.setRotationPoint(4F, 17F, 15F);
        Back_Left_Leg.setTextureSize(128, 64);
        Back_Left_Leg.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Leg);
        setRotation(Back_Left_Leg, -0.2617994F, 0F, 0F);
        Back_Left_Foot = new ModelRenderer(this, 39, 58);
        Back_Left_Foot.addBox(0F, 5F, -3.5F, 3, 2, 4);
        Back_Left_Foot.setRotationPoint(4F, 17F, 15F);
        Back_Left_Foot.setTextureSize(128, 64);
        Back_Left_Foot.mirror = true;
        this.convertToChild(Back_Left_Shoulder, Back_Left_Foot);
        setRotation(Back_Left_Foot, 0F, 0F, 0F);
        Back_Right_Shoulder = new ModelRenderer(this, 54, 43);
        Back_Right_Shoulder.addBox(-3F, -1.5F, -2F, 3, 3, 3);
        Back_Right_Shoulder.setRotationPoint(-4F, 17F, 15F);
        Back_Right_Shoulder.setTextureSize(128, 64);
        Back_Right_Shoulder.mirror = true;
        setRotation(Back_Right_Shoulder, 0F, 0F, 0F);
        Back_Right_Leg = new ModelRenderer(this, 54, 49);
        Back_Right_Leg.addBox(-3F, 0F, -1F, 3, 6, 3);
        Back_Right_Leg.setRotationPoint(-4F, 17F, 15F);
        Back_Right_Leg.setTextureSize(128, 64);
        Back_Right_Leg.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Leg);
        setRotation(Back_Right_Leg, -0.2617994F, 0F, 0F);
        Back_Right_Foot = new ModelRenderer(this, 53, 58);
        Back_Right_Foot.addBox(-3F, 5F, -3.5F, 3, 2, 4);
        Back_Right_Foot.setRotationPoint(-4F, 17F, 15F);
        Back_Right_Foot.setTextureSize(128, 64);
        Back_Right_Foot.mirror = true;
        this.convertToChild(Back_Right_Shoulder, Back_Right_Foot);
        setRotation(Back_Right_Foot, 0F, 0F, 0F);
        Fire_Tail_1 = new ModelRenderer(this, 14, 27);
        Fire_Tail_1.addBox(-3F, -5F, 0F, 6, 9, 6);
        Fire_Tail_1.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_1.setTextureSize(128, 64);
        Fire_Tail_1.mirror = true;
        setRotation(Fire_Tail_1, 0F, 0F, 0F);
        Fire_Tail_2 = new ModelRenderer(this, 13, 42);
        Fire_Tail_2.addBox(-4F, -4F, 0.5F, 8, 7, 5);
        Fire_Tail_2.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_2.setTextureSize(128, 64);
        Fire_Tail_2.mirror = true;
        setRotation(Fire_Tail_2, 0F, 0F, 0F);
        Fire_Tail_3 = new ModelRenderer(this, 20, 22);
        Fire_Tail_3.addBox(-1.5F, -7F, 0F, 3, 2, 3);
        Fire_Tail_3.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_3.setTextureSize(128, 64);
        Fire_Tail_3.mirror = true;
        setRotation(Fire_Tail_3, -0.2617994F, 0F, 0F);
        Fire_Tail_4 = new ModelRenderer(this, 15, 20);
        Fire_Tail_4.addBox(-1F, -8F, 5F, 2, 3, 2);
        Fire_Tail_4.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_4.setTextureSize(128, 64);
        Fire_Tail_4.mirror = true;
        setRotation(Fire_Tail_4, 0.1745329F, 0F, 0F);
        Fire_Tail_5 = new ModelRenderer(this, 6, 25);
        Fire_Tail_5.addBox(-2.5F, -4F, 5F, 5, 6, 2);
        Fire_Tail_5.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_5.setTextureSize(128, 64);
        Fire_Tail_5.mirror = true;
        setRotation(Fire_Tail_5, -0.1745329F, 0F, 0F);
        Fire_Tail_6 = new ModelRenderer(this, 0, 24);
        Fire_Tail_6.addBox(-1.5F, -4F, 7.5F, 3, 2, 1);
        Fire_Tail_6.setRotationPoint(0F, 13F, 17F);
        Fire_Tail_6.setTextureSize(128, 64);
        Fire_Tail_6.mirror = true;
        setRotation(Fire_Tail_6, 0F, 0F, 0F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        GL11.glScalef(1.4F, 1.4F, 1.4F);
        GL11.glTranslatef(0.F, -0.5F, -0.5F);

        Front_Torso.render(f5);
        Back_Torso.render(f5);
        Fire_Mane_2.render(f5);
        Fire_Mane_3.render(f5);
        Fire_Mane_4.render(f5);
        Neck.render(f5);
        Head.render(f5);
        Front_Right_Shoulder.render(f5);
        Front_Left_Shoulder.render(f5);
        Back_Left_Shoulder.render(f5);
        Back_Right_Shoulder.render(f5);
        Fire_Tail_1.render(f5);
        Fire_Tail_2.render(f5);
        Fire_Tail_3.render(f5);
        Fire_Tail_4.render(f5);
        Fire_Tail_5.render(f5);
        Fire_Tail_6.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);

///////////////////////////////LEGS///////////////////////////////////////
        this.Front_Left_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Front_Right_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        this.Back_Right_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Back_Left_Shoulder.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;
    }

}

