package com.hoopawolf.mwaw.models;

import com.hoopawolf.mwaw.entity.EntityDarkPet3;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDarkPet3 extends ModelBase {
    //fields
    ModelRenderer Ring;
    ModelRenderer Right_Eye_1;
    ModelRenderer Right_Eye_2;
    ModelRenderer Right_Eye_3;
    ModelRenderer Left_Eye_1;
    ModelRenderer Left_Eye_2;
    ModelRenderer Left_Eye_3;
    ModelRenderer Right_Face_Helm;
    ModelRenderer Middle_Face_Helm;
    ModelRenderer Left_Face_Helm;
    ModelRenderer Right_Helm_1;
    ModelRenderer Right_Helm_2;
    ModelRenderer Left_Helm_1;
    ModelRenderer Left_Helm_2;
    ModelRenderer Top_Helm;
    ModelRenderer Front_Top_Helm;
    ModelRenderer Left_Horn;
    ModelRenderer Right_Horn;
    ModelRenderer Back_Helm_1;
    ModelRenderer Back_Helm_2;
    ModelRenderer Right_Chestplate_Piece;
    ModelRenderer Front_Chestplate_Piece_1;
    ModelRenderer Left_Chestplate_Piece;
    ModelRenderer Front_Chestplate_Piece_2;
    ModelRenderer Back_Chestplate_Piece_1;
    ModelRenderer Back_Chestplate_Piece_2;
    ModelRenderer Back_Chestplate_Piece_3;
    ModelRenderer Back_Chestplate_Piece_4;
    ModelRenderer Right_Chestplate_Strap;
    ModelRenderer Left_Chestplate_Strap;
    ModelRenderer Right_Shoulder_Pad_1;
    ModelRenderer Right_Shoulder_Pad_2;
    ModelRenderer Right_Shoulder_Pad_3;
    ModelRenderer Right_Shoulder_Strap_1;
    ModelRenderer Right_Shoulder_Strap_2;
    ModelRenderer Right_Shoulder_Spike;
    ModelRenderer Right_Shoulder_Spike_2;
    ModelRenderer Right_Shoulder_Spike_3;
    ModelRenderer Right_Shoulder_Spike_4;
    ModelRenderer Right_Shoulder_Spike_5;
    ModelRenderer Left_Shoulder_Pad_1;
    ModelRenderer Left_Shoulder_Pad_2;
    ModelRenderer Left_Shoulder_Pad_3;
    ModelRenderer Left_Shoulder_Strap_1;
    ModelRenderer Left_Shoulder_Strap_2;
    ModelRenderer Left_Shoulder_Spike_1;
    ModelRenderer Left_Shoulder_Spike_2;
    ModelRenderer Left_Shoulder_Spike_3;
    ModelRenderer Left_Shoulder_Spike_4;
    ModelRenderer Left_Shoulder_Spike_5;
    ModelRenderer Lower_Body_Armor_1;
    ModelRenderer Lower_Body_Armor_2;
    ModelRenderer Lower_Body_Armor_3;
    ModelRenderer Lower_Body_Armor_4;
    ModelRenderer Lower_Body_Armor_5;
    ModelRenderer Lower_Body_Armor_6;
    ModelRenderer Lower_Body_Armor_7;
    ModelRenderer Lower_Body_Armor_8;
    ModelRenderer Right_Bracelet_1;
    ModelRenderer Right_Bracelet_2;
    ModelRenderer Left_Bracelet_1;
    ModelRenderer Left_Bracelet_2;
    ModelRenderer Sword_Hilt;
    ModelRenderer Sword_Guard_1;
    ModelRenderer Sword_Guard_2;
    ModelRenderer Sword_Blade;
    ModelRenderer War_Axe_Handle;
    ModelRenderer War_Axe_Shoulder;
    ModelRenderer War_Axe_Head_1;
    ModelRenderer War_Axe_Head_2;
    ModelRenderer Katana_Pommel;
    ModelRenderer Katana_Hilt;
    ModelRenderer Katana_Guard;
    ModelRenderer Katana_Blade;
    ModelRenderer Trident_Rear;
    ModelRenderer Trident;
    ModelRenderer Ethereal_Head;
    ModelRenderer Ethereal_Torso;
    ModelRenderer Ethereal_Waist_1;
    ModelRenderer Ethereal_Waist_2;
    ModelRenderer Ethereal_Lower_Body_1;
    ModelRenderer Ethereal_Lower_Body_2;
    ModelRenderer Ethereal_Right_Hand_1;
    ModelRenderer Ethereal_Right_Knuckle_1;
    ModelRenderer Ethereal_Right_Hand_2;
    ModelRenderer Ethereal_Right_Knuckle_2;
    ModelRenderer Ethereal_Left_Hand_1;
    ModelRenderer Ethereal_Left_Knuckle_1;
    ModelRenderer Ethereal_Left_Hand_2;
    ModelRenderer Ethereal_Left_Knuckle_2;

    public ModelDarkPet3() {
        textureWidth = 512;
        textureHeight = 256;

        Ethereal_Head = new ModelRenderer(this, 0, -23);
        Ethereal_Head.addBox(-5F, -16F, -5F, 10, 12, 11);
        Ethereal_Head.setRotationPoint(0F, -17F, 0F);
        Ethereal_Head.setTextureSize(512, 256);
        Ethereal_Head.mirror = true;
        setRotation(Ethereal_Head, 0F, 0F, 0F);
        Top_Helm = new ModelRenderer(this, 240, 65);
        Top_Helm.addBox(-7F, -18F, -7F, 14, 2, 13);
        Top_Helm.setRotationPoint(0F, -17F, 0F);
        Top_Helm.setTextureSize(512, 256);
        Top_Helm.mirror = true;
        setRotation(Top_Helm, 0F, 0F, 0F);
        Ring = new ModelRenderer(this, 243, 0);
        Ring.addBox(-12F, -12F, 0F, 24, 24, 0);
        Ring.setRotationPoint(0F, -37F, 15F);
        Ring.setTextureSize(512, 256);
        Ring.mirror = true;
        //convertToChild(Top_Helm, Ring);
        setRotation(Ring, 0F, 0F, 0F);
        Right_Eye_1 = new ModelRenderer(this, 252, 80);
        Right_Eye_1.addBox(-5F, -16F, -5.5F, 1, 3, 1);
        Right_Eye_1.setRotationPoint(0F, -17F, 0F);
        Right_Eye_1.setTextureSize(512, 256);
        Right_Eye_1.mirror = true;
        convertToChild(Top_Helm, Right_Eye_1);
        setRotation(Right_Eye_1, 0F, 0F, 0F);
        Right_Eye_2 = new ModelRenderer(this, 256, 81);
        Right_Eye_2.addBox(-4F, -16F, -5.5F, 2, 2, 1);
        Right_Eye_2.setRotationPoint(0F, -16F, 0F);
        Right_Eye_2.setTextureSize(512, 256);
        Right_Eye_2.mirror = true;
        convertToChild(Top_Helm, Right_Eye_2);
        setRotation(Right_Eye_2, 0F, 0F, 0F);
        Right_Eye_3 = new ModelRenderer(this, 262, 82);
        Right_Eye_3.addBox(-2F, -14F, -5.5F, 1, 1, 1);
        Right_Eye_3.setRotationPoint(0F, -17F, 0F);
        Right_Eye_3.setTextureSize(512, 256);
        Right_Eye_3.mirror = true;
        convertToChild(Top_Helm, Right_Eye_3);
        setRotation(Right_Eye_3, 0F, 0F, 0F);
        Left_Eye_1 = new ModelRenderer(this, 278, 80);
        Left_Eye_1.addBox(4F, -16F, -5.5F, 1, 3, 1);
        Left_Eye_1.setRotationPoint(0F, -17F, 0F);
        Left_Eye_1.setTextureSize(512, 256);
        Left_Eye_1.mirror = true;
        convertToChild(Top_Helm, Left_Eye_1);
        setRotation(Left_Eye_1, 0F, 0F, 0F);
        Left_Eye_2 = new ModelRenderer(this, 272, 81);
        Left_Eye_2.addBox(2F, -15F, -5.5F, 2, 2, 1);
        Left_Eye_2.setRotationPoint(0F, -17F, 0F);
        Left_Eye_2.setTextureSize(512, 256);
        Left_Eye_2.mirror = true;
        convertToChild(Top_Helm, Left_Eye_2);
        setRotation(Left_Eye_2, 0F, 0F, 0F);
        Left_Eye_3 = new ModelRenderer(this, 268, 82);
        Left_Eye_3.addBox(1F, -14F, -5.5F, 1, 1, 1);
        Left_Eye_3.setRotationPoint(0F, -17F, 0F);
        Left_Eye_3.setTextureSize(512, 256);
        Left_Eye_3.mirror = true;
        convertToChild(Top_Helm, Left_Eye_3);
        setRotation(Left_Eye_3, 0F, 0F, 0F);
        Right_Face_Helm = new ModelRenderer(this, 252, 84);
        Right_Face_Helm.addBox(-5F, -13F, -7F, 4, 10, 2);
        Right_Face_Helm.setRotationPoint(0F, -17F, 0F);
        Right_Face_Helm.setTextureSize(512, 256);
        Right_Face_Helm.mirror = true;
        convertToChild(Top_Helm, Right_Face_Helm);
        setRotation(Right_Face_Helm, 0F, 0F, 0F);
        Middle_Face_Helm = new ModelRenderer(this, 264, 87);
        Middle_Face_Helm.addBox(-1F, -11F, -6F, 2, 8, 1);
        Middle_Face_Helm.setRotationPoint(0F, -17F, 0F);
        Middle_Face_Helm.setTextureSize(512, 256);
        Middle_Face_Helm.mirror = true;
        convertToChild(Top_Helm, Middle_Face_Helm);
        setRotation(Middle_Face_Helm, 0F, 0F, 0F);
        Left_Face_Helm = new ModelRenderer(this, 270, 84);
        Left_Face_Helm.addBox(1F, -13F, -7F, 4, 10, 2);
        Left_Face_Helm.setRotationPoint(0F, -17F, 0F);
        Left_Face_Helm.setTextureSize(512, 256);
        Left_Face_Helm.mirror = true;
        convertToChild(Top_Helm, Left_Face_Helm);
        setRotation(Left_Face_Helm, 0F, 0F, 0F);
        Right_Helm_1 = new ModelRenderer(this, 220, 68);
        Right_Helm_1.addBox(-8F, -16F, -7F, 3, 12, 13);
        Right_Helm_1.setRotationPoint(0F, -17F, 0F);
        Right_Helm_1.setTextureSize(512, 256);
        Right_Helm_1.mirror = true;
        convertToChild(Top_Helm, Right_Helm_1);
        setRotation(Right_Helm_1, 0F, 0F, 0F);
        Right_Helm_2 = new ModelRenderer(this, 196, 71);
        Right_Helm_2.addBox(-9F, -15F, -6F, 1, 11, 11);
        Right_Helm_2.setRotationPoint(0F, -17F, 0F);
        Right_Helm_2.setTextureSize(512, 256);
        Right_Helm_2.mirror = true;
        convertToChild(Top_Helm, Right_Helm_2);
        setRotation(Right_Helm_2, 0F, 0F, 0F);
        Left_Helm_1 = new ModelRenderer(this, 282, 68);
        Left_Helm_1.addBox(5F, -16F, -7F, 3, 12, 13);
        Left_Helm_1.setRotationPoint(0F, -17F, 0F);
        Left_Helm_1.setTextureSize(512, 256);
        Left_Helm_1.mirror = true;
        convertToChild(Top_Helm, Left_Helm_1);
        setRotation(Left_Helm_1, 0F, 0F, 0F);
        Left_Helm_2 = new ModelRenderer(this, 314, 71);
        Left_Helm_2.addBox(8F, -15F, -6F, 1, 11, 11);
        Left_Helm_2.setRotationPoint(0F, -17F, 0F);
        Left_Helm_2.setTextureSize(512, 256);
        Left_Helm_2.mirror = true;
        convertToChild(Top_Helm, Left_Helm_2);
        setRotation(Left_Helm_2, 0F, 0F, 0F);
        Front_Top_Helm = new ModelRenderer(this, 260, 58);
        Front_Top_Helm.addBox(-14.5F, -14.5F, -8.5F, 4, 4, 3);
        Front_Top_Helm.setRotationPoint(0F, -17F, 0F);
        Front_Top_Helm.setTextureSize(512, 256);
        Front_Top_Helm.mirror = true;
        convertToChild(Top_Helm, Front_Top_Helm);
        setRotation(Front_Top_Helm, 0F, 0F, 0.7853982F);
        Left_Horn = new ModelRenderer(this, 274, 52);
        Left_Horn.addBox(-10.5F, -21.5F, -8F, 1, 12, 1);
        Left_Horn.setRotationPoint(0F, -17F, 0F);
        Left_Horn.setTextureSize(512, 256);
        Left_Horn.mirror = true;
        convertToChild(Top_Helm, Left_Horn);
        setRotation(Left_Horn, 0F, 0F, 0.7853982F);
        Right_Horn = new ModelRenderer(this, 256, 52);
        Right_Horn.addBox(9.5F, -21.5F, -8F, 1, 12, 1);
        Right_Horn.setRotationPoint(0F, -17F, 0F);
        Right_Horn.setTextureSize(512, 256);
        Right_Horn.mirror = true;
        convertToChild(Top_Helm, Right_Horn);
        setRotation(Right_Horn, 0F, 0F, -0.7853982F);
        Back_Helm_1 = new ModelRenderer(this, 252, 38);
        Back_Helm_1.addBox(-7F, -17F, 6F, 14, 13, 1);
        Back_Helm_1.setRotationPoint(0F, -17F, 0F);
        Back_Helm_1.setTextureSize(512, 256);
        Back_Helm_1.mirror = true;
        convertToChild(Top_Helm, Back_Helm_1);
        setRotation(Back_Helm_1, 0F, 0F, 0F);
        Back_Helm_2 = new ModelRenderer(this, 254, 25);
        Back_Helm_2.addBox(-6F, -16F, 7F, 12, 12, 1);
        Back_Helm_2.setRotationPoint(0F, -17F, 0F);
        Back_Helm_2.setTextureSize(512, 256);
        Back_Helm_2.mirror = true;
        convertToChild(Top_Helm, Back_Helm_2);
        setRotation(Back_Helm_2, 0F, 0F, 0F);
        Front_Chestplate_Piece_1 = new ModelRenderer(this, 240, 96);
        Front_Chestplate_Piece_1.addBox(-12F, 1F, -9F, 24, 22, 3);
        Front_Chestplate_Piece_1.setRotationPoint(0F, -17F, 0F);
        Front_Chestplate_Piece_1.setTextureSize(512, 256);
        Front_Chestplate_Piece_1.mirror = true;
        setRotation(Front_Chestplate_Piece_1, 0F, 0F, 0F);
        Right_Chestplate_Piece = new ModelRenderer(this, 212, 93);
        Right_Chestplate_Piece.addBox(-15F, 0F, -7F, 8, 22, 6);
        Right_Chestplate_Piece.setRotationPoint(0F, -17F, 0F);
        Right_Chestplate_Piece.setTextureSize(512, 256);
        Right_Chestplate_Piece.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Right_Chestplate_Piece);
        setRotation(Right_Chestplate_Piece, 0F, 0F, 0F);
        Left_Chestplate_Piece = new ModelRenderer(this, 294, 93);
        Left_Chestplate_Piece.addBox(7F, 0F, -7F, 8, 22, 6);
        Left_Chestplate_Piece.setRotationPoint(0F, -17F, 0F);
        Left_Chestplate_Piece.setTextureSize(512, 256);
        Left_Chestplate_Piece.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Left_Chestplate_Piece);
        setRotation(Left_Chestplate_Piece, 0F, 0F, 0F);
        Front_Chestplate_Piece_2 = new ModelRenderer(this, 256, 121);
        Front_Chestplate_Piece_2.addBox(-4F, 4F, -12F, 8, 24, 3);
        Front_Chestplate_Piece_2.setRotationPoint(0F, -17F, 0F);
        Front_Chestplate_Piece_2.setTextureSize(512, 256);
        Front_Chestplate_Piece_2.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Front_Chestplate_Piece_2);
        setRotation(Front_Chestplate_Piece_2, 0F, 0F, 0F);
        Back_Chestplate_Piece_1 = new ModelRenderer(this, 322, 93);
        Back_Chestplate_Piece_1.addBox(-10F, 0F, 5F, 20, 18, 4);
        Back_Chestplate_Piece_1.setRotationPoint(0F, -17F, 0F);
        Back_Chestplate_Piece_1.setTextureSize(512, 256);
        Back_Chestplate_Piece_1.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Back_Chestplate_Piece_1);
        setRotation(Back_Chestplate_Piece_1, 0F, 0F, 0F);
        Back_Chestplate_Piece_2 = new ModelRenderer(this, 331, 115);
        Back_Chestplate_Piece_2.addBox(-7F, 1F, 9F, 14, 16, 1);
        Back_Chestplate_Piece_2.setRotationPoint(0F, -17F, 0F);
        Back_Chestplate_Piece_2.setTextureSize(512, 256);
        Back_Chestplate_Piece_2.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Back_Chestplate_Piece_2);
        setRotation(Back_Chestplate_Piece_2, 0F, 0F, 0F);
        Back_Chestplate_Piece_3 = new ModelRenderer(this, 329, 132);
        Back_Chestplate_Piece_3.addBox(-7F, 17F, 5F, 14, 3, 3);
        Back_Chestplate_Piece_3.setRotationPoint(0F, -17F, 0F);
        Back_Chestplate_Piece_3.setTextureSize(512, 256);
        Back_Chestplate_Piece_3.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Back_Chestplate_Piece_3);
        setRotation(Back_Chestplate_Piece_3, 0F, 0F, 0F);
        Back_Chestplate_Piece_4 = new ModelRenderer(this, 332, 138);
        Back_Chestplate_Piece_4.addBox(-6F, 20F, 5F, 12, 2, 2);
        Back_Chestplate_Piece_4.setRotationPoint(0F, -17F, 0F);
        Back_Chestplate_Piece_4.setTextureSize(512, 256);
        Back_Chestplate_Piece_4.mirror = true;
        convertToChild(Front_Chestplate_Piece_1, Back_Chestplate_Piece_4);
        setRotation(Back_Chestplate_Piece_4, 0F, 0F, 0F);
        Right_Chestplate_Strap = new ModelRenderer(this, 196, 59);
        Right_Chestplate_Strap.addBox(-13F, -2F, -3F, 6, 2, 10);
        Right_Chestplate_Strap.setRotationPoint(0F, -17F, 0F);
        Right_Chestplate_Strap.setTextureSize(512, 256);
        Right_Chestplate_Strap.mirror = true;
        setRotation(Right_Chestplate_Strap, 0F, 0F, 0F);
        Left_Chestplate_Strap = new ModelRenderer(this, 306, 59);
        Left_Chestplate_Strap.addBox(7F, -2F, -3F, 6, 2, 10);
        Left_Chestplate_Strap.setRotationPoint(0F, -17F, 0F);
        Left_Chestplate_Strap.setTextureSize(512, 256);
        Left_Chestplate_Strap.mirror = true;
        setRotation(Left_Chestplate_Strap, 0F, 0F, 0F);
        Right_Shoulder_Pad_1 = new ModelRenderer(this, 148, 69);
        Right_Shoulder_Pad_1.addBox(-13F, -5F, -5F, 12, 4, 12);
        Right_Shoulder_Pad_1.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Pad_1.setTextureSize(512, 256);
        Right_Shoulder_Pad_1.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Pad_1);
        setRotation(Right_Shoulder_Pad_1, 0F, 0F, -0.2617994F);
        Right_Shoulder_Pad_2 = new ModelRenderer(this, 124, 72);
        Right_Shoulder_Pad_2.addBox(-13F, -7F, -4F, 2, 3, 10);
        Right_Shoulder_Pad_2.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Pad_2.setTextureSize(512, 256);
        Right_Shoulder_Pad_2.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Pad_2);
        setRotation(Right_Shoulder_Pad_2, 0F, 0F, -0.5235988F);
        Right_Shoulder_Pad_3 = new ModelRenderer(this, 94, 75);
        Right_Shoulder_Pad_3.addBox(-15F, -12F, -3F, 7, 2, 8);
        Right_Shoulder_Pad_3.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Pad_3.setTextureSize(512, 256);
        Right_Shoulder_Pad_3.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Pad_3);
        setRotation(Right_Shoulder_Pad_3, 0F, 0F, -1.047198F);
        Right_Shoulder_Strap_1 = new ModelRenderer(this, 172, 85);
        Right_Shoulder_Strap_1.addBox(-11F, -3F, -7F, 8, 4, 4);
        Right_Shoulder_Strap_1.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Strap_1.setTextureSize(512, 256);
        Right_Shoulder_Strap_1.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Strap_1);
        setRotation(Right_Shoulder_Strap_1, 0F, 0F, -0.2617994F);
        Right_Shoulder_Strap_2 = new ModelRenderer(this, 172, 61);
        Right_Shoulder_Strap_2.addBox(-11F, -3F, 5F, 8, 4, 4);
        Right_Shoulder_Strap_2.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Strap_2.setTextureSize(512, 256);
        Right_Shoulder_Strap_2.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Strap_2);
        setRotation(Right_Shoulder_Strap_2, 0F, 0F, -0.2617994F);
        Right_Shoulder_Spike = new ModelRenderer(this, 132, 54);
        Right_Shoulder_Spike.addBox(-10F, -10F, -4F, 10, 5, 10);
        Right_Shoulder_Spike.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Spike.setTextureSize(512, 256);
        Right_Shoulder_Spike.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Spike);
        setRotation(Right_Shoulder_Spike, 0F, 0F, -0.6108652F);
        Right_Shoulder_Spike_2 = new ModelRenderer(this, 132, 42);
        Right_Shoulder_Spike_2.addBox(-10F, -13F, -3F, 8, 4, 8);
        Right_Shoulder_Spike_2.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Spike_2.setTextureSize(512, 256);
        Right_Shoulder_Spike_2.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Spike_2);
        setRotation(Right_Shoulder_Spike_2, 0F, 0F, -0.5235988F);
        Right_Shoulder_Spike_3 = new ModelRenderer(this, 132, 32);
        Right_Shoulder_Spike_3.addBox(-10F, -16F, -2F, 6, 4, 6);
        Right_Shoulder_Spike_3.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Spike_3.setTextureSize(512, 256);
        Right_Shoulder_Spike_3.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Spike_3);
        setRotation(Right_Shoulder_Spike_3, 0F, 0F, -0.4363323F);
        Right_Shoulder_Spike_4 = new ModelRenderer(this, 132, 25);
        Right_Shoulder_Spike_4.addBox(-10F, -18F, -1F, 4, 3, 4);
        Right_Shoulder_Spike_4.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Spike_4.setTextureSize(512, 256);
        Right_Shoulder_Spike_4.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Spike_4);
        setRotation(Right_Shoulder_Spike_4, 0F, 0F, -0.3490659F);
        Right_Shoulder_Spike_5 = new ModelRenderer(this, 132, 20);
        Right_Shoulder_Spike_5.addBox(-10.5F, -20F, 0F, 2, 3, 2);
        Right_Shoulder_Spike_5.setRotationPoint(-15F, -14F, 0F);
        Right_Shoulder_Spike_5.setTextureSize(512, 256);
        Right_Shoulder_Spike_5.mirror = true;
        convertToChild(Right_Chestplate_Strap, Right_Shoulder_Spike_5);
        setRotation(Right_Shoulder_Spike_5, 0F, 0F, -0.2617994F);
        Left_Shoulder_Pad_1 = new ModelRenderer(this, 338, 69);
        Left_Shoulder_Pad_1.addBox(1F, -5F, -5F, 12, 4, 12);
        Left_Shoulder_Pad_1.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Pad_1.setTextureSize(512, 256);
        Left_Shoulder_Pad_1.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Pad_1);
        setRotation(Left_Shoulder_Pad_1, 0F, 0F, 0.2617994F);
        Left_Shoulder_Pad_2 = new ModelRenderer(this, 386, 72);
        Left_Shoulder_Pad_2.addBox(11F, -7F, -4F, 2, 3, 10);
        Left_Shoulder_Pad_2.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Pad_2.setTextureSize(512, 256);
        Left_Shoulder_Pad_2.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Pad_2);
        setRotation(Left_Shoulder_Pad_2, 0F, 0F, 0.5235988F);
        Left_Shoulder_Pad_3 = new ModelRenderer(this, 410, 75);
        Left_Shoulder_Pad_3.addBox(8F, -12F, -3F, 7, 2, 8);
        Left_Shoulder_Pad_3.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Pad_3.setTextureSize(512, 256);
        Left_Shoulder_Pad_3.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Pad_3);
        setRotation(Left_Shoulder_Pad_3, 0F, 0F, 1.047198F);
        Left_Shoulder_Strap_1 = new ModelRenderer(this, 338, 85);
        Left_Shoulder_Strap_1.addBox(3F, -3F, -7F, 8, 4, 4);
        Left_Shoulder_Strap_1.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Strap_1.setTextureSize(512, 256);
        Left_Shoulder_Strap_1.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Strap_1);
        setRotation(Left_Shoulder_Strap_1, 0F, 0F, 0.2617994F);
        Left_Shoulder_Strap_2 = new ModelRenderer(this, 338, 61);
        Left_Shoulder_Strap_2.addBox(3F, -3F, 5F, 8, 4, 4);
        Left_Shoulder_Strap_2.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Strap_2.setTextureSize(512, 256);
        Left_Shoulder_Strap_2.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Strap_2);
        setRotation(Left_Shoulder_Strap_2, 0F, 0F, 0.2617994F);
        Left_Shoulder_Spike_1 = new ModelRenderer(this, 362, 54);
        Left_Shoulder_Spike_1.addBox(0F, -10F, -4F, 10, 5, 10);
        Left_Shoulder_Spike_1.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Spike_1.setTextureSize(512, 256);
        Left_Shoulder_Spike_1.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Spike_1);
        setRotation(Left_Shoulder_Spike_1, 0F, 0F, 0.6108652F);
        Left_Shoulder_Spike_2 = new ModelRenderer(this, 370, 42);
        Left_Shoulder_Spike_2.addBox(2F, -13F, -3F, 8, 4, 8);
        Left_Shoulder_Spike_2.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Spike_2.setTextureSize(512, 256);
        Left_Shoulder_Spike_2.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Spike_2);
        setRotation(Left_Shoulder_Spike_2, 0F, 0F, 0.5235988F);
        Left_Shoulder_Spike_3 = new ModelRenderer(this, 378, 32);
        Left_Shoulder_Spike_3.addBox(4F, -16F, -2F, 6, 4, 6);
        Left_Shoulder_Spike_3.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Spike_3.setTextureSize(512, 256);
        Left_Shoulder_Spike_3.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Spike_3);
        setRotation(Left_Shoulder_Spike_3, 0F, 0F, 0.4363323F);
        Left_Shoulder_Spike_4 = new ModelRenderer(this, 386, 25);
        Left_Shoulder_Spike_4.addBox(6F, -18F, -1F, 4, 3, 4);
        Left_Shoulder_Spike_4.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Spike_4.setTextureSize(512, 256);
        Left_Shoulder_Spike_4.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Spike_4);
        setRotation(Left_Shoulder_Spike_4, 0F, 0F, 0.3490659F);
        Left_Shoulder_Spike_5 = new ModelRenderer(this, 394, 20);
        Left_Shoulder_Spike_5.addBox(8.5F, -20F, 0F, 2, 3, 2);
        Left_Shoulder_Spike_5.setRotationPoint(15F, -14F, 0F);
        Left_Shoulder_Spike_5.setTextureSize(512, 256);
        Left_Shoulder_Spike_5.mirror = true;
        convertToChild(Left_Chestplate_Strap, Left_Shoulder_Spike_5);
        setRotation(Left_Shoulder_Spike_5, 0F, 0F, 0.2617994F);
        Lower_Body_Armor_1 = new ModelRenderer(this, 255, 164);
        Lower_Body_Armor_1.addBox(-5F, 29F, -6F, 10, 4, 2);
        Lower_Body_Armor_1.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_1.setTextureSize(512, 256);
        Lower_Body_Armor_1.mirror = true;
        setRotation(Lower_Body_Armor_1, 0F, 0F, 0F);
        Lower_Body_Armor_2 = new ModelRenderer(this, 243, 155);
        Lower_Body_Armor_2.addBox(-6F, 29F, -5F, 2, 4, 5);
        Lower_Body_Armor_2.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_2.setTextureSize(512, 256);
        Lower_Body_Armor_2.mirror = true;
        convertToChild(Lower_Body_Armor_1, Lower_Body_Armor_2);
        setRotation(Lower_Body_Armor_2, 0F, 0F, 0F);
        Lower_Body_Armor_3 = new ModelRenderer(this, 277, 155);
        Lower_Body_Armor_3.addBox(4F, 29F, -5F, 2, 4, 5);
        Lower_Body_Armor_3.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_3.setTextureSize(512, 256);
        Lower_Body_Armor_3.mirror = true;
        convertToChild(Lower_Body_Armor_1, Lower_Body_Armor_3);
        setRotation(Lower_Body_Armor_3, 0F, 0F, 0F);
        Lower_Body_Armor_4 = new ModelRenderer(this, 257, 148);
        Lower_Body_Armor_4.addBox(-4F, 29F, 4F, 8, 4, 2);
        Lower_Body_Armor_4.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_4.setTextureSize(512, 256);
        Lower_Body_Armor_4.mirror = true;
        convertToChild(Lower_Body_Armor_1, Lower_Body_Armor_4);
        setRotation(Lower_Body_Armor_4, 0F, 0F, 0F);
        Lower_Body_Armor_5 = new ModelRenderer(this, 249, 148);
        Lower_Body_Armor_5.addBox(-5F, 29F, 2F, 1, 4, 3);
        Lower_Body_Armor_5.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_5.setTextureSize(512, 256);
        Lower_Body_Armor_5.mirror = true;
        convertToChild(Lower_Body_Armor_1, Lower_Body_Armor_5);
        setRotation(Lower_Body_Armor_5, 0F, 0F, 0F);
        Lower_Body_Armor_6 = new ModelRenderer(this, 277, 148);
        Lower_Body_Armor_6.addBox(4F, 29F, 2F, 1, 4, 3);
        Lower_Body_Armor_6.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_6.setTextureSize(512, 256);
        Lower_Body_Armor_6.mirror = true;
        convertToChild(Lower_Body_Armor_1, Lower_Body_Armor_6);
        setRotation(Lower_Body_Armor_6, 0F, 0F, 0F);
        Lower_Body_Armor_7 = new ModelRenderer(this, 255, 170);
        Lower_Body_Armor_7.addBox(-3F, 35F, -3F, 6, 2, 6);
        Lower_Body_Armor_7.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_7.setTextureSize(512, 256);
        Lower_Body_Armor_7.mirror = true;
        setRotation(Lower_Body_Armor_7, 0F, 0F, 0F);
        Lower_Body_Armor_8 = new ModelRenderer(this, 259, 178);
        Lower_Body_Armor_8.addBox(-2F, 37F, -2F, 4, 1, 4);
        Lower_Body_Armor_8.setRotationPoint(0F, -17F, 0F);
        Lower_Body_Armor_8.setTextureSize(512, 256);
        Lower_Body_Armor_8.mirror = true;
        convertToChild(Lower_Body_Armor_7, Lower_Body_Armor_8);
        setRotation(Lower_Body_Armor_8, 0F, 0F, 0F);
        Right_Bracelet_1 = new ModelRenderer(this, 94, 85);
        Right_Bracelet_1.addBox(-28F, 0F, -1F, 6, 8, 6);
        Right_Bracelet_1.setRotationPoint(-15F, -14F, 0F);
        Right_Bracelet_1.setTextureSize(512, 256);
        Right_Bracelet_1.mirror = true;
        setRotation(Right_Bracelet_1, 0F, 0F, 0.1745329F);
        Right_Bracelet_2 = new ModelRenderer(this, 118, 85);
        Right_Bracelet_2.addBox(-9F, 14F, -1F, 6, 8, 6);
        Right_Bracelet_2.setRotationPoint(-15F, -14F, 0F);
        Right_Bracelet_2.setTextureSize(512, 256);
        Right_Bracelet_2.mirror = true;
        setRotation(Right_Bracelet_2, 0F, 0F, 0.1745329F);
        Left_Bracelet_1 = new ModelRenderer(this, 416, 85);
        Left_Bracelet_1.addBox(22F, 0F, -1F, 6, 8, 6);
        Left_Bracelet_1.setRotationPoint(15F, -14F, 0F);
        Left_Bracelet_1.setTextureSize(512, 256);
        Left_Bracelet_1.mirror = true;
        setRotation(Left_Bracelet_1, 0F, 0F, -0.1745329F);
        Left_Bracelet_2 = new ModelRenderer(this, 392, 85);
        Left_Bracelet_2.addBox(3F, 14F, -1F, 6, 8, 6);
        Left_Bracelet_2.setRotationPoint(15F, -14F, 0F);
        Left_Bracelet_2.setTextureSize(512, 256);
        Left_Bracelet_2.mirror = true;
        setRotation(Left_Bracelet_2, 0F, 0F, -0.1745329F);
        Sword_Hilt = new ModelRenderer(this, 0, 202);
        Sword_Hilt.addBox(-7F, 27F, -7F, 2, 2, 15);
        Sword_Hilt.setRotationPoint(-15F, -14F, 0F);
        Sword_Hilt.setTextureSize(512, 256);
        Sword_Hilt.mirror = true;
        convertToChild(Right_Bracelet_2, Sword_Hilt);
        setRotation(Sword_Hilt, 0F, 0F, 0.1745329F);
        Sword_Guard_1 = new ModelRenderer(this, 34, 195);
        Sword_Guard_1.addBox(-8F, 13F, -23F, 4, 8, 4);
        Sword_Guard_1.setRotationPoint(-15F, -14F, 0F);
        Sword_Guard_1.setTextureSize(512, 256);
        Sword_Guard_1.mirror = true;
        convertToChild(Right_Bracelet_2, Sword_Guard_1);
        setRotation(Sword_Guard_1, 0.6108652F, 0F, 0.1745329F);
        Sword_Guard_2 = new ModelRenderer(this, 34, 207);
        Sword_Guard_2.addBox(-8F, 25F, 9F, 4, 8, 4);
        Sword_Guard_2.setRotationPoint(-15F, -14F, 0F);
        Sword_Guard_2.setTextureSize(512, 256);
        Sword_Guard_2.mirror = true;
        convertToChild(Right_Bracelet_2, Sword_Guard_2);
        setRotation(Sword_Guard_2, -0.6108652F, 0F, 0.1745329F);
        Sword_Blade = new ModelRenderer(this, 50, 176);
        Sword_Blade.addBox(-6F, 25F, -36F, 0, 6, 28);
        Sword_Blade.setRotationPoint(-15F, -14F, 0F);
        Sword_Blade.setTextureSize(512, 256);
        Sword_Blade.mirror = true;
        convertToChild(Right_Bracelet_2, Sword_Blade);
        setRotation(Sword_Blade, 0F, 0F, 0.1745329F);
        War_Axe_Handle = new ModelRenderer(this, 0, 219);
        War_Axe_Handle.addBox(-26F, 13F, -25F, 2, 2, 35);
        War_Axe_Handle.setRotationPoint(-15F, -14F, 0F);
        War_Axe_Handle.setTextureSize(512, 256);
        War_Axe_Handle.mirror = true;
        convertToChild(Right_Bracelet_1, War_Axe_Handle);
        setRotation(War_Axe_Handle, 0F, 0F, 0.1745329F);
        War_Axe_Shoulder = new ModelRenderer(this, 74, 231);
        War_Axe_Shoulder.addBox(-26.5F, 12.5F, -37F, 3, 3, 12);
        War_Axe_Shoulder.setRotationPoint(-15F, -14F, 0F);
        War_Axe_Shoulder.setTextureSize(512, 256);
        War_Axe_Shoulder.mirror = true;
        convertToChild(Right_Bracelet_1, War_Axe_Shoulder);
        setRotation(War_Axe_Shoulder, 0F, 0F, 0.1745329F);
        War_Axe_Head_1 = new ModelRenderer(this, 74, 203);
        War_Axe_Head_1.addBox(-25F, 2.5F, -40F, 0, 10, 18);
        War_Axe_Head_1.setRotationPoint(-15F, -14F, 0F);
        War_Axe_Head_1.setTextureSize(512, 256);
        War_Axe_Head_1.mirror = true;
        convertToChild(Right_Bracelet_1, War_Axe_Head_1);
        setRotation(War_Axe_Head_1, 0F, 0F, 0.1745329F);
        War_Axe_Head_2 = new ModelRenderer(this, 74, 228);
        War_Axe_Head_2.addBox(-25F, 15.5F, -40F, 0, 10, 18);
        War_Axe_Head_2.setRotationPoint(-15F, -14F, 0F);
        War_Axe_Head_2.setTextureSize(512, 256);
        War_Axe_Head_2.mirror = true;
        convertToChild(Right_Bracelet_1, War_Axe_Head_2);
        setRotation(War_Axe_Head_2, 0F, 0F, 0.1745329F);
        Katana_Pommel = new ModelRenderer(this, 0, 187);
        Katana_Pommel.addBox(4F, 26F, 9F, 4, 4, 4);
        Katana_Pommel.setRotationPoint(15F, -14F, 0F);
        Katana_Pommel.setTextureSize(512, 256);
        Katana_Pommel.mirror = true;
        convertToChild(Left_Bracelet_2, Katana_Pommel);
        setRotation(Katana_Pommel, 0F, 0F, -0.1745329F);
        Katana_Hilt = new ModelRenderer(this, 16, 173);
        Katana_Hilt.addBox(5F, 27F, -11F, 2, 2, 20);
        Katana_Hilt.setRotationPoint(15F, -14F, 0F);
        Katana_Hilt.setTextureSize(512, 256);
        Katana_Hilt.mirror = true;
        convertToChild(Left_Bracelet_2, Katana_Hilt);
        setRotation(Katana_Hilt, 0F, 0F, -0.1745329F);
        Katana_Guard = new ModelRenderer(this, 60, 186);
        Katana_Guard.addBox(4.5F, 25F, -14F, 3, 6, 3);
        Katana_Guard.setRotationPoint(15F, -14F, 0F);
        Katana_Guard.setTextureSize(512, 256);
        Katana_Guard.mirror = true;
        convertToChild(Left_Bracelet_2, Katana_Guard);
        setRotation(Katana_Guard, 0F, 0F, -0.1745329F);
        Katana_Blade = new ModelRenderer(this, 72, 152);
        Katana_Blade.addBox(6F, 22F, -48F, 0, 9, 34);
        Katana_Blade.setRotationPoint(15F, -14F, 0F);
        Katana_Blade.setTextureSize(512, 256);
        Katana_Blade.mirror = true;
        convertToChild(Left_Bracelet_2, Katana_Blade);
        setRotation(Katana_Blade, 0F, 0F, -0.1745329F);
        Trident_Rear = new ModelRenderer(this, 0, 169);
        Trident_Rear.addBox(25F, 18F, -1F, 0, 2, 2);
        Trident_Rear.setRotationPoint(15F, -14F, 0F);
        Trident_Rear.setTextureSize(512, 256);
        Trident_Rear.mirror = true;
        convertToChild(Left_Bracelet_2, Trident_Rear);
        setRotation(Trident_Rear, 0.7853982F, 0F, -0.1745329F);
        Trident = new ModelRenderer(this, 4, 112);
        Trident.addBox(25F, 9F, -40F, 0, 9, 52);
        Trident.setRotationPoint(15F, -14F, 0F);
        Trident.setTextureSize(512, 256);
        Trident.mirror = true;
        convertToChild(Left_Bracelet_2, Trident);
        setRotation(Trident, 0F, 0F, -0.1745329F);
        Ethereal_Torso = new ModelRenderer(this, 0, 8);
        Ethereal_Torso.addBox(-14F, 0F, -6F, 28, 22, 11);
        Ethereal_Torso.setRotationPoint(0F, -17F, 0F);
        Ethereal_Torso.setTextureSize(512, 256);
        Ethereal_Torso.mirror = true;
        setRotation(Ethereal_Torso, 0F, 0F, 0F);
        Ethereal_Waist_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Waist_1.addBox(-12F, 22F, -6F, 24, 1, 11);
        Ethereal_Waist_1.setRotationPoint(0F, -17F, 0F);
        Ethereal_Waist_1.setTextureSize(512, 256);
        Ethereal_Waist_1.mirror = true;
        setRotation(Ethereal_Waist_1, 0F, 0F, 0F);
        Ethereal_Waist_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Waist_2.addBox(-10F, 23F, -6F, 20, 3, 11);
        Ethereal_Waist_2.setRotationPoint(0F, -17F, 0F);
        Ethereal_Waist_2.setTextureSize(512, 256);
        Ethereal_Waist_2.mirror = true;
        setRotation(Ethereal_Waist_2, 0F, 0F, 0F);
        Ethereal_Lower_Body_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Lower_Body_1.addBox(-4F, 26F, -4F, 8, 7, 8);
        Ethereal_Lower_Body_1.setRotationPoint(0F, -17F, 0F);
        Ethereal_Lower_Body_1.setTextureSize(512, 256);
        Ethereal_Lower_Body_1.mirror = true;
        setRotation(Ethereal_Lower_Body_1, 0F, 0F, 0F);
        Ethereal_Lower_Body_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Lower_Body_2.addBox(-3.5F, 33F, -3.5F, 7, 2, 7);
        Ethereal_Lower_Body_2.setRotationPoint(0F, -17F, 0F);
        Ethereal_Lower_Body_2.setTextureSize(512, 256);
        Ethereal_Lower_Body_2.mirror = true;
        setRotation(Ethereal_Lower_Body_2, 0F, 0F, 0F);
        Ethereal_Right_Hand_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Right_Hand_1.addBox(-30F, 8F, -3F, 10, 9, 10);
        Ethereal_Right_Hand_1.setRotationPoint(-15F, -14F, 0F);
        Ethereal_Right_Hand_1.setTextureSize(512, 256);
        Ethereal_Right_Hand_1.mirror = true;
        setRotation(Ethereal_Right_Hand_1, 0F, 0F, 0.1745329F);
        Ethereal_Right_Knuckle_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Right_Knuckle_1.addBox(-30F, 17F, -3F, 9, 2, 10);
        Ethereal_Right_Knuckle_1.setRotationPoint(-15F, -14F, 0F);
        Ethereal_Right_Knuckle_1.setTextureSize(512, 256);
        Ethereal_Right_Knuckle_1.mirror = true;
        setRotation(Ethereal_Right_Knuckle_1, 0F, 0F, 0.1745329F);
        Ethereal_Right_Hand_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Right_Hand_2.addBox(-11F, 22F, -3F, 10, 9, 10);
        Ethereal_Right_Hand_2.setRotationPoint(-15F, -14F, 0F);
        Ethereal_Right_Hand_2.setTextureSize(512, 256);
        Ethereal_Right_Hand_2.mirror = true;
        setRotation(Ethereal_Right_Hand_2, 0F, 0F, 0.1745329F);
        Ethereal_Right_Knuckle_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Right_Knuckle_2.addBox(-11F, 31F, -3F, 9, 2, 10);
        Ethereal_Right_Knuckle_2.setRotationPoint(-15F, -14F, 0F);
        Ethereal_Right_Knuckle_2.setTextureSize(512, 256);
        Ethereal_Right_Knuckle_2.mirror = true;
        setRotation(Ethereal_Right_Knuckle_2, 0F, 0F, 0.1745329F);
        Ethereal_Left_Hand_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Left_Hand_1.addBox(20F, 8F, -3F, 10, 9, 10);
        Ethereal_Left_Hand_1.setRotationPoint(15F, -14F, 0F);
        Ethereal_Left_Hand_1.setTextureSize(512, 256);
        Ethereal_Left_Hand_1.mirror = true;
        setRotation(Ethereal_Left_Hand_1, 0F, 0F, -0.1745329F);
        Ethereal_Left_Knuckle_1 = new ModelRenderer(this, 0, 8);
        Ethereal_Left_Knuckle_1.addBox(21F, 17F, -3F, 9, 2, 10);
        Ethereal_Left_Knuckle_1.setRotationPoint(15F, -14F, 0F);
        Ethereal_Left_Knuckle_1.setTextureSize(512, 256);
        Ethereal_Left_Knuckle_1.mirror = true;
        setRotation(Ethereal_Left_Knuckle_1, 0F, 0F, -0.1745329F);
        Ethereal_Left_Hand_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Left_Hand_2.addBox(1F, 22F, -3F, 10, 9, 10);
        Ethereal_Left_Hand_2.setRotationPoint(15F, -14F, 0F);
        Ethereal_Left_Hand_2.setTextureSize(512, 256);
        Ethereal_Left_Hand_2.mirror = true;
        setRotation(Ethereal_Left_Hand_2, 0F, 0F, -0.1745329F);
        Ethereal_Left_Knuckle_2 = new ModelRenderer(this, 0, 8);
        Ethereal_Left_Knuckle_2.addBox(2F, 31F, -3F, 9, 2, 10);
        Ethereal_Left_Knuckle_2.setRotationPoint(15F, -14F, 0F);
        Ethereal_Left_Knuckle_2.setTextureSize(512, 256);
        Ethereal_Left_Knuckle_2.mirror = true;
        setRotation(Ethereal_Left_Knuckle_2, 0F, 0F, -0.1745329F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        EntityDarkPet3 darkPet = (EntityDarkPet3) entity;

        Top_Helm.rotationPointY = darkPet.getFloatingRotation();

        Ring.rotateAngleZ = f2 / 20;

        Front_Chestplate_Piece_1.rotationPointY = darkPet.getFloatingRotation();
        Right_Chestplate_Strap.rotationPointY = darkPet.getFloatingRotation();
        Left_Chestplate_Strap.rotationPointY = darkPet.getFloatingRotation();
        Lower_Body_Armor_1.rotationPointY = darkPet.getFloatingRotation();
        Lower_Body_Armor_7.rotationPointY = darkPet.getFloatingRotation();

        Ring.render(f5);
        Top_Helm.render(f5);
        Front_Chestplate_Piece_1.render(f5);
        Right_Chestplate_Strap.render(f5);
        Left_Chestplate_Strap.render(f5);
        Lower_Body_Armor_1.render(f5);
        Lower_Body_Armor_7.render(f5);
        Right_Bracelet_1.render(f5);
        Right_Bracelet_2.render(f5);
        Left_Bracelet_1.render(f5);
        Left_Bracelet_2.render(f5);

        Ethereal_Head.render(f5);
        Ethereal_Torso.render(f5);
        Ethereal_Waist_1.render(f5);
        Ethereal_Waist_2.render(f5);
        Ethereal_Lower_Body_1.render(f5);
        Ethereal_Lower_Body_2.render(f5);
        Ethereal_Right_Hand_1.render(f5);
        Ethereal_Right_Knuckle_1.render(f5);
        Ethereal_Right_Hand_2.render(f5);
        Ethereal_Right_Knuckle_2.render(f5);
        Ethereal_Left_Hand_1.render(f5);
        Ethereal_Left_Knuckle_1.render(f5);
        Ethereal_Left_Hand_2.render(f5);
        Ethereal_Left_Knuckle_2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Top_Helm.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Top_Helm.rotateAngleY = f3 / (180F / (float) Math.PI);
        this.Ethereal_Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Ethereal_Head.rotateAngleY = f3 / (180F / (float) Math.PI);

        ////////////////////////////////ARMS///////////////////////////////
        this.Left_Bracelet_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Right_Bracelet_2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
        this.Left_Bracelet_2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Right_Bracelet_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;

        this.Ethereal_Left_Hand_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Ethereal_Right_Hand_2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
        this.Ethereal_Left_Hand_2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Ethereal_Right_Hand_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;

        this.Ethereal_Left_Knuckle_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Ethereal_Right_Knuckle_2.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
        this.Ethereal_Left_Knuckle_2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 2.0F * f1 * 0.5F;
        this.Ethereal_Right_Knuckle_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
    }

}

