package com.hoopawolf.mwaw.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;

public class ModelLightningPet2 extends ModelBase {
    //fields
    ModelRenderer Upper_Torso;
    ModelRenderer Lower_Torso;
    ModelRenderer Neck;
    ModelRenderer Head;
    ModelRenderer Right_Frill_1;
    ModelRenderer Right_Frill_2;
    ModelRenderer Right_Frill_3;
    ModelRenderer Right_Frill_4;
    ModelRenderer Left_Frill_1;
    ModelRenderer Left_Frill_2;
    ModelRenderer Left_Frill_3;
    ModelRenderer Left_Frill_4;
    ModelRenderer Horn_1;
    ModelRenderer Horn_2;
    ModelRenderer Hair_1;
    ModelRenderer Hair_2;
    ModelRenderer Snout;
    ModelRenderer Chest;
    ModelRenderer Front_Right_Leg_1;
    ModelRenderer Front_Right_Leg_2;
    ModelRenderer Front_Right_Foot;
    ModelRenderer Front_Right_Claw_1;
    ModelRenderer Front_Right_Claw_2;
    ModelRenderer Front_Right_Claw_3;
    ModelRenderer Front_Left_Leg_1;
    ModelRenderer Front_Left_Leg_2;
    ModelRenderer Front_Left_Foot;
    ModelRenderer Front_Left_Claw_1;
    ModelRenderer Front_Left_Claw_2;
    ModelRenderer Front_Left_Claw_3;
    ModelRenderer Back_Right_Leg_2;
    ModelRenderer Back_Right_Leg_1;
    ModelRenderer Back_Right_Foot;
    ModelRenderer Back_Right_Claw_1;
    ModelRenderer Back_Right_Claw_2;
    ModelRenderer Back_Right_Claw_3;
    ModelRenderer Back_Left_Leg_1;
    ModelRenderer Back_Left_Leg_2;
    ModelRenderer Back_Left_Foot;
    ModelRenderer Back_Left_Claw_1;
    ModelRenderer Back_Left_Claw_2;
    ModelRenderer Back_Left_Claw_3;
    ModelRenderer Rear;
    ModelRenderer Tail_1;
    ModelRenderer Tail_2;
    ModelRenderer Tail_3;
    ModelRenderer Tail_Point_1;
    ModelRenderer Tail_Point_2;
    ModelRenderer Tail_Point_3;
    ModelRenderer Right_Wing_Membrane_1;
    ModelRenderer Right_Wing_Membrane_2;
    ModelRenderer Right_Wing_Membrane_3;
    ModelRenderer Right_Wing_1;
    ModelRenderer Right_Wing_2;
    ModelRenderer Right_Wing_3;
    ModelRenderer Right_Wing_4;
    ModelRenderer Left_Wing_Membrane_1;
    ModelRenderer Left_Wing_Membrane_2;
    ModelRenderer Left_Wing_Membrane_3;
    ModelRenderer Left_Wing_1;
    ModelRenderer Left_Wing_2;
    ModelRenderer Left_Wing_3;
    ModelRenderer Left_Wing_4;

    public ModelLightningPet2() {
        textureWidth = 128;
        textureHeight = 64;

        Upper_Torso = new ModelRenderer(this, 50, 21);
        Upper_Torso.addBox(-4.5F, 0F, 0F, 9, 9, 10);
        Upper_Torso.setRotationPoint(0F, 9F, 0F);
        Upper_Torso.setTextureSize(128, 64);
        Upper_Torso.mirror = true;
        setRotation(Upper_Torso, -0.0698132F, 0F, 0F);
        Lower_Torso = new ModelRenderer(this, 18, 24);
        Lower_Torso.addBox(-4F, 1F, 8F, 8, 8, 8);
        Lower_Torso.setRotationPoint(0F, 9F, 0F);
        Lower_Torso.setTextureSize(128, 64);
        Lower_Torso.mirror = true;
        setRotation(Lower_Torso, 0F, 0F, 0F);
        Neck = new ModelRenderer(this, 72, 12);
        Neck.addBox(-2F, -3F, -2F, 4, 5, 4);
        Neck.setRotationPoint(0F, 9F, 0F);
        Neck.setTextureSize(128, 64);
        Neck.mirror = true;
        setRotation(Neck, 0.3665191F, 0F, 0F);
        Head = new ModelRenderer(this, 88, 9);
        Head.addBox(-3F, -6F, -4F, 6, 6, 5);
        Head.setRotationPoint(0F, 9F, 0F);
        Head.setTextureSize(128, 64);
        Head.mirror = true;
        setRotation(Head, 0F, 0F, 0F);
        Right_Frill_1 = new ModelRenderer(this, 120, 0);
        Right_Frill_1.addBox(-4F, -6F, 0F, 1, 1, 3);
        Right_Frill_1.setRotationPoint(0F, 9F, 0F);
        Right_Frill_1.setTextureSize(128, 64);
        Right_Frill_1.mirror = true;
        this.convertToChild(Head, Right_Frill_1);
        setRotation(Right_Frill_1, 0.1745329F, -0.0872665F, 0F);
        Right_Frill_2 = new ModelRenderer(this, 112, 0);
        Right_Frill_2.addBox(-4F, -5F, 0F, 1, 1, 3);
        Right_Frill_2.setRotationPoint(0F, 9F, 0F);
        Right_Frill_2.setTextureSize(128, 64);
        Right_Frill_2.mirror = true;
        this.convertToChild(Head, Right_Frill_2);
        setRotation(Right_Frill_2, 0.0872665F, -0.0872665F, 0F);
        Right_Frill_3 = new ModelRenderer(this, 120, 4);
        Right_Frill_3.addBox(-4F, -4F, 0F, 1, 1, 3);
        Right_Frill_3.setRotationPoint(0F, 9F, 0F);
        Right_Frill_3.setTextureSize(128, 64);
        Right_Frill_3.mirror = true;
        this.convertToChild(Head, Right_Frill_3);
        setRotation(Right_Frill_3, 0F, -0.0872665F, 0F);
        Right_Frill_4 = new ModelRenderer(this, 112, 4);
        Right_Frill_4.addBox(-4F, -3F, 0F, 1, 1, 3);
        Right_Frill_4.setRotationPoint(0F, 9F, 0F);
        Right_Frill_4.setTextureSize(128, 64);
        Right_Frill_4.mirror = true;
        this.convertToChild(Head, Right_Frill_4);
        setRotation(Right_Frill_4, -0.0872665F, -0.0872665F, 0F);
        Left_Frill_1 = new ModelRenderer(this, 89, 0);
        Left_Frill_1.addBox(3F, -6F, 0F, 1, 1, 3);
        Left_Frill_1.setRotationPoint(0F, 9F, 0F);
        Left_Frill_1.setTextureSize(128, 64);
        Left_Frill_1.mirror = true;
        this.convertToChild(Head, Left_Frill_1);
        setRotation(Left_Frill_1, 0.1745329F, 0.0872665F, 0F);
        Left_Frill_2 = new ModelRenderer(this, 81, 0);
        Left_Frill_2.addBox(3F, -5F, 0F, 1, 1, 3);
        Left_Frill_2.setRotationPoint(0F, 9F, 0F);
        Left_Frill_2.setTextureSize(128, 64);
        Left_Frill_2.mirror = true;
        this.convertToChild(Head, Left_Frill_2);
        setRotation(Left_Frill_2, 0.0872665F, 0.0872665F, 0F);
        Left_Frill_3 = new ModelRenderer(this, 89, 4);
        Left_Frill_3.addBox(3F, -4F, 0F, 1, 1, 3);
        Left_Frill_3.setRotationPoint(0F, 9F, 0F);
        Left_Frill_3.setTextureSize(128, 64);
        Left_Frill_3.mirror = true;
        this.convertToChild(Head, Left_Frill_3);
        setRotation(Left_Frill_3, 0F, 0.0872665F, 0F);
        Left_Frill_4 = new ModelRenderer(this, 81, 4);
        Left_Frill_4.addBox(3F, -3F, 0F, 1, 1, 3);
        Left_Frill_4.setRotationPoint(0F, 9F, 0F);
        Left_Frill_4.setTextureSize(128, 64);
        Left_Frill_4.mirror = true;
        this.convertToChild(Head, Left_Frill_4);
        setRotation(Left_Frill_4, -0.0872665F, 0.0872665F, 0F);
        Horn_1 = new ModelRenderer(this, 99, 5);
        Horn_1.addBox(-0.5F, -7F, 0.5F, 1, 2, 2);
        Horn_1.setRotationPoint(0F, 9F, 0F);
        Horn_1.setTextureSize(128, 64);
        Horn_1.mirror = true;
        this.convertToChild(Head, Horn_1);
        setRotation(Horn_1, 0.5585054F, 0F, 0F);
        Horn_2 = new ModelRenderer(this, 100, 0);
        Horn_2.addBox(-0.5F, -11F, 1.5F, 1, 4, 1);
        Horn_2.setRotationPoint(0F, 9F, 0F);
        Horn_2.setTextureSize(128, 64);
        Horn_2.mirror = true;
        this.convertToChild(Head, Horn_2);
        setRotation(Horn_2, 0.5585054F, 0F, 0F);
        Hair_1 = new ModelRenderer(this, 55, 3);
        Hair_1.addBox(-2F, -7F, -2F, 4, 4, 5);
        Hair_1.setRotationPoint(0F, 9F, 0F);
        Hair_1.setTextureSize(128, 64);
        Hair_1.mirror = true;
        this.convertToChild(Head, Hair_1);
        setRotation(Hair_1, -0.3490659F, 0F, 0F);
        Hair_2 = new ModelRenderer(this, 41, 6);
        Hair_2.addBox(-2F, -5F, 3F, 4, 2, 3);
        Hair_2.setRotationPoint(0F, 9F, 0F);
        Hair_2.setTextureSize(128, 64);
        Hair_2.mirror = true;
        this.convertToChild(Head, Hair_2);
        setRotation(Hair_2, -0.3490659F, 0F, 0F);
        Snout = new ModelRenderer(this, 110, 10);
        Snout.addBox(-2F, -6.5F, -6F, 4, 4, 5);
        Snout.setRotationPoint(0F, 9F, 0F);
        Snout.setTextureSize(128, 64);
        Snout.mirror = true;
        this.convertToChild(Head, Snout);
        setRotation(Snout, 0.4363323F, 0F, 0F);
        Chest = new ModelRenderer(this, 88, 26);
        Chest.addBox(-4F, 1.5F, -3F, 8, 7, 3);
        Chest.setRotationPoint(0F, 9F, 0F);
        Chest.setTextureSize(128, 64);
        Chest.mirror = true;
        setRotation(Chest, 0F, 0F, 0F);
        Front_Right_Leg_1 = new ModelRenderer(this, 48, 40);
        Front_Right_Leg_1.addBox(-3F, -1F, -1.5F, 3, 5, 3);
        Front_Right_Leg_1.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Leg_1.setTextureSize(128, 64);
        Front_Right_Leg_1.mirror = true;
        setRotation(Front_Right_Leg_1, 0F, 0F, 0F);
        Front_Right_Leg_2 = new ModelRenderer(this, 48, 48);
        Front_Right_Leg_2.addBox(-3F, 0F, 1.6F, 3, 8, 3);
        Front_Right_Leg_2.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Leg_2.setTextureSize(128, 64);
        Front_Right_Leg_2.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Leg_2);
        setRotation(Front_Right_Leg_2, -0.5235988F, 0F, 0F);
        Front_Right_Foot = new ModelRenderer(this, 48, 59);
        Front_Right_Foot.addBox(-3F, 7F, -3.5F, 3, 2, 3);
        Front_Right_Foot.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Foot.setTextureSize(128, 64);
        Front_Right_Foot.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Foot);
        setRotation(Front_Right_Foot, 0F, 0F, 0F);
        Front_Right_Claw_1 = new ModelRenderer(this, 60, 59);
        Front_Right_Claw_1.addBox(-3F, 8F, -5.5F, 0, 1, 2);
        Front_Right_Claw_1.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Claw_1.setTextureSize(128, 64);
        Front_Right_Claw_1.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_1);
        setRotation(Front_Right_Claw_1, 0F, 0F, 0F);
        Front_Right_Claw_2 = new ModelRenderer(this, 60, 60);
        Front_Right_Claw_2.addBox(-1.5F, 8F, -5.5F, 0, 1, 2);
        Front_Right_Claw_2.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Claw_2.setTextureSize(128, 64);
        Front_Right_Claw_2.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_2);
        setRotation(Front_Right_Claw_2, 0F, 0F, 0F);
        Front_Right_Claw_3 = new ModelRenderer(this, 60, 61);
        Front_Right_Claw_3.addBox(0F, 8F, -5.5F, 0, 1, 2);
        Front_Right_Claw_3.setRotationPoint(-4.5F, 15F, 2F);
        Front_Right_Claw_3.setTextureSize(128, 64);
        Front_Right_Claw_3.mirror = true;
        this.convertToChild(Front_Right_Leg_1, Front_Right_Claw_3);
        setRotation(Front_Right_Claw_3, 0F, 0F, 0F);
        Front_Left_Leg_1 = new ModelRenderer(this, 32, 40);
        Front_Left_Leg_1.addBox(0F, -1F, -1.5F, 3, 5, 3);
        Front_Left_Leg_1.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Leg_1.setTextureSize(128, 64);
        Front_Left_Leg_1.mirror = true;
        setRotation(Front_Left_Leg_1, 0F, 0F, 0F);
        Front_Left_Leg_2 = new ModelRenderer(this, 32, 48);
        Front_Left_Leg_2.addBox(0F, 0F, 1.6F, 3, 8, 3);
        Front_Left_Leg_2.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Leg_2.setTextureSize(128, 64);
        Front_Left_Leg_2.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Leg_2);
        setRotation(Front_Left_Leg_2, -0.5235988F, 0F, 0F);
        Front_Left_Foot = new ModelRenderer(this, 32, 59);
        Front_Left_Foot.addBox(0F, 7F, -3.5F, 3, 2, 3);
        Front_Left_Foot.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Foot.setTextureSize(128, 64);
        Front_Left_Foot.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Foot);
        setRotation(Front_Left_Foot, 0F, 0F, 0F);
        Front_Left_Claw_1 = new ModelRenderer(this, 44, 59);
        Front_Left_Claw_1.addBox(3F, 8F, -5.5F, 0, 1, 2);
        Front_Left_Claw_1.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Claw_1.setTextureSize(128, 64);
        Front_Left_Claw_1.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_1);
        setRotation(Front_Left_Claw_1, 0F, 0F, 0F);
        Front_Left_Claw_2 = new ModelRenderer(this, 44, 60);
        Front_Left_Claw_2.addBox(1.5F, 8F, -5.5F, 0, 1, 2);
        Front_Left_Claw_2.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Claw_2.setTextureSize(128, 64);
        Front_Left_Claw_2.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_2);
        setRotation(Front_Left_Claw_2, 0F, 0F, 0F);
        Front_Left_Claw_3 = new ModelRenderer(this, 44, 61);
        Front_Left_Claw_3.addBox(0F, 8F, -5.5F, 0, 1, 2);
        Front_Left_Claw_3.setRotationPoint(4.5F, 15F, 2F);
        Front_Left_Claw_3.setTextureSize(128, 64);
        Front_Left_Claw_3.mirror = true;
        this.convertToChild(Front_Left_Leg_1, Front_Left_Claw_3);
        setRotation(Front_Left_Claw_3, 0F, 0F, 0F);
        Back_Right_Leg_1 = new ModelRenderer(this, 16, 42);
        Back_Right_Leg_1.addBox(-3F, -1F, -1.5F, 3, 4, 3);
        Back_Right_Leg_1.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Leg_1.setTextureSize(128, 64);
        Back_Right_Leg_1.mirror = true;
        setRotation(Back_Right_Leg_1, 0F, 0F, 0F);
        Back_Right_Leg_2 = new ModelRenderer(this, 16, 49);
        Back_Right_Leg_2.addBox(-3F, 0F, 0.5F, 3, 7, 3);
        Back_Right_Leg_2.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Leg_2.setTextureSize(128, 64);
        Back_Right_Leg_2.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Leg_2);
        setRotation(Back_Right_Leg_2, -0.3490659F, 0F, 0F);
        Back_Right_Foot = new ModelRenderer(this, 16, 59);
        Back_Right_Foot.addBox(-3F, 6F, -2F, 3, 2, 3);
        Back_Right_Foot.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Foot.setTextureSize(128, 64);
        Back_Right_Foot.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Foot);
        setRotation(Back_Right_Foot, 0F, 0F, 0F);
        Back_Right_Claw_1 = new ModelRenderer(this, 28, 59);
        Back_Right_Claw_1.addBox(-3F, 7F, -4F, 0, 1, 2);
        Back_Right_Claw_1.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Claw_1.setTextureSize(128, 64);
        Back_Right_Claw_1.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_1);
        setRotation(Back_Right_Claw_1, 0F, 0F, 0F);
        Back_Right_Claw_2 = new ModelRenderer(this, 28, 60);
        Back_Right_Claw_2.addBox(-1.5F, 7F, -4F, 0, 1, 2);
        Back_Right_Claw_2.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Claw_2.setTextureSize(128, 64);
        Back_Right_Claw_2.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_2);
        setRotation(Back_Right_Claw_2, 0F, 0F, 0F);
        Back_Right_Claw_3 = new ModelRenderer(this, 28, 61);
        Back_Right_Claw_3.addBox(0F, 7F, -4F, 0, 1, 2);
        Back_Right_Claw_3.setRotationPoint(-4F, 16F, 12F);
        Back_Right_Claw_3.setTextureSize(128, 64);
        Back_Right_Claw_3.mirror = true;
        this.convertToChild(Back_Right_Leg_1, Back_Right_Claw_3);
        setRotation(Back_Right_Claw_3, 0F, 0F, 0F);
        Back_Left_Leg_1 = new ModelRenderer(this, 0, 42);
        Back_Left_Leg_1.addBox(0F, -1F, -1.5F, 3, 4, 3);
        Back_Left_Leg_1.setRotationPoint(4F, 16F, 12F);
        Back_Left_Leg_1.setTextureSize(128, 64);
        Back_Left_Leg_1.mirror = true;
        setRotation(Back_Left_Leg_1, 0F, 0F, 0F);
        Back_Left_Leg_2 = new ModelRenderer(this, 0, 49);
        Back_Left_Leg_2.addBox(0F, 0F, 0.5F, 3, 7, 3);
        Back_Left_Leg_2.setRotationPoint(4F, 16F, 12F);
        Back_Left_Leg_2.setTextureSize(128, 64);
        Back_Left_Leg_2.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Leg_2);
        setRotation(Back_Left_Leg_2, -0.3490659F, 0F, 0F);
        Back_Left_Foot = new ModelRenderer(this, 0, 59);
        Back_Left_Foot.addBox(0F, 6F, -2F, 3, 2, 3);
        Back_Left_Foot.setRotationPoint(4F, 16F, 12F);
        Back_Left_Foot.setTextureSize(128, 64);
        Back_Left_Foot.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Foot);
        setRotation(Back_Left_Foot, 0F, 0F, 0F);
        Back_Left_Claw_1 = new ModelRenderer(this, 12, 59);
        Back_Left_Claw_1.addBox(3F, 7F, -4F, 0, 1, 2);
        Back_Left_Claw_1.setRotationPoint(4F, 16F, 12F);
        Back_Left_Claw_1.setTextureSize(128, 64);
        Back_Left_Claw_1.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_1);
        setRotation(Back_Left_Claw_1, 0F, 0F, 0F);
        Back_Left_Claw_2 = new ModelRenderer(this, 12, 60);
        Back_Left_Claw_2.addBox(1.5F, 7F, -4F, 0, 1, 2);
        Back_Left_Claw_2.setRotationPoint(4F, 16F, 12F);
        Back_Left_Claw_2.setTextureSize(128, 64);
        Back_Left_Claw_2.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_2);
        setRotation(Back_Left_Claw_2, 0F, 0F, 0F);
        Back_Left_Claw_3 = new ModelRenderer(this, 12, 61);
        Back_Left_Claw_3.addBox(0F, 7F, -4F, 0, 1, 2);
        Back_Left_Claw_3.setRotationPoint(4F, 16F, 12F);
        Back_Left_Claw_3.setTextureSize(128, 64);
        Back_Left_Claw_3.mirror = true;
        this.convertToChild(Back_Left_Leg_1, Back_Left_Claw_3);
        setRotation(Back_Left_Claw_3, 0F, 0F, 0F);
        Rear = new ModelRenderer(this, 0, 32);
        Rear.addBox(-2F, -2F, -1F, 4, 4, 5);
        Rear.setRotationPoint(0F, 14F, 16F);
        Rear.setTextureSize(128, 64);
        Rear.mirror = true;
        setRotation(Rear, 0.3490659F, 0F, 0F);
        Tail_1 = new ModelRenderer(this, 0, 24);
        Tail_1.addBox(-1.5F, 0F, 2F, 3, 3, 5);
        Tail_1.setRotationPoint(0F, 14F, 16F);
        Tail_1.setTextureSize(128, 64);
        Tail_1.mirror = true;
        setRotation(Tail_1, 1.047198F, 0F, 0F);
        Tail_2 = new ModelRenderer(this, 0, 16);
        Tail_2.addBox(-1.5F, 4F, 3.5F, 3, 3, 5);
        Tail_2.setRotationPoint(0F, 14F, 16F);
        Tail_2.setTextureSize(128, 64);
        Tail_2.mirror = true;
        setRotation(Tail_2, 1.745329F, 0F, 0F);
        Tail_3 = new ModelRenderer(this, 16, 13);
        Tail_3.addBox(-1.5F, 7F, 2F, 3, 3, 5);
        Tail_3.setRotationPoint(0F, 14F, 16F);
        Tail_3.setTextureSize(128, 64);
        Tail_3.mirror = true;
        setRotation(Tail_3, 2.443461F, 0F, 0F);
        Tail_Point_1 = new ModelRenderer(this, 32, 13);
        Tail_Point_1.addBox(-1F, 6F, 7F, 2, 2, 2);
        Tail_Point_1.setRotationPoint(0F, 14F, 16F);
        Tail_Point_1.setTextureSize(128, 64);
        Tail_Point_1.mirror = true;
        setRotation(Tail_Point_1, 2.356194F, 0F, 0F);
        Tail_Point_2 = new ModelRenderer(this, 40, 13);
        Tail_Point_2.addBox(-1F, 9.5F, 1F, 2, 2, 2);
        Tail_Point_2.setRotationPoint(0F, 14F, 16F);
        Tail_Point_2.setTextureSize(128, 64);
        Tail_Point_2.mirror = true;
        setRotation(Tail_Point_2, 3.141593F, 0F, 0F);
        Tail_Point_3 = new ModelRenderer(this, 48, 13);
        Tail_Point_3.addBox(-0.5F, 10F, 3F, 1, 1, 2);
        Tail_Point_3.setRotationPoint(0F, 14F, 16F);
        Tail_Point_3.setTextureSize(128, 64);
        Tail_Point_3.mirror = true;
        setRotation(Tail_Point_3, 3.141593F, 0F, 0F);
        Right_Wing_Membrane_1 = new ModelRenderer(this, 68, 40);
        Right_Wing_Membrane_1.addBox(0F, -4F, 0F, 1, 5, 1);
        Right_Wing_Membrane_1.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_Membrane_1.setTextureSize(128, 64);
        Right_Wing_Membrane_1.mirror = true;
        setRotation(Right_Wing_Membrane_1, -0.5235988F, -0.5235988F, 0F);
        Right_Wing_Membrane_2 = new ModelRenderer(this, 64, 40);
        Right_Wing_Membrane_2.addBox(0F, -7F, -3F, 1, 6, 1);
        Right_Wing_Membrane_2.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_Membrane_2.setTextureSize(128, 64);
        Right_Wing_Membrane_2.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_Membrane_2);
        setRotation(Right_Wing_Membrane_2, -2.007129F, -0.5235988F, 0F);
        Right_Wing_Membrane_3 = new ModelRenderer(this, 60, 40);
        Right_Wing_Membrane_3.addBox(0F, -14F, -2.5F, 1, 11, 1);
        Right_Wing_Membrane_3.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_Membrane_3.setTextureSize(128, 64);
        Right_Wing_Membrane_3.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_Membrane_3);
        setRotation(Right_Wing_Membrane_3, -1.22173F, -0.5235988F, 0F);
        Right_Wing_1 = new ModelRenderer(this, 76, 53);
        Right_Wing_1.addBox(0.5F, 0F, -1F, 0, 4, 7);
        Right_Wing_1.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_1.setTextureSize(128, 64);
        Right_Wing_1.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_1);
        setRotation(Right_Wing_1, 0.4886922F, -0.5235988F, 0F);
        Right_Wing_2 = new ModelRenderer(this, 72, 47);
        Right_Wing_2.addBox(0.5F, -1F, 1.5F, 0, 4, 9);
        Right_Wing_2.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_2.setTextureSize(128, 64);
        Right_Wing_2.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_2);
        setRotation(Right_Wing_2, 0.4537856F, -0.5235988F, 0F);
        Right_Wing_3 = new ModelRenderer(this, 64, 49);
        Right_Wing_3.addBox(0.5F, -13F, -2F, 0, 10, 4);
        Right_Wing_3.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_3.setTextureSize(128, 64);
        Right_Wing_3.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_3);
        setRotation(Right_Wing_3, -1.22173F, -0.5235988F, 0F);
        Right_Wing_4 = new ModelRenderer(this, 60, 48);
        Right_Wing_4.addBox(0.5F, -13F, -5.5F, 0, 1, 4);
        Right_Wing_4.setRotationPoint(-4.5F, 10F, 3F);
        Right_Wing_4.setTextureSize(128, 64);
        Right_Wing_4.mirror = true;
        this.convertToChild(Right_Wing_Membrane_1, Right_Wing_4);
        setRotation(Right_Wing_4, -1.500983F, -0.5235988F, 0F);
        Left_Wing_Membrane_1 = new ModelRenderer(this, 98, 40);
        Left_Wing_Membrane_1.addBox(-1F, -4F, 0F, 1, 5, 1);
        Left_Wing_Membrane_1.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_Membrane_1.setTextureSize(128, 64);
        Left_Wing_Membrane_1.mirror = true;
        setRotation(Left_Wing_Membrane_1, -0.5235988F, 0.5235988F, 0F);
        Left_Wing_Membrane_2 = new ModelRenderer(this, 94, 40);
        Left_Wing_Membrane_2.addBox(-1F, -7F, -3F, 1, 6, 1);
        Left_Wing_Membrane_2.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_Membrane_2.setTextureSize(128, 64);
        Left_Wing_Membrane_2.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_Membrane_2);
        setRotation(Left_Wing_Membrane_2, -2.007129F, 0.5235988F, 0F);
        Left_Wing_Membrane_3 = new ModelRenderer(this, 90, 40);
        Left_Wing_Membrane_3.addBox(-1F, -14F, -2.5F, 1, 11, 1);
        Left_Wing_Membrane_3.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_Membrane_3.setTextureSize(128, 64);
        Left_Wing_Membrane_3.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_Membrane_3);
        setRotation(Left_Wing_Membrane_3, -1.22173F, 0.5235988F, 0F);
        Left_Wing_1 = new ModelRenderer(this, 106, 53);
        Left_Wing_1.addBox(-0.5F, 0F, -1F, 0, 4, 7);
        Left_Wing_1.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_1.setTextureSize(128, 64);
        Left_Wing_1.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_1);
        setRotation(Left_Wing_1, 0.4886922F, 0.5235988F, 0F);
        Left_Wing_2 = new ModelRenderer(this, 102, 47);
        Left_Wing_2.addBox(-0.5F, -1F, 1.5F, 0, 4, 9);
        Left_Wing_2.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_2.setTextureSize(128, 64);
        Left_Wing_2.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_2);
        setRotation(Left_Wing_2, 0.4537856F, 0.5235988F, 0F);
        Left_Wing_3 = new ModelRenderer(this, 94, 49);
        Left_Wing_3.addBox(-0.5F, -13F, -2F, 0, 10, 4);
        Left_Wing_3.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_3.setTextureSize(128, 64);
        Left_Wing_3.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_3);
        setRotation(Left_Wing_3, -1.22173F, 0.5235988F, 0F);
        Left_Wing_4 = new ModelRenderer(this, 90, 48);
        Left_Wing_4.addBox(-0.5F, -13F, -5.5F, 0, 1, 4);
        Left_Wing_4.setRotationPoint(4.5F, 10F, 3F);
        Left_Wing_4.setTextureSize(128, 64);
        Left_Wing_4.mirror = true;
        this.convertToChild(Left_Wing_Membrane_1, Left_Wing_4);
        setRotation(Left_Wing_4, -1.500983F, 0.5235988F, 0F);
    }

    protected void convertToChild(ModelRenderer parParent, ModelRenderer parChild) {
        // move child rotation point to be relative to parent
        parChild.rotationPointX -= parParent.rotationPointX;
        parChild.rotationPointY -= parParent.rotationPointY;
        parChild.rotationPointZ -= parParent.rotationPointZ;
        // make rotations relative to parent
        parChild.rotateAngleX -= parParent.rotateAngleX;
        parChild.rotateAngleY -= parParent.rotateAngleY;
        parChild.rotateAngleZ -= parParent.rotateAngleZ;
        // create relationship
        parParent.addChild(parChild);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        GL11.glScalef(1.4F, 1.4F, 1.4F);
        GL11.glTranslatef(0.F, -0.5F, -0.4F);

        Upper_Torso.render(f5);
        Lower_Torso.render(f5);
        Neck.render(f5);
        Head.render(f5);
        Chest.render(f5);
        Front_Right_Leg_1.render(f5);
        Front_Left_Leg_1.render(f5);
        Back_Right_Leg_1.render(f5);
        Back_Left_Leg_1.render(f5);
        Rear.render(f5);
        Tail_1.render(f5);
        Tail_2.render(f5);
        Tail_3.render(f5);
        Tail_Point_1.render(f5);
        Tail_Point_2.render(f5);
        Tail_Point_3.render(f5);
        Right_Wing_Membrane_1.render(f5);
        Left_Wing_Membrane_1.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);

        ////////////////////////////////HEAD///////////////////////////////////////
        this.Head.rotateAngleX = f4 / (180F / (float) Math.PI);
        this.Head.rotateAngleY = f3 / (180F / (float) Math.PI);

///////////////////////////////LEGS///////////////////////////////////////
        this.Front_Left_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Front_Right_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        this.Back_Right_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
        this.Back_Left_Leg_1.rotateAngleX = MathHelper.cos(f * 0.6662F + (float) Math.PI) * 1.4F * f1;

        //////////////////////////////WINGS////////////////////////////////////////
        if (!entity.onGround) {
            this.Left_Wing_Membrane_1.rotateAngleZ = f2;
            this.Right_Wing_Membrane_1.rotateAngleZ = -f2;
        } else {
            this.Left_Wing_Membrane_1.rotateAngleZ = 0;
            this.Right_Wing_Membrane_1.rotateAngleZ = 0;
        }
    }

}

